BEGIN;

UPDATE foods SET name='Tuna and Vegetable Salad, Canned', base_name='Tuna and Vegetable Salad, Canned', needs_translation=0 WHERE food_id=23209 AND source='France_Ciqual';
UPDATE foods SET name='Composed Salad with Meat or Fish, Canned', base_name='Composed Salad with Meat or Fish, Canned', needs_translation=0 WHERE food_id=23210 AND source='France_Ciqual';
UPDATE foods SET name='Mushrooms a la Grecque, Canned', base_name='Mushrooms a la Grecque, Canned', needs_translation=0 WHERE food_id=23211 AND source='France_Ciqual';
UPDATE foods SET name='Potato Salad, Homemade', base_name='Potato Salad, Homemade', needs_translation=0 WHERE food_id=23212 AND source='France_Ciqual';
UPDATE foods SET name='Tabbouleh or Couscous Salad, Prepackaged', base_name='Tabbouleh or Couscous Salad, Prepackaged', needs_translation=0 WHERE food_id=23213 AND source='France_Ciqual';
UPDATE foods SET name='Potato Salad, Piedmont-Style, Prepackaged', base_name='Potato Salad, Piedmont-Style, Prepackaged', needs_translation=0 WHERE food_id=23214 AND source='France_Ciqual';
UPDATE foods SET name='Rice Salad, Canned', base_name='Rice Salad, Canned', needs_translation=0 WHERE food_id=23215 AND source='France_Ciqual';
UPDATE foods SET name='Pasta Salad, Vegetarian', base_name='Pasta Salad, Vegetarian', needs_translation=0 WHERE food_id=23216 AND source='France_Ciqual';
UPDATE foods SET name='Raw Vegetables, No Dressing (Average)', base_name='Raw Vegetables, No Dressing (Average)', needs_translation=0 WHERE food_id=23217 AND source='France_Ciqual';
UPDATE foods SET name='Pasta Salad with Vegetables, with Fish or Meat, Prepackaged', base_name='Pasta Salad with Vegetables, with Fish or Meat, Prepackaged', needs_translation=0 WHERE food_id=23218 AND source='France_Ciqual';
UPDATE foods SET name='Mixed Vegetable Salad, with Sauce, Prepackaged', base_name='Mixed Vegetable Salad, with Sauce, Prepackaged', needs_translation=0 WHERE food_id=23219 AND source='France_Ciqual';
UPDATE foods SET name='Chicken Caesar Salad (Lettuce, Cheese, Croutons, Sauce), Prepackaged', base_name='Chicken Caesar Salad (Lettuce, Cheese, Croutons, Sauce), Prepackaged', needs_translation=0 WHERE food_id=23220 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Salad Based on Bulgur and/or Quinoa and Vegetables, Prepackaged', base_name='Vegetable Salad Based on Bulgur and/or Quinoa and Vegetables, Prepackaged', needs_translation=0 WHERE food_id=23221 AND source='France_Ciqual';
UPDATE foods SET name='Grated Carrots, with Sauce, Prepackaged', base_name='Grated Carrots, with Sauce, Prepackaged', needs_translation=0 WHERE food_id=23222 AND source='France_Ciqual';
UPDATE foods SET name='Beet Salad, with Sauce, Prepackaged', base_name='Beet Salad, with Sauce, Prepackaged', needs_translation=0 WHERE food_id=23223 AND source='France_Ciqual';
UPDATE foods SET name='Cabbage Salad or Coleslaw, with Sauce, Prepackaged', base_name='Cabbage Salad or Coleslaw, with Sauce, Prepackaged', needs_translation=0 WHERE food_id=23224 AND source='France_Ciqual';
UPDATE foods SET name='Cucumber Salad with Cream/Fromage Blanc, Prepackaged', base_name='Cucumber Salad with Cream/Fromage Blanc, Prepackaged', needs_translation=0 WHERE food_id=23225 AND source='France_Ciqual';
UPDATE foods SET name='Lentil and Smoked Sausage Salad, Prepackaged', base_name='Lentil and Smoked Sausage Salad, Prepackaged', needs_translation=0 WHERE food_id=23226 AND source='France_Ciqual';
UPDATE foods SET name='Greek Salad, with Sauce, Prepackaged', base_name='Greek Salad, with Sauce, Prepackaged', needs_translation=0 WHERE food_id=23227 AND source='France_Ciqual';
UPDATE foods SET name='Nicoise-Style Rice Salad, with Sauce, Prepackaged', base_name='Nicoise-Style Rice Salad, with Sauce, Prepackaged', needs_translation=0 WHERE food_id=23228 AND source='France_Ciqual';
UPDATE foods SET name='Tabbouleh or Couscous Salad with Chicken, Prepackaged', base_name='Tabbouleh or Couscous Salad with Chicken, Prepackaged', needs_translation=0 WHERE food_id=23229 AND source='France_Ciqual';
UPDATE foods SET name='Lentil Soup, Prepackaged, To Reheat', base_name='Lentil Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23230 AND source='France_Ciqual';
UPDATE foods SET name='Poultry and Vegetable Soup, Prepackaged, To Reheat', base_name='Poultry and Vegetable Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23231 AND source='France_Ciqual';
UPDATE foods SET name='Mixed Vegetable Soup, Prepackaged, To Reheat', base_name='Mixed Vegetable Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23232 AND source='France_Ciqual';
UPDATE foods SET name='Fish and/or Shellfish Soup, Prepackaged, To Reheat', base_name='Fish and/or Shellfish Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23233 AND source='France_Ciqual';
UPDATE foods SET name='Mixed Vegetable Soup, Dehydrated, Reconstituted', base_name='Mixed Vegetable Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23234 AND source='France_Ciqual';
UPDATE foods SET name='Leek and Potato Soup, Prepackaged, To Reheat', base_name='Leek and Potato Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23235 AND source='France_Ciqual';
UPDATE foods SET name='Poultry and Vermicelli Soup, Prepackaged, To Reheat', base_name='Poultry and Vermicelli Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23236 AND source='France_Ciqual';
UPDATE foods SET name='Meat and Vegetable Bouillon, Pot-au-Feu Style, Ready to Eat', base_name='Meat and Vegetable Bouillon, Pot-au-Feu Style, Ready to Eat', needs_translation=0 WHERE food_id=23237 AND source='France_Ciqual';
UPDATE foods SET name='Onion Soup, Prepackaged, To Reheat', base_name='Onion Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23238 AND source='France_Ciqual';
UPDATE foods SET name='Mushroom Soup, Prepackaged, To Reheat', base_name='Mushroom Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23239 AND source='France_Ciqual';
UPDATE foods SET name='Carrot Soup, Prepackaged, To Reheat', base_name='Carrot Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23240 AND source='France_Ciqual';
UPDATE foods SET name='Tomato Soup, Prepackaged, To Reheat', base_name='Tomato Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23241 AND source='France_Ciqual';
UPDATE foods SET name='Chorba Frik Soup, Meat and Frik-Based', base_name='Chorba Frik Soup, Meat and Frik-Based', needs_translation=0 WHERE food_id=23242 AND source='France_Ciqual';
UPDATE foods SET name='Minestrone Soup, Prepackaged, To Reheat', base_name='Minestrone Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23243 AND source='France_Ciqual';
UPDATE foods SET name='Pistou Soup, Dehydrated, Reconstituted', base_name='Pistou Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23244 AND source='France_Ciqual';
UPDATE foods SET name='Fish and/or Shellfish Soup, Dehydrated, Reconstituted', base_name='Fish and/or Shellfish Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23245 AND source='France_Ciqual';
UPDATE foods SET name='Asian Soup, with Noodles, Dehydrated, Reconstituted', base_name='Asian Soup, with Noodles, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23246 AND source='France_Ciqual';
UPDATE foods SET name='Moroccan Soup, Dehydrated, Reconstituted', base_name='Moroccan Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23247 AND source='France_Ciqual';
UPDATE foods SET name='Leek and Potato Soup, Dehydrated, Reconstituted', base_name='Leek and Potato Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23248 AND source='France_Ciqual';
UPDATE foods SET name='Poultry and Vegetable Soup, Dehydrated, Reconstituted', base_name='Poultry and Vegetable Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23249 AND source='France_Ciqual';
UPDATE foods SET name='Beef Bouillon, Dehydrated, Reconstituted', base_name='Beef Bouillon, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23250 AND source='France_Ciqual';
UPDATE foods SET name='Asparagus Soup, Dehydrated, Reconstituted', base_name='Asparagus Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23251 AND source='France_Ciqual';
UPDATE foods SET name='Tomato and Vermicelli Soup, Prepackaged, To Reheat', base_name='Tomato and Vermicelli Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23252 AND source='France_Ciqual';
UPDATE foods SET name='Grain and Vegetable Soup, Dehydrated, Reconstituted', base_name='Grain and Vegetable Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23253 AND source='France_Ciqual';
UPDATE foods SET name='Tomato Soup, Dehydrated, Reconstituted', base_name='Tomato Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23254 AND source='France_Ciqual';
UPDATE foods SET name='Mushroom Soup, Dehydrated, Reconstituted', base_name='Mushroom Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23255 AND source='France_Ciqual';
UPDATE foods SET name='Onion Soup, Dehydrated, Reconstituted', base_name='Onion Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23256 AND source='France_Ciqual';
UPDATE foods SET name='Pumpkin Soup, Prepackaged, To Reheat', base_name='Pumpkin Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23257 AND source='France_Ciqual';
UPDATE foods SET name='Poultry Bouillon, Dehydrated, Reconstituted', base_name='Poultry Bouillon, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23258 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Bouillon, Dehydrated, Reconstituted', base_name='Vegetable Bouillon, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23259 AND source='France_Ciqual';
UPDATE foods SET name='Tomato and Vermicelli Soup, Dehydrated, Reconstituted', base_name='Tomato and Vermicelli Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23260 AND source='France_Ciqual';
UPDATE foods SET name='Poultry and Vermicelli Soup, Dehydrated, Reconstituted', base_name='Poultry and Vermicelli Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23261 AND source='France_Ciqual';
UPDATE foods SET name='Pistou Soup, Prepackaged, To Reheat', base_name='Pistou Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23262 AND source='France_Ciqual';
UPDATE foods SET name='Pumpkin Soup, Dehydrated, Reconstituted', base_name='Pumpkin Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23263 AND source='France_Ciqual';
UPDATE foods SET name='Asian Soup, with Noodles, Prepackaged, To Reheat', base_name='Asian Soup, with Noodles, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23264 AND source='France_Ciqual';
UPDATE foods SET name='Minestrone Soup, Dehydrated, Reconstituted', base_name='Minestrone Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23265 AND source='France_Ciqual';
UPDATE foods SET name='Watercress Soup, Dehydrated, Reconstituted', base_name='Watercress Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23266 AND source='France_Ciqual';
UPDATE foods SET name='Watercress Soup, Prepackaged, To Reheat', base_name='Watercress Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23267 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Soup with Cheese, Prepackaged, To Reheat', base_name='Vegetable Soup with Cheese, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23268 AND source='France_Ciqual';
UPDATE foods SET name='Green Vegetable Soup, Prepackaged, To Reheat', base_name='Green Vegetable Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23269 AND source='France_Ciqual';
UPDATE foods SET name='Green Vegetable Soup, Dehydrated, Reconstituted', base_name='Green Vegetable Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23270 AND source='France_Ciqual';
UPDATE foods SET name='Split Pea Soup, Prepackaged, To Reheat', base_name='Split Pea Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23271 AND source='France_Ciqual';
UPDATE foods SET name='Cold Soup, Gazpacho Type, Prepackaged', base_name='Cold Soup, Gazpacho Type, Prepackaged', needs_translation=0 WHERE food_id=23272 AND source='France_Ciqual';
UPDATE foods SET name='Asparagus Soup, Prepackaged, To Reheat', base_name='Asparagus Soup, Prepackaged, To Reheat', needs_translation=0 WHERE food_id=23273 AND source='France_Ciqual';
UPDATE foods SET name='Soup (Average)', base_name='Soup (Average)', needs_translation=0 WHERE food_id=23274 AND source='France_Ciqual';
UPDATE foods SET name='Miso Soup, Dehydrated, Reconstituted', base_name='Miso Soup, Dehydrated, Reconstituted', needs_translation=0 WHERE food_id=23275 AND source='France_Ciqual';
UPDATE foods SET name='Tripe, Caen-Style (Tripes a la Mode de Caen)', base_name='Tripe, Caen-Style (Tripes a la Mode de Caen)', needs_translation=0 WHERE food_id=23276 AND source='France_Ciqual';
UPDATE foods SET name='Tripe, Caen-Style (Tripes a la Mode de Caen), Prepackaged', base_name='Tripe, Caen-Style (Tripes a la Mode de Caen), Prepackaged', needs_translation=0 WHERE food_id=23277 AND source='France_Ciqual';
UPDATE foods SET name='Tripe with Tomato or Provencal-Style', base_name='Tripe with Tomato or Provencal-Style', needs_translation=0 WHERE food_id=23278 AND source='France_Ciqual';
UPDATE foods SET name='Veal Blanquette (Blanquette de Veau)', base_name='Veal Blanquette (Blanquette de Veau)', needs_translation=0 WHERE food_id=23279 AND source='France_Ciqual';
UPDATE foods SET name='Beef Bourguignon', base_name='Beef Bourguignon', needs_translation=0 WHERE food_id=23280 AND source='France_Ciqual';
UPDATE foods SET name='Lamb Curry Saute, Prepackaged', base_name='Lamb Curry Saute, Prepackaged', needs_translation=0 WHERE food_id=23281 AND source='France_Ciqual';
UPDATE foods SET name='Duck in Sauce (Green Pepper, Hunter-Style, etc.), Prepackaged', base_name='Duck in Sauce (Green Pepper, Hunter-Style, etc.), Prepackaged', needs_translation=0 WHERE food_id=23282 AND source='France_Ciqual';
UPDATE foods SET name='Rabbit with Mustard, Prepackaged', base_name='Rabbit with Mustard, Prepackaged', needs_translation=0 WHERE food_id=23283 AND source='France_Ciqual';
UPDATE foods SET name='Coq au Vin', base_name='Coq au Vin', needs_translation=0 WHERE food_id=23284 AND source='France_Ciqual';
UPDATE foods SET name='Veal Paupiette (Stuffed Veal Roll)', base_name='Veal Paupiette (Stuffed Veal Roll)', needs_translation=0 WHERE food_id=23285 AND source='France_Ciqual';
UPDATE foods SET name='Poultry Paupiette (Stuffed Poultry Roll)', base_name='Poultry Paupiette (Stuffed Poultry Roll)', needs_translation=0 WHERE food_id=23286 AND source='France_Ciqual';
UPDATE foods SET name='Meat in Sauce (Average)', base_name='Meat in Sauce (Average)', needs_translation=0 WHERE food_id=23287 AND source='France_Ciqual';
UPDATE foods SET name='Chicken Curry with Coconut Milk', base_name='Chicken Curry with Coconut Milk', needs_translation=0 WHERE food_id=23288 AND source='France_Ciqual';
UPDATE foods SET name='Molokhia, Beef and Jute Leaf Dish, Homemade', base_name='Molokhia, Beef and Jute Leaf Dish, Homemade', needs_translation=0 WHERE food_id=23289 AND source='France_Ciqual';
UPDATE foods SET name='Deviled Pork Shoulder (Palette a la Diable), Prepackaged', base_name='Deviled Pork Shoulder (Palette a la Diable), Prepackaged', needs_translation=0 WHERE food_id=23290 AND source='France_Ciqual';
UPDATE foods SET name='Beef Tongue with Madeira Sauce, Prepackaged', base_name='Beef Tongue with Madeira Sauce, Prepackaged', needs_translation=0 WHERE food_id=23291 AND source='France_Ciqual';
UPDATE foods SET name='Caramelized Pork, Prepackaged', base_name='Caramelized Pork, Prepackaged', needs_translation=0 WHERE food_id=23292 AND source='France_Ciqual';
UPDATE foods SET name='Beef Meatballs in Tomato Sauce, Prepackaged', base_name='Beef Meatballs in Tomato Sauce, Prepackaged', needs_translation=0 WHERE food_id=23293 AND source='France_Ciqual';
UPDATE foods SET name='Veal Paupiette, Prepackaged, Oven-Cooked', base_name='Veal Paupiette, Prepackaged, Oven-Cooked', needs_translation=0 WHERE food_id=23294 AND source='France_Ciqual';
UPDATE foods SET name='Beef Carpaccio, with Marinade', base_name='Beef Carpaccio, with Marinade', needs_translation=0 WHERE food_id=23295 AND source='France_Ciqual';
UPDATE foods SET name='Yakitori (Grilled Japanese Skewers in Sauce)', base_name='Yakitori (Grilled Japanese Skewers in Sauce)', needs_translation=0 WHERE food_id=23296 AND source='France_Ciqual';
UPDATE foods SET name='Beef Skewer, Cooked', base_name='Beef Skewer, Cooked', needs_translation=0 WHERE food_id=23297 AND source='France_Ciqual';
UPDATE foods SET name='Poultry Skewer, Cooked', base_name='Poultry Skewer, Cooked', needs_translation=0 WHERE food_id=23298 AND source='France_Ciqual';
UPDATE foods SET name='Meat Shepherd''s Pie (Hachis Parmentier), Prepackaged', base_name='Meat Shepherd''s Pie (Hachis Parmentier), Prepackaged', needs_translation=0 WHERE food_id=23299 AND source='France_Ciqual';
UPDATE foods SET name='Couscous with Mutton', base_name='Couscous with Mutton', needs_translation=0 WHERE food_id=23300 AND source='France_Ciqual';
UPDATE foods SET name='Couscous with Meat or Chicken, Prepackaged, Reduced-Fat', base_name='Couscous with Meat or Chicken, Prepackaged, Reduced-Fat', needs_translation=0 WHERE food_id=23301 AND source='France_Ciqual';
UPDATE foods SET name='Pan-Fried Potatoes, Pre-Fried, with Bacon Bits or Chicken and Others, No Green Vegetables, Prepackaged', base_name='Pan-Fried Potatoes, Pre-Fried, with Bacon Bits or Chicken and Others, No Green Vegetables, Prepackaged', needs_translation=0 WHERE food_id=23302 AND source='France_Ciqual';
UPDATE foods SET name='Royal Couscous (with Several Meats), Prepackaged', base_name='Royal Couscous (with Several Meats), Prepackaged', needs_translation=0 WHERE food_id=23303 AND source='France_Ciqual';
UPDATE foods SET name='Couscous with Chicken', base_name='Couscous with Chicken', needs_translation=0 WHERE food_id=23304 AND source='France_Ciqual';
UPDATE foods SET name='Couscous with Meat, Prepackaged', base_name='Couscous with Meat, Prepackaged', needs_translation=0 WHERE food_id=23305 AND source='France_Ciqual';
UPDATE foods SET name='Duck Shepherd''s Pie (Parmentier de Canard), Prepackaged', base_name='Duck Shepherd''s Pie (Parmentier de Canard), Prepackaged', needs_translation=0 WHERE food_id=23306 AND source='France_Ciqual';
UPDATE foods SET name='Duck Shepherd''s Pie (Parmentier de Canard), Prepackaged, Cooked', base_name='Duck Shepherd''s Pie (Parmentier de Canard), Prepackaged, Cooked', needs_translation=0 WHERE food_id=23307 AND source='France_Ciqual';
UPDATE foods SET name='Cassoulet, Canned', base_name='Cassoulet, Canned', needs_translation=0 WHERE food_id=23308 AND source='France_Ciqual';
UPDATE foods SET name='Sauerkraut with Meats (Choucroute Garnie), Prepackaged', base_name='Sauerkraut with Meats (Choucroute Garnie), Prepackaged', needs_translation=0 WHERE food_id=23309 AND source='France_Ciqual';
UPDATE foods SET name='Salt Pork or Sausage with Lentils, Prepackaged', base_name='Salt Pork or Sausage with Lentils, Prepackaged', needs_translation=0 WHERE food_id=23310 AND source='France_Ciqual';
UPDATE foods SET name='Pot-au-Feu, Prepackaged', base_name='Pot-au-Feu, Prepackaged', needs_translation=0 WHERE food_id=23311 AND source='France_Ciqual';
UPDATE foods SET name='Beef with Carrots', base_name='Beef with Carrots', needs_translation=0 WHERE food_id=23312 AND source='France_Ciqual';
UPDATE foods SET name='Auvergne-Style Hotpot (Cabbage and Pork)', base_name='Auvergne-Style Hotpot (Cabbage and Pork)', needs_translation=0 WHERE food_id=23313 AND source='France_Ciqual';
UPDATE foods SET name='Cassoulet with Pork, Canned', base_name='Cassoulet with Pork, Canned', needs_translation=0 WHERE food_id=23314 AND source='France_Ciqual';
UPDATE foods SET name='Cassoulet with Duck or Goose, Canned', base_name='Cassoulet with Duck or Goose, Canned', needs_translation=0 WHERE food_id=23315 AND source='France_Ciqual';
UPDATE foods SET name='Stuffed Tomato', base_name='Stuffed Tomato', needs_translation=0 WHERE food_id=23316 AND source='France_Ciqual';
UPDATE foods SET name='Stuffed Cabbage, Prepackaged', base_name='Stuffed Cabbage, Prepackaged', needs_translation=0 WHERE food_id=23317 AND source='France_Ciqual';
UPDATE foods SET name='Chili con Carne, Prepackaged', base_name='Chili con Carne, Prepackaged', needs_translation=0 WHERE food_id=23318 AND source='France_Ciqual';
UPDATE foods SET name='Moussaka', base_name='Moussaka', needs_translation=0 WHERE food_id=23319 AND source='France_Ciqual';
UPDATE foods SET name='Lamb Navarin with Vegetables', base_name='Lamb Navarin with Vegetables', needs_translation=0 WHERE food_id=23320 AND source='France_Ciqual';
UPDATE foods SET name='Mutton Tagine', base_name='Mutton Tagine', needs_translation=0 WHERE food_id=23321 AND source='France_Ciqual';
UPDATE foods SET name='Osso Buco', base_name='Osso Buco', needs_translation=0 WHERE food_id=23322 AND source='France_Ciqual';
UPDATE foods SET name='Basque-Style Chicken, Prepackaged', base_name='Basque-Style Chicken, Prepackaged', needs_translation=0 WHERE food_id=23323 AND source='France_Ciqual';
UPDATE foods SET name='Chicken Tagine, Prepackaged', base_name='Chicken Tagine, Prepackaged', needs_translation=0 WHERE food_id=23324 AND source='France_Ciqual';
UPDATE foods SET name='Chop Suey (Pork or Chicken), Prepackaged', base_name='Chop Suey (Pork or Chicken), Prepackaged', needs_translation=0 WHERE food_id=23325 AND source='France_Ciqual';
UPDATE foods SET name='Stuffed Vegetables (Except Tomato)', base_name='Stuffed Vegetables (Except Tomato)', needs_translation=0 WHERE food_id=23326 AND source='France_Ciqual';
UPDATE foods SET name='Mussels Mariniere (Onions and White Wine)', base_name='Mussels Mariniere (Onions and White Wine)', needs_translation=0 WHERE food_id=23327 AND source='France_Ciqual';
UPDATE foods SET name='Stuffed Mussels (Fat, Herb-Garlic Mix...), Prepackaged, Raw', base_name='Stuffed Mussels (Fat, Herb-Garlic Mix...), Prepackaged, Raw', needs_translation=0 WHERE food_id=23328 AND source='France_Ciqual';
UPDATE foods SET name='Fish and/or Seafood Gratin or Casserole, Prepackaged, Raw', base_name='Fish and/or Seafood Gratin or Casserole, Prepackaged, Raw', needs_translation=0 WHERE food_id=23329 AND source='France_Ciqual';
UPDATE foods SET name='Fish and/or Seafood Gratin or Casserole, Prepackaged, Cooked', base_name='Fish and/or Seafood Gratin or Casserole, Prepackaged, Cooked', needs_translation=0 WHERE food_id=23330 AND source='France_Ciqual';
UPDATE foods SET name='Salmon with Sorrel, Prepackaged', base_name='Salmon with Sorrel, Prepackaged', needs_translation=0 WHERE food_id=23331 AND source='France_Ciqual';
UPDATE foods SET name='White Fish, Bordelaise-Style, Prepackaged', base_name='White Fish, Bordelaise-Style, Prepackaged', needs_translation=0 WHERE food_id=23332 AND source='France_Ciqual';
UPDATE foods SET name='White Fish, Provencal or Nicoise-Style (Tomato Sauce), Prepackaged', base_name='White Fish, Provencal or Nicoise-Style (Tomato Sauce), Prepackaged', needs_translation=0 WHERE food_id=23333 AND source='France_Ciqual';
UPDATE foods SET name='White Fish, Florentine-Style (Spinach Sauce), Prepackaged', base_name='White Fish, Florentine-Style (Spinach Sauce), Prepackaged', needs_translation=0 WHERE food_id=23334 AND source='France_Ciqual';
UPDATE foods SET name='White Fish, Mariniere-Style (Onion, White Wine, Mussel Sauce), Prepackaged', base_name='White Fish, Mariniere-Style (Onion, White Wine, Mussel Sauce), Prepackaged', needs_translation=0 WHERE food_id=23335 AND source='France_Ciqual';
UPDATE foods SET name='White Fish with Mustard Sauce, Prepackaged', base_name='White Fish with Mustard Sauce, Prepackaged', needs_translation=0 WHERE food_id=23336 AND source='France_Ciqual';
UPDATE foods SET name='White Fish, Parisienne-Style (Mushroom Sauce), Prepackaged', base_name='White Fish, Parisienne-Style (Mushroom Sauce), Prepackaged', needs_translation=0 WHERE food_id=23337 AND source='France_Ciqual';
UPDATE foods SET name='White Fish with Tarragon, Prepackaged', base_name='White Fish with Tarragon, Prepackaged', needs_translation=0 WHERE food_id=23338 AND source='France_Ciqual';
UPDATE foods SET name='White Fish with Sorrel Sauce, Prepackaged', base_name='White Fish with Sorrel Sauce, Prepackaged', needs_translation=0 WHERE food_id=23339 AND source='France_Ciqual';
UPDATE foods SET name='Stuffed Salmon, Prepackaged', base_name='Stuffed Salmon, Prepackaged', needs_translation=0 WHERE food_id=23340 AND source='France_Ciqual';
UPDATE foods SET name='Fish Skewer', base_name='Fish Skewer', needs_translation=0 WHERE food_id=23341 AND source='France_Ciqual';
UPDATE foods SET name='Shrimp Skewer', base_name='Shrimp Skewer', needs_translation=0 WHERE food_id=23342 AND source='France_Ciqual';
UPDATE foods SET name='Fish in Sauce, Frozen', base_name='Fish in Sauce, Frozen', needs_translation=0 WHERE food_id=23343 AND source='France_Ciqual';
UPDATE foods SET name='Cooked Fish (Average)', base_name='Cooked Fish (Average)', needs_translation=0 WHERE food_id=23344 AND source='France_Ciqual';
UPDATE foods SET name='White Fish, Cooked (Average)', base_name='White Fish, Cooked (Average)', needs_translation=0 WHERE food_id=23345 AND source='France_Ciqual';
UPDATE foods SET name='White Fish, Sea, Cooked (Average)', base_name='White Fish, Sea, Cooked (Average)', needs_translation=0 WHERE food_id=23346 AND source='France_Ciqual';
UPDATE foods SET name='Paella', base_name='Paella', needs_translation=0 WHERE food_id=23347 AND source='France_Ciqual';
UPDATE foods SET name='Couscous with Fish', base_name='Couscous with Fish', needs_translation=0 WHERE food_id=23348 AND source='France_Ciqual';
UPDATE foods SET name='Fish Gratin with Mashed Potato or Brandade or Fish Shepherd''s Pie, Prepackaged', base_name='Fish Gratin with Mashed Potato or Brandade or Fish Shepherd''s Pie, Prepackaged', needs_translation=0 WHERE food_id=23349 AND source='France_Ciqual';
UPDATE foods SET name='Sushi or Maki with Seafood', base_name='Sushi or Maki with Seafood', needs_translation=0 WHERE food_id=23350 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Terrine or Mousse', base_name='Vegetable Terrine or Mousse', needs_translation=0 WHERE food_id=23351 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Flan', base_name='Vegetable Flan', needs_translation=0 WHERE food_id=23352 AND source='France_Ciqual';
UPDATE foods SET name='White Beans in Tomato Sauce, Canned', base_name='White Beans in Tomato Sauce, Canned', needs_translation=0 WHERE food_id=23353 AND source='France_Ciqual';
UPDATE foods SET name='Basque-Style Piperade, Prepackaged', base_name='Basque-Style Piperade, Prepackaged', needs_translation=0 WHERE food_id=23354 AND source='France_Ciqual';
UPDATE foods SET name='Seasoned Pan-Fried Vegetables, No Mushroom, Frozen, Raw', base_name='Seasoned Pan-Fried Vegetables, No Mushroom, Frozen, Raw', needs_translation=0 WHERE food_id=23355 AND source='France_Ciqual';
UPDATE foods SET name='Seasoned Pan-Fried Vegetables, Asian-Style or Vegetable Wok, Frozen, Raw', base_name='Seasoned Pan-Fried Vegetables, Asian-Style or Vegetable Wok, Frozen, Raw', needs_translation=0 WHERE food_id=23356 AND source='France_Ciqual';
UPDATE foods SET name='Seasoned Pan-Fried Vegetables, Grilled, Southern or Mediterranean-Style, Frozen, Raw', base_name='Seasoned Pan-Fried Vegetables, Grilled, Southern or Mediterranean-Style, Frozen, Raw', needs_translation=0 WHERE food_id=23357 AND source='France_Ciqual';
UPDATE foods SET name='Seasoned Pan-Fried Vegetables with Mushrooms ("Rustic"), Frozen', base_name='Seasoned Pan-Fried Vegetables with Mushrooms ("Rustic"), Frozen', needs_translation=0 WHERE food_id=23358 AND source='France_Ciqual';
UPDATE foods SET name='Cooked Ratatouille, Prepackaged', base_name='Cooked Ratatouille, Prepackaged', needs_translation=0 WHERE food_id=23359 AND source='France_Ciqual';
UPDATE foods SET name='Creamed Spinach, Prepackaged', base_name='Creamed Spinach, Prepackaged', needs_translation=0 WHERE food_id=23360 AND source='France_Ciqual';
UPDATE foods SET name='Eggplant Gratin, Prepackaged', base_name='Eggplant Gratin, Prepackaged', needs_translation=0 WHERE food_id=23361 AND source='France_Ciqual';
UPDATE foods SET name='Dauphinoise Potato Gratin (Gratin Dauphinois)', base_name='Dauphinoise Potato Gratin (Gratin Dauphinois)', needs_translation=0 WHERE food_id=23362 AND source='France_Ciqual';
UPDATE foods SET name='Endive with Ham (Endive au Jambon)', base_name='Endive with Ham (Endive au Jambon)', needs_translation=0 WHERE food_id=23363 AND source='France_Ciqual';
UPDATE foods SET name='Cauliflower Gratin, Prepackaged', base_name='Cauliflower Gratin, Prepackaged', needs_translation=0 WHERE food_id=23364 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Gratin', base_name='Vegetable Gratin', needs_translation=0 WHERE food_id=23365 AND source='France_Ciqual';
UPDATE foods SET name='Eggplant Relish (Eggplant, Tomatoes, Onions), Prepackaged', base_name='Eggplant Relish (Eggplant, Tomatoes, Onions), Prepackaged', needs_translation=0 WHERE food_id=23366 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Patty or Cake, Pre-Fried, Frozen', base_name='Vegetable Patty or Cake, Pre-Fried, Frozen', needs_translation=0 WHERE food_id=23367 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Patty or Cake, Pre-Fried, Frozen, Cooked', base_name='Vegetable Patty or Cake, Pre-Fried, Frozen, Cooked', needs_translation=0 WHERE food_id=23368 AND source='France_Ciqual';
UPDATE foods SET name='Sauerkraut, Plain, Drained, Cooked', base_name='Sauerkraut, Plain, Drained, Cooked', needs_translation=0 WHERE food_id=23369 AND source='France_Ciqual';
UPDATE foods SET name='Provencal-Style Tomato, Homemade', base_name='Provencal-Style Tomato, Homemade', needs_translation=0 WHERE food_id=23370 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Fritter', base_name='Vegetable Fritter', needs_translation=0 WHERE food_id=23371 AND source='France_Ciqual';
UPDATE foods SET name='Falafel or Chickpea and/or Fava Bean Patty, Fried', base_name='Falafel or Chickpea and/or Fava Bean Patty, Fried', needs_translation=0 WHERE food_id=23372 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Gratin in White (Bechamel-Style) Sauce, Cooked', base_name='Vegetable Gratin in White (Bechamel-Style) Sauce, Cooked', needs_translation=0 WHERE food_id=23373 AND source='France_Ciqual';
UPDATE foods SET name='Falafel or Chickpea and/or Fava Bean Patty, Prepackaged', base_name='Falafel or Chickpea and/or Fava Bean Patty, Prepackaged', needs_translation=0 WHERE food_id=23374 AND source='France_Ciqual';
UPDATE foods SET name='Precooked Durum Wheat, Prepared, Microwaveable Pouch', base_name='Precooked Durum Wheat, Prepared, Microwaveable Pouch', needs_translation=0 WHERE food_id=23375 AND source='France_Ciqual';
UPDATE foods SET name='Precooked Durum Wheat, Whole Grains, Prepared, Pan-Fried', base_name='Precooked Durum Wheat, Whole Grains, Prepared, Pan-Fried', needs_translation=0 WHERE food_id=23376 AND source='France_Ciqual';
UPDATE foods SET name='Meat Ravioli, Tomato Sauce, Canned', base_name='Meat Ravioli, Tomato Sauce, Canned', needs_translation=0 WHERE food_id=23377 AND source='France_Ciqual';
UPDATE foods SET name='Lasagna or Cannelloni with Meat (Bolognese)', base_name='Lasagna or Cannelloni with Meat (Bolognese)', needs_translation=0 WHERE food_id=23378 AND source='France_Ciqual';
UPDATE foods SET name='Bolognese Pasta (Spaghetti, Tagliatelle...)', base_name='Bolognese Pasta (Spaghetti, Tagliatelle...)', needs_translation=0 WHERE food_id=23379 AND source='France_Ciqual';
UPDATE foods SET name='Cantonese Rice', base_name='Cantonese Rice', needs_translation=0 WHERE food_id=23380 AND source='France_Ciqual';
UPDATE foods SET name='Steamed Chinese Shrimp Dumplings, Cooked', base_name='Steamed Chinese Shrimp Dumplings, Cooked', needs_translation=0 WHERE food_id=23381 AND source='France_Ciqual';
UPDATE foods SET name='Pasta Gratin', base_name='Pasta Gratin', needs_translation=0 WHERE food_id=23382 AND source='France_Ciqual';
UPDATE foods SET name='Lasagna or Cannelloni with Vegetables, Prepackaged, Cooked', base_name='Lasagna or Cannelloni with Vegetables, Prepackaged, Cooked', needs_translation=0 WHERE food_id=23383 AND source='France_Ciqual';
UPDATE foods SET name='Carbonara Pasta (Spaghetti, Tagliatelle...)', base_name='Carbonara Pasta (Spaghetti, Tagliatelle...)', needs_translation=0 WHERE food_id=23384 AND source='France_Ciqual';
UPDATE foods SET name='Lasagna or Cannelloni with Fish, Prepackaged', base_name='Lasagna or Cannelloni with Fish, Prepackaged', needs_translation=0 WHERE food_id=23385 AND source='France_Ciqual';
UPDATE foods SET name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini, Ravioles du Dauphine), Cheese, Cooked', base_name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini, Ravioles du Dauphine), Cheese, Cooked', needs_translation=0 WHERE food_id=23386 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Couscous, Prepackaged', base_name='Vegetable Couscous, Prepackaged', needs_translation=0 WHERE food_id=23387 AND source='France_Ciqual';
UPDATE foods SET name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Cheese and Vegetables, Prepackaged, Cooked', base_name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Cheese and Vegetables, Prepackaged, Cooked', needs_translation=0 WHERE food_id=23388 AND source='France_Ciqual';
UPDATE foods SET name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Meat (e.g. Bolognese), Prepackaged, Raw', base_name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Meat (e.g. Bolognese), Prepackaged, Raw', needs_translation=0 WHERE food_id=23389 AND source='France_Ciqual';
UPDATE foods SET name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Meat (e.g. Bolognese), Prepackaged, Cooked', base_name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Meat (e.g. Bolognese), Prepackaged, Cooked', needs_translation=0 WHERE food_id=23390 AND source='France_Ciqual';
UPDATE foods SET name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini, Ravioles du Dauphine), Cheese, Prepackaged, Raw', base_name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini, Ravioles du Dauphine), Cheese, Prepackaged, Raw', needs_translation=0 WHERE food_id=23391 AND source='France_Ciqual';
UPDATE foods SET name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Cheese and Vegetables, Prepackaged, Raw', base_name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Cheese and Vegetables, Prepackaged, Raw', needs_translation=0 WHERE food_id=23392 AND source='France_Ciqual';
UPDATE foods SET name='Stir-Fried/Pan-Fried Noodles with Shrimp', base_name='Stir-Fried/Pan-Fried Noodles with Shrimp', needs_translation=0 WHERE food_id=23393 AND source='France_Ciqual';
UPDATE foods SET name='White Rice, with Chicken, Prepackaged, Cooked', base_name='White Rice, with Chicken, Prepackaged, Cooked', needs_translation=0 WHERE food_id=23394 AND source='France_Ciqual';
UPDATE foods SET name='White Rice, with Vegetables and Meat, Prepackaged, Cooked', base_name='White Rice, with Vegetables and Meat, Prepackaged, Cooked', needs_translation=0 WHERE food_id=23395 AND source='France_Ciqual';
UPDATE foods SET name='Risotto, Vegetable, Prepackaged', base_name='Risotto, Vegetable, Prepackaged', needs_translation=0 WHERE food_id=23396 AND source='France_Ciqual';
UPDATE foods SET name='Risotto, Seafood, Prepackaged', base_name='Risotto, Seafood, Prepackaged', needs_translation=0 WHERE food_id=23397 AND source='France_Ciqual';
UPDATE foods SET name='Risotto, Cheese, Prepackaged', base_name='Risotto, Cheese, Prepackaged', needs_translation=0 WHERE food_id=23398 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Ravioli, Tomato Sauce, Canned', base_name='Vegetable Ravioli, Tomato Sauce, Canned', needs_translation=0 WHERE food_id=23399 AND source='France_Ciqual';
UPDATE foods SET name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Vegetable, Prepackaged, Cooked', base_name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Vegetable, Prepackaged, Cooked', needs_translation=0 WHERE food_id=23400 AND source='France_Ciqual';
UPDATE foods SET name='Pasta in Cheese Sauce (Spaghetti, Tagliatelle...), Prepackaged', base_name='Pasta in Cheese Sauce (Spaghetti, Tagliatelle...), Prepackaged', needs_translation=0 WHERE food_id=23401 AND source='France_Ciqual';
UPDATE foods SET name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Vegetable, Prepackaged, Raw', base_name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Vegetable, Prepackaged, Raw', needs_translation=0 WHERE food_id=23402 AND source='France_Ciqual';
UPDATE foods SET name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Cooked (Average)', base_name='Fresh Stuffed Pasta (e.g. Ravioli, Tortellini), Cooked (Average)', needs_translation=0 WHERE food_id=23403 AND source='France_Ciqual';
UPDATE foods SET name='Stuffed Vine Leaf with Rice or Dolmas, Drained, Prepackaged', base_name='Stuffed Vine Leaf with Rice or Dolmas, Drained, Prepackaged', needs_translation=0 WHERE food_id=23404 AND source='France_Ciqual';
UPDATE foods SET name='Lasagna or Cannelloni with Vegetables, Prepackaged, Cooked', base_name='Lasagna or Cannelloni with Vegetables, Prepackaged, Cooked', needs_translation=0 WHERE food_id=23405 AND source='France_Ciqual';
UPDATE foods SET name='Lasagna or Cannelloni with Vegetables and Goat Cheese, Prepackaged, Cooked', base_name='Lasagna or Cannelloni with Vegetables and Goat Cheese, Prepackaged, Cooked', needs_translation=0 WHERE food_id=23406 AND source='France_Ciqual';
UPDATE foods SET name='Lasagna or Cannelloni with Cheese and Spinach, Prepackaged', base_name='Lasagna or Cannelloni with Cheese and Spinach, Prepackaged', needs_translation=0 WHERE food_id=23407 AND source='France_Ciqual';
UPDATE foods SET name='Aligot (Mashed Potato with Fresh Tomme Cheese), Prepackaged', base_name='Aligot (Mashed Potato with Fresh Tomme Cheese), Prepackaged', needs_translation=0 WHERE food_id=23408 AND source='France_Ciqual';
UPDATE foods SET name='Breaded Goat Cheese to Brown, Prepackaged', base_name='Breaded Goat Cheese to Brown, Prepackaged', needs_translation=0 WHERE food_id=23409 AND source='France_Ciqual';
UPDATE foods SET name='Cheese Souffle', base_name='Cheese Souffle', needs_translation=0 WHERE food_id=23410 AND source='France_Ciqual';
UPDATE foods SET name='Tartiflette, Prepackaged', base_name='Tartiflette, Prepackaged', needs_translation=0 WHERE food_id=23411 AND source='France_Ciqual';
UPDATE foods SET name='Gougeres (Cheese Puffs)', base_name='Gougeres (Cheese Puffs)', needs_translation=0 WHERE food_id=23412 AND source='France_Ciqual';
UPDATE foods SET name='Cheese Preparation for Savoyard Fondue, Prepackaged', base_name='Cheese Preparation for Savoyard Fondue, Prepackaged', needs_translation=0 WHERE food_id=23413 AND source='France_Ciqual';
UPDATE foods SET name='Breaded Cheese with Ham', base_name='Breaded Cheese with Ham', needs_translation=0 WHERE food_id=23414 AND source='France_Ciqual';
UPDATE foods SET name='Plant-Based Cutlet or Steak, Soy-Based', base_name='Plant-Based Cutlet or Steak, Soy-Based', needs_translation=0 WHERE food_id=23415 AND source='France_Ciqual';
UPDATE foods SET name='Tempeh', base_name='Tempeh', needs_translation=0 WHERE food_id=23416 AND source='France_Ciqual';
UPDATE foods SET name='Wheat-Based Nuggets (Soy-Free), Prepackaged', base_name='Wheat-Based Nuggets (Soy-Free), Prepackaged', needs_translation=0 WHERE food_id=23417 AND source='France_Ciqual';
UPDATE foods SET name='Soy and Wheat Nuggets (Not Vegan), Prepackaged', base_name='Soy and Wheat Nuggets (Not Vegan), Prepackaged', needs_translation=0 WHERE food_id=23418 AND source='France_Ciqual';
UPDATE foods SET name='Soy and Wheat Nuggets (Vegan), Prepackaged', base_name='Soy and Wheat Nuggets (Vegan), Prepackaged', needs_translation=0 WHERE food_id=23419 AND source='France_Ciqual';
UPDATE foods SET name='Soy and Wheat Breaded Product (Not Vegan)', base_name='Soy and Wheat Breaded Product (Not Vegan)', needs_translation=0 WHERE food_id=23420 AND source='France_Ciqual';
UPDATE foods SET name='Breaded Soy and Wheat Stick (Vegan), Prepackaged', base_name='Breaded Soy and Wheat Stick (Vegan), Prepackaged', needs_translation=0 WHERE food_id=23421 AND source='France_Ciqual';
UPDATE foods SET name='Breaded Cutlet, Soy, Wheat and Cheese, Cordon Bleu Type, Prepackaged', base_name='Breaded Cutlet, Soy, Wheat and Cheese, Cordon Bleu Type, Prepackaged', needs_translation=0 WHERE food_id=23422 AND source='France_Ciqual';
UPDATE foods SET name='Tofu Ravioli, Tomato Sauce, Prepackaged', base_name='Tofu Ravioli, Tomato Sauce, Prepackaged', needs_translation=0 WHERE food_id=23423 AND source='France_Ciqual';
UPDATE foods SET name='Grain Patty with Cheese (Soy-Free), Prepackaged', base_name='Grain Patty with Cheese (Soy-Free), Prepackaged', needs_translation=0 WHERE food_id=23424 AND source='France_Ciqual';
UPDATE foods SET name='Grain Patty with Vegetables (Soy-Free), Prepackaged', base_name='Grain Patty with Vegetables (Soy-Free), Prepackaged', needs_translation=0 WHERE food_id=23425 AND source='France_Ciqual';
UPDATE foods SET name='Plant-Based Meatball, Soy and/or Wheat, Prepackaged', base_name='Plant-Based Meatball, Soy and/or Wheat, Prepackaged', needs_translation=0 WHERE food_id=23426 AND source='France_Ciqual';
UPDATE foods SET name='Patty or Cake with Lentils, Soy and Vegetables, Prepackaged', base_name='Patty or Cake with Lentils, Soy and Vegetables, Prepackaged', needs_translation=0 WHERE food_id=23427 AND source='France_Ciqual';
UPDATE foods SET name='Patty or Cake with Wheat (Seitan) and Vegetables, Prepackaged', base_name='Patty or Cake with Wheat (Seitan) and Vegetables, Prepackaged', needs_translation=0 WHERE food_id=23428 AND source='France_Ciqual';
UPDATE foods SET name='Patty or Cake with Wheat and Soy (Vegan), Prepackaged', base_name='Patty or Cake with Wheat and Soy (Vegan), Prepackaged', needs_translation=0 WHERE food_id=23429 AND source='France_Ciqual';
UPDATE foods SET name='Patty or Cake with Wheat and Soy (Not Vegan), Prepackaged', base_name='Patty or Cake with Wheat and Soy (Not Vegan), Prepackaged', needs_translation=0 WHERE food_id=23430 AND source='France_Ciqual';
UPDATE foods SET name='Patty or Cake with Soy and Cheese, Prepackaged', base_name='Patty or Cake with Soy and Cheese, Prepackaged', needs_translation=0 WHERE food_id=23431 AND source='France_Ciqual';
UPDATE foods SET name='Patty or Cake with Soy and Vegetables, Prepackaged', base_name='Patty or Cake with Soy and Vegetables, Prepackaged', needs_translation=0 WHERE food_id=23432 AND source='France_Ciqual';
UPDATE foods SET name='Patty or Cake with Soy, Cheese and Vegetables, Prepackaged', base_name='Patty or Cake with Soy, Cheese and Vegetables, Prepackaged', needs_translation=0 WHERE food_id=23433 AND source='France_Ciqual';
UPDATE foods SET name='Plant-Based Ground Product, Soy-Based, Prepackaged', base_name='Plant-Based Ground Product, Soy-Based, Prepackaged', needs_translation=0 WHERE food_id=23434 AND source='France_Ciqual';
UPDATE foods SET name='Cheese Pizza or Margherita Pizza, Prepackaged', base_name='Cheese Pizza or Margherita Pizza, Prepackaged', needs_translation=0 WHERE food_id=23435 AND source='France_Ciqual';
UPDATE foods SET name='Quiche Lorraine, Prepackaged', base_name='Quiche Lorraine, Prepackaged', needs_translation=0 WHERE food_id=23436 AND source='France_Ciqual';
UPDATE foods SET name='Crepe or Galette Filled with Bechamel and Ham, Prepackaged', base_name='Crepe or Galette Filled with Bechamel and Ham, Prepackaged', needs_translation=0 WHERE food_id=23437 AND source='France_Ciqual';
UPDATE foods SET name='Crepe or Galette Filled with Bechamel, Ham and Cheese, Prepackaged', base_name='Crepe or Galette Filled with Bechamel, Ham and Cheese, Prepackaged', needs_translation=0 WHERE food_id=23438 AND source='France_Ciqual';
UPDATE foods SET name='Crepe or Galette Filled with Bechamel and Mushroom, Prepackaged', base_name='Crepe or Galette Filled with Bechamel and Mushroom, Prepackaged', needs_translation=0 WHERE food_id=23439 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Tart, Prepackaged', base_name='Vegetable Tart, Prepackaged', needs_translation=0 WHERE food_id=23440 AND source='France_Ciqual';
UPDATE foods SET name='Ham and Cheese Pizza, Prepackaged', base_name='Ham and Cheese Pizza, Prepackaged', needs_translation=0 WHERE food_id=23441 AND source='France_Ciqual';
UPDATE foods SET name='Cheese Tart, Prepackaged', base_name='Cheese Tart, Prepackaged', needs_translation=0 WHERE food_id=23442 AND source='France_Ciqual';
UPDATE foods SET name='Provencal-Style Tart, Prepackaged', base_name='Provencal-Style Tart, Prepackaged', needs_translation=0 WHERE food_id=23443 AND source='France_Ciqual';
UPDATE foods SET name='Meat Pizza, Bolognese Type, Prepackaged', base_name='Meat Pizza, Bolognese Type, Prepackaged', needs_translation=0 WHERE food_id=23444 AND source='France_Ciqual';
UPDATE foods SET name='Burritos', base_name='Burritos', needs_translation=0 WHERE food_id=23445 AND source='France_Ciqual';
UPDATE foods SET name='Fajitas', base_name='Fajitas', needs_translation=0 WHERE food_id=23446 AND source='France_Ciqual';
UPDATE foods SET name='Seafood Pizza, Prepackaged', base_name='Seafood Pizza, Prepackaged', needs_translation=0 WHERE food_id=23448 AND source='France_Ciqual';
UPDATE foods SET name='Salmon Pizza, Prepackaged', base_name='Salmon Pizza, Prepackaged', needs_translation=0 WHERE food_id=23449 AND source='France_Ciqual';
UPDATE foods SET name='Goat Cheese and Bacon Pizza, Prepackaged', base_name='Goat Cheese and Bacon Pizza, Prepackaged', needs_translation=0 WHERE food_id=23450 AND source='France_Ciqual';
UPDATE foods SET name='Vegetable Pizza or Four Seasons Pizza, Prepackaged', base_name='Vegetable Pizza or Four Seasons Pizza, Prepackaged', needs_translation=0 WHERE food_id=23451 AND source='France_Ciqual';
UPDATE foods SET name='Mushroom and Cheese Pizza, Prepackaged', base_name='Mushroom and Cheese Pizza, Prepackaged', needs_translation=0 WHERE food_id=23452 AND source='France_Ciqual';
UPDATE foods SET name='Four Cheese Pizza, Prepackaged', base_name='Four Cheese Pizza, Prepackaged', needs_translation=0 WHERE food_id=23453 AND source='France_Ciqual';
UPDATE foods SET name='Pizza (Average)', base_name='Pizza (Average)', needs_translation=0 WHERE food_id=23454 AND source='France_Ciqual';
UPDATE foods SET name='Pissaladiere (Provencal Onion Tart), Prepackaged', base_name='Pissaladiere (Provencal Onion Tart), Prepackaged', needs_translation=0 WHERE food_id=23455 AND source='France_Ciqual';
UPDATE foods SET name='Onion Tart, Prepackaged', base_name='Onion Tart, Prepackaged', needs_translation=0 WHERE food_id=23456 AND source='France_Ciqual';
UPDATE foods SET name='Ham, Cheese and Mushroom Pizza or Pizza Royale/Regina, Prepackaged', base_name='Ham, Cheese and Mushroom Pizza or Pizza Royale/Regina, Prepackaged', needs_translation=0 WHERE food_id=23457 AND source='France_Ciqual';
UPDATE foods SET name='Crepe or Galette Filled with Bechamel and Cheese, Prepackaged', base_name='Crepe or Galette Filled with Bechamel and Cheese, Prepackaged', needs_translation=0 WHERE food_id=23458 AND source='France_Ciqual';
UPDATE foods SET name='Flammenkueche or Flambeed Tart with Bacon, Prepackaged', base_name='Flammenkueche or Flambeed Tart with Bacon, Prepackaged', needs_translation=0 WHERE food_id=23459 AND source='France_Ciqual';
UPDATE foods SET name='Crepe or Galette Filled with Bechamel, Ham, Cheese and Mushroom, Prepackaged', base_name='Crepe or Galette Filled with Bechamel, Ham, Cheese and Mushroom, Prepackaged', needs_translation=0 WHERE food_id=23460 AND source='France_Ciqual';
UPDATE foods SET name='Leek Tart or Pie, Prepackaged', base_name='Leek Tart or Pie, Prepackaged', needs_translation=0 WHERE food_id=23461 AND source='France_Ciqual';
UPDATE foods SET name='Salmon Tart, Prepackaged', base_name='Salmon Tart, Prepackaged', needs_translation=0 WHERE food_id=23462 AND source='France_Ciqual';
UPDATE foods SET name='Riesling Pie (Tourte au Riesling), Prepackaged', base_name='Riesling Pie (Tourte au Riesling), Prepackaged', needs_translation=0 WHERE food_id=23463 AND source='France_Ciqual';
UPDATE foods SET name='Tomato Tart, Prepackaged', base_name='Tomato Tart, Prepackaged', needs_translation=0 WHERE food_id=23464 AND source='France_Ciqual';
UPDATE foods SET name='Crepe or Galette Complete (Egg, Ham, Cheese), Prepackaged', base_name='Crepe or Galette Complete (Egg, Ham, Cheese), Prepackaged', needs_translation=0 WHERE food_id=23465 AND source='France_Ciqual';
UPDATE foods SET name='Scallop Tart, Prepackaged', base_name='Scallop Tart, Prepackaged', needs_translation=0 WHERE food_id=23466 AND source='France_Ciqual';
UPDATE foods SET name='Chicken Pastilla, Prepackaged', base_name='Chicken Pastilla, Prepackaged', needs_translation=0 WHERE food_id=23467 AND source='France_Ciqual';
UPDATE foods SET name='Bacon, Onion and Cheese Pizza, Prepackaged', base_name='Bacon, Onion and Cheese Pizza, Prepackaged', needs_translation=0 WHERE food_id=23468 AND source='France_Ciqual';
UPDATE foods SET name='Crepe or Galette with Scallops, Prepackaged', base_name='Crepe or Galette with Scallops, Prepackaged', needs_translation=0 WHERE food_id=23469 AND source='France_Ciqual';
UPDATE foods SET name='Savory Tart or Quiche (Average)', base_name='Savory Tart or Quiche (Average)', needs_translation=0 WHERE food_id=23470 AND source='France_Ciqual';
UPDATE foods SET name='Crepe or Galette Filled with Bechamel and Mushroom, Cooked, Prepackaged', base_name='Crepe or Galette Filled with Bechamel and Mushroom, Cooked, Prepackaged', needs_translation=0 WHERE food_id=23471 AND source='France_Ciqual';
UPDATE foods SET name='Maroilles Cheese Tart or Flamiche, Prepackaged', base_name='Maroilles Cheese Tart or Flamiche, Prepackaged', needs_translation=0 WHERE food_id=23472 AND source='France_Ciqual';
UPDATE foods SET name='Crepe or Galette Filled with Fish and/or Seafood, Prepackaged', base_name='Crepe or Galette Filled with Fish and/or Seafood, Prepackaged', needs_translation=0 WHERE food_id=23473 AND source='France_Ciqual';
UPDATE foods SET name='Ficelle Picarde (Ham and Mushroom Crepe), Prepackaged', base_name='Ficelle Picarde (Ham and Mushroom Crepe), Prepackaged', needs_translation=0 WHERE food_id=23474 AND source='France_Ciqual';
UPDATE foods SET name='Spinach and Goat Cheese Tart, Prepackaged', base_name='Spinach and Goat Cheese Tart, Prepackaged', needs_translation=0 WHERE food_id=23475 AND source='France_Ciqual';
UPDATE foods SET name='Tielle Setoise (Octopus and Tomato Pie), Prepackaged', base_name='Tielle Setoise (Octopus and Tomato Pie), Prepackaged', needs_translation=0 WHERE food_id=23476 AND source='France_Ciqual';
UPDATE foods SET name='Tuna Pizza, Prepackaged', base_name='Tuna Pizza, Prepackaged', needs_translation=0 WHERE food_id=23477 AND source='France_Ciqual';
UPDATE foods SET name='Kebab Pizza, Prepackaged', base_name='Kebab Pizza, Prepackaged', needs_translation=0 WHERE food_id=23478 AND source='France_Ciqual';
UPDATE foods SET name='Chicken Pizza, Prepackaged', base_name='Chicken Pizza, Prepackaged', needs_translation=0 WHERE food_id=23479 AND source='France_Ciqual';
UPDATE foods SET name='Raclette or Tartiflette-Style Pizza, Prepackaged', base_name='Raclette or Tartiflette-Style Pizza, Prepackaged', needs_translation=0 WHERE food_id=23480 AND source='France_Ciqual';
UPDATE foods SET name='Speck or Cured Ham Pizza, Prepackaged', base_name='Speck or Cured Ham Pizza, Prepackaged', needs_translation=0 WHERE food_id=23481 AND source='France_Ciqual';
UPDATE foods SET name='Focaccia, Topped', base_name='Focaccia, Topped', needs_translation=0 WHERE food_id=23482 AND source='France_Ciqual';
UPDATE foods SET name='Fougasse, Topped', base_name='Fougasse, Topped', needs_translation=0 WHERE food_id=23483 AND source='France_Ciqual';
UPDATE foods SET name='Croque-Monsieur, Homemade', base_name='Croque-Monsieur, Homemade', needs_translation=0 WHERE food_id=23484 AND source='France_Ciqual';
UPDATE foods SET name='Hot Dog, Prepackaged', base_name='Hot Dog, Prepackaged', needs_translation=0 WHERE food_id=23485 AND source='France_Ciqual';
UPDATE foods SET name='Greek Sandwich or Kebab, Pita, Raw Vegetables', base_name='Greek Sandwich or Kebab, Pita, Raw Vegetables', needs_translation=0 WHERE food_id=23490 AND source='France_Ciqual';
UPDATE foods SET name='Greek Sandwich or Kebab, Baguette, Raw Vegetables', base_name='Greek Sandwich or Kebab, Baguette, Raw Vegetables', needs_translation=0 WHERE food_id=23491 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Tuna, Raw Vegetables (Tomato, Lettuce), Mayonnaise', base_name='Baguette Sandwich, Tuna, Raw Vegetables (Tomato, Lettuce), Mayonnaise', needs_translation=0 WHERE food_id=23492 AND source='France_Ciqual';
UPDATE foods SET name='Panini Sandwich, Cured Ham, Mozzarella, Tomatoes', base_name='Panini Sandwich, Cured Ham, Mozzarella, Tomatoes', needs_translation=0 WHERE food_id=23493 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Ham, Hard-Boiled Egg, Raw Vegetables (Tomato, Lettuce), Butter', base_name='Baguette Sandwich, Ham, Hard-Boiled Egg, Raw Vegetables (Tomato, Lettuce), Butter', needs_translation=0 WHERE food_id=23494 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Chicken, Raw Vegetables (Tomato, Lettuce), Mayonnaise', base_name='Baguette Sandwich, Chicken, Raw Vegetables (Tomato, Lettuce), Mayonnaise', needs_translation=0 WHERE food_id=23495 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Ham and Emmental, Prepackaged', base_name='Baguette Sandwich, Ham and Emmental, Prepackaged', needs_translation=0 WHERE food_id=23496 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Smoked Salmon, Butter', base_name='Baguette Sandwich, Smoked Salmon, Butter', needs_translation=0 WHERE food_id=23497 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Tuna, Corn, Raw Vegetables, Prepackaged', base_name='Baguette Sandwich, Tuna, Corn, Raw Vegetables, Prepackaged', needs_translation=0 WHERE food_id=23498 AND source='France_Ciqual';
UPDATE foods SET name='Chicken Burger', base_name='Chicken Burger', needs_translation=0 WHERE food_id=23499 AND source='France_Ciqual';
UPDATE foods SET name='Pan Bagnat', base_name='Pan Bagnat', needs_translation=0 WHERE food_id=23500 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Ham, Butter', base_name='Baguette Sandwich, Ham, Butter', needs_translation=0 WHERE food_id=23501 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Camembert, Butter', base_name='Baguette Sandwich, Camembert, Butter', needs_translation=0 WHERE food_id=23502 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Dry Sausage (Saucisson), Butter', base_name='Baguette Sandwich, Dry Sausage (Saucisson), Butter', needs_translation=0 WHERE food_id=23504 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Ham, Emmental, Butter', base_name='Baguette Sandwich, Ham, Emmental, Butter', needs_translation=0 WHERE food_id=23505 AND source='France_Ciqual';
UPDATE foods SET name='Sandwich (Average)', base_name='Sandwich (Average)', needs_translation=0 WHERE food_id=23506 AND source='France_Ciqual';
UPDATE foods SET name='Toasts or Savory Canapes, Various Toppings, Prepackaged', base_name='Toasts or Savory Canapes, Various Toppings, Prepackaged', needs_translation=0 WHERE food_id=23507 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Assorted Raw Vegetables, Mayonnaise', base_name='Baguette Sandwich, Assorted Raw Vegetables, Mayonnaise', needs_translation=0 WHERE food_id=23508 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Turkey, Raw Vegetables (Tomato, Lettuce), Mayonnaise', base_name='Baguette Sandwich, Turkey, Raw Vegetables (Tomato, Lettuce), Mayonnaise', needs_translation=0 WHERE food_id=23509 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Egg, Raw Vegetables (Tomato, Lettuce), Mayonnaise', base_name='Baguette Sandwich, Egg, Raw Vegetables (Tomato, Lettuce), Mayonnaise', needs_translation=0 WHERE food_id=23510 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Pork, Raw Vegetables (Tomato, Lettuce), Mayonnaise', base_name='Baguette Sandwich, Pork, Raw Vegetables (Tomato, Lettuce), Mayonnaise', needs_translation=0 WHERE food_id=23511 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich, Merguez Sausage, Ketchup and Mustard', base_name='Baguette Sandwich, Merguez Sausage, Ketchup and Mustard', needs_translation=0 WHERE food_id=23512 AND source='France_Ciqual';
UPDATE foods SET name='Croque-Madame', base_name='Croque-Madame', needs_translation=0 WHERE food_id=23514 AND source='France_Ciqual';
UPDATE foods SET name='Baguette Sandwich (Average)', base_name='Baguette Sandwich (Average)', needs_translation=0 WHERE food_id=23515 AND source='France_Ciqual';
UPDATE foods SET name='Sandwich Bread Sandwich, Various Fillings, Prepackaged', base_name='Sandwich Bread Sandwich, Various Fillings, Prepackaged', needs_translation=0 WHERE food_id=23516 AND source='France_Ciqual';
UPDATE foods SET name='Croque-Monsieur, Prepackaged', base_name='Croque-Monsieur, Prepackaged', needs_translation=0 WHERE food_id=23517 AND source='France_Ciqual';
UPDATE foods SET name='Whole Wheat Sandwich Bread, Ham, Raw Vegetables, Optional Cheese, Prepackaged', base_name='Whole Wheat Sandwich Bread, Ham, Raw Vegetables, Optional Cheese, Prepackaged', needs_translation=0 WHERE food_id=23518 AND source='France_Ciqual';
UPDATE foods SET name='Whole Wheat Sandwich Bread, Tuna, Raw Vegetables, Mayonnaise, Prepackaged', base_name='Whole Wheat Sandwich Bread, Tuna, Raw Vegetables, Mayonnaise, Prepackaged', needs_translation=0 WHERE food_id=23519 AND source='France_Ciqual';
UPDATE foods SET name='Whole Wheat Sandwich Bread, Ham, Cheese, Prepackaged', base_name='Whole Wheat Sandwich Bread, Ham, Cheese, Prepackaged', needs_translation=0 WHERE food_id=23520 AND source='France_Ciqual';
UPDATE foods SET name='Whole Wheat Sandwich Bread, Chicken, Raw Vegetables, Mayonnaise, Prepackaged', base_name='Whole Wheat Sandwich Bread, Chicken, Raw Vegetables, Mayonnaise, Prepackaged', needs_translation=0 WHERE food_id=23521 AND source='France_Ciqual';
UPDATE foods SET name='Samosa, Prepackaged, Cooked', base_name='Samosa, Prepackaged, Cooked', needs_translation=0 WHERE food_id=23523 AND source='France_Ciqual';
UPDATE foods SET name='Fish and/or Seafood Puff Pastry', base_name='Fish and/or Seafood Puff Pastry', needs_translation=0 WHERE food_id=23524 AND source='France_Ciqual';
UPDATE foods SET name='Chinese Specialty, Steamed Dumpling Type, Prepackaged, Cooked', base_name='Chinese Specialty, Steamed Dumpling Type, Prepackaged, Cooked', needs_translation=0 WHERE food_id=23525 AND source='France_Ciqual';
UPDATE foods SET name='Snail Puff Pastry, Prepackaged', base_name='Snail Puff Pastry, Prepackaged', needs_translation=0 WHERE food_id=23526 AND source='France_Ciqual';
UPDATE foods SET name='Cheese Puff Pastry or Friand', base_name='Cheese Puff Pastry or Friand', needs_translation=0 WHERE food_id=23527 AND source='France_Ciqual';
UPDATE foods SET name='Meat Puff Pastry or Friand, Prepackaged', base_name='Meat Puff Pastry or Friand, Prepackaged', needs_translation=0 WHERE food_id=23528 AND source='France_Ciqual';
UPDATE foods SET name='Vol-au-Vent (Bouchee a la Reine), with Meat/Poultry/Quenelle', base_name='Vol-au-Vent (Bouchee a la Reine), with Meat/Poultry/Quenelle', needs_translation=0 WHERE food_id=23529 AND source='France_Ciqual';
UPDATE foods SET name='Croissant with Ham', base_name='Croissant with Ham', needs_translation=0 WHERE food_id=23530 AND source='France_Ciqual';
UPDATE foods SET name='Spring Roll', base_name='Spring Roll', needs_translation=0 WHERE food_id=23531 AND source='France_Ciqual';
UPDATE foods SET name='Filled Brick Pastry (Filling: Shrimp, Vegetables, Poultry, Meat, Fish, etc.), Homemade, Cooked', base_name='Filled Brick Pastry (Filling: Shrimp, Vegetables, Poultry, Meat, Fish, etc.), Homemade, Cooked', needs_translation=0 WHERE food_id=23533 AND source='France_Ciqual';
UPDATE foods SET name='Vol-au-Vent (Bouchee a la Reine), with Fish and Seafood', base_name='Vol-au-Vent (Bouchee a la Reine), with Fish and Seafood', needs_translation=0 WHERE food_id=23534 AND source='France_Ciqual';
UPDATE foods SET name='Ham and Cheese Puff Pastry or Friand', base_name='Ham and Cheese Puff Pastry or Friand', needs_translation=0 WHERE food_id=23535 AND source='France_Ciqual';
UPDATE foods SET name='Meat, Poultry, or Fish Fritter, Homemade, Raw', base_name='Meat, Poultry, or Fish Fritter, Homemade, Raw', needs_translation=0 WHERE food_id=23536 AND source='France_Ciqual';
UPDATE foods SET name='Egg Brick Pastry, Homemade, Cooked', base_name='Egg Brick Pastry, Homemade, Cooked', needs_translation=0 WHERE food_id=23537 AND source='France_Ciqual';
UPDATE foods SET name='Beef Brick Pastry', base_name='Beef Brick Pastry', needs_translation=0 WHERE food_id=23538 AND source='France_Ciqual';
UPDATE foods SET name='Potato Brick Pastry, Homemade, Cooked', base_name='Potato Brick Pastry, Homemade, Cooked', needs_translation=0 WHERE food_id=23539 AND source='France_Ciqual';
UPDATE foods SET name='Savory Puff Pastry (Average)', base_name='Savory Puff Pastry (Average)', needs_translation=0 WHERE food_id=23540 AND source='France_Ciqual';
UPDATE foods SET name='Vol-au-Vent (Bouchee a la Reine), Filled (Average)', base_name='Vol-au-Vent (Bouchee a la Reine), Filled (Average)', needs_translation=0 WHERE food_id=23541 AND source='France_Ciqual';
UPDATE foods SET name='Croissant with Ham and Cheese, Prepackaged', base_name='Croissant with Ham and Cheese, Prepackaged', needs_translation=0 WHERE food_id=23545 AND source='France_Ciqual';
UPDATE foods SET name='Celeriac Remoulade, Prepackaged', base_name='Celeriac Remoulade, Prepackaged', needs_translation=0 WHERE food_id=26214 AND source='France_Ciqual';
UPDATE foods SET name='Sports Drink, Dietetic', base_name='Sports Drink, Dietetic', needs_translation=0 WHERE food_id=26323 AND source='France_Ciqual';
UPDATE foods SET name='Low-Calorie Meal Replacement, Dessert Cream', base_name='Low-Calorie Meal Replacement, Dessert Cream', needs_translation=0 WHERE food_id=26324 AND source='France_Ciqual';
UPDATE foods SET name='Low-Calorie Meal Replacement, Ready to Drink', base_name='Low-Calorie Meal Replacement, Ready to Drink', needs_translation=0 WHERE food_id=26325 AND source='France_Ciqual';
UPDATE foods SET name='Low-Calorie Meal Replacement, Powder Reconstituted with Skimmed Milk', base_name='Low-Calorie Meal Replacement, Powder Reconstituted with Skimmed Milk', needs_translation=0 WHERE food_id=26326 AND source='France_Ciqual';
UPDATE foods SET name='Low-Calorie Meal Replacement, Powder Reconstituted with Skimmed Milk, Milkshake Type', base_name='Low-Calorie Meal Replacement, Powder Reconstituted with Skimmed Milk, Milkshake Type', needs_translation=0 WHERE food_id=26327 AND source='France_Ciqual';
UPDATE foods SET name='Syrup for Canned Fruit in Syrup', base_name='Syrup for Canned Fruit in Syrup', needs_translation=0 WHERE food_id=26343 AND source='France_Ciqual';
UPDATE foods SET name='Light Syrup for Canned Fruit in Syrup', base_name='Light Syrup for Canned Fruit in Syrup', needs_translation=0 WHERE food_id=26344 AND source='France_Ciqual';
UPDATE foods SET name='Pineapple Juice for Canned Pineapple in Juice', base_name='Pineapple Juice for Canned Pineapple in Juice', needs_translation=0 WHERE food_id=26345 AND source='France_Ciqual';
UPDATE foods SET name='Light Syrup for Canned Pear', base_name='Light Syrup for Canned Pear', needs_translation=0 WHERE food_id=26346 AND source='France_Ciqual';
UPDATE foods SET name='Royal Jelly', base_name='Royal Jelly', needs_translation=0 WHERE food_id=26348 AND source='France_Ciqual';
UPDATE foods SET name='Pollen, Partially Dried', base_name='Pollen, Partially Dried', needs_translation=0 WHERE food_id=26349 AND source='France_Ciqual';
UPDATE foods SET name='Pollen, Fresh', base_name='Pollen, Fresh', needs_translation=0 WHERE food_id=26350 AND source='France_Ciqual';

COMMIT;
