// "Recipes" -- a real, new Digest category, 2026-08-14, direct request:
// "These meals should all be available as pre-made choices already
// available to be used in the app, and are automatically available to them
// from the Digest area, where a new category of Recipes for different
// kinds of meals will be available." One real DigestEntry per row in the
// bundled curated_recipes table (see scripts/add_curated_recipes_batch2.py
// and scripts/add_fermentation_strains.py for the real reference-database
// content this reuses) -- 44 total, spanning all 10 direct-ingredient Food
// builders (Salad and Smoothie already had 6 each from an earlier
// 2026-08-09 pass; Side, Fermentation, Beverage, Snack, Baked Goods, Soup,
// Sauces, and Handhelds each got 4 new ones the same day this file was
// built).
//
// Deliberately NOT a citation-backed research entry like the rest of this
// Digest -- `citations: []`/`overallTier: 'strong'` throughout, matching
// the precedent already established for appHelps.ts (this app's own
// features, described directly, not an external research claim). Every
// title/teaser/summary below is reused VERBATIM from that same recipe's own
// real `name`/`flavor_profile`/`health_benefit` fields, not written fresh
// for this file, so the Digest entry and the builder's own "Or Start From a
// Recipe" card always describe the exact same thing.
//
// `linkedCuratedRecipeId`/`linkedBuilderType` (see types.ts's own comment)
// are what let PurpleDigestScreen's DigestCard render a real "Build This
// Recipe" button, navigating straight into the matching builder with that
// recipe already loaded (app/(tabs)/food.tsx's own openXRecipeId params,
// one per builder).
import type { DigestEntry } from './types';

export const RECIPES_ENTRIES: DigestEntry[] = [
  {
    id: 'recipe-baked-whole-wheat-bread',
    category: 'recipes',
    title: 'Simple Whole Wheat Bread',
    teaser: 'A dense, honest homemade loaf, crust and all.',
    summary: 'Whole-grain flour keeps fiber intact that white flour strips out during milling, worth knowing before reaching for a store loaf.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_baked_whole_wheat_bread',
    linkedBuilderType: 'bakedGoods',
  },
  {
    id: 'recipe-baked-wheat-tortillas',
    category: 'recipes',
    title: 'Homemade Wheat Tortillas',
    teaser: 'Soft and made from scratch instead of a packaged stack.',
    summary: 'No preservatives or dough conditioners: just flour, fat, water, and salt, the same ingredients a homemade tortilla has always needed.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_baked_wheat_tortillas',
    linkedBuilderType: 'bakedGoods',
  },
  {
    id: 'recipe-baked-buttermilk-biscuits',
    category: 'recipes',
    title: 'Whole Wheat Buttermilk Biscuits',
    teaser: 'Flaky and tangy from buttermilk, a from-scratch take on a familiar comfort food.',
    summary: 'Whole wheat flour in place of white flour adds fiber to an otherwise-familiar biscuit.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_baked_buttermilk_biscuits',
    linkedBuilderType: 'bakedGoods',
  },
  {
    id: 'recipe-baked-banana-oat-cookies',
    category: 'recipes',
    title: 'Banana Oat Breakfast Cookies',
    teaser: 'Naturally sweet from banana, a healthier stand-in for a dessert cookie.',
    summary: 'No added refined sugar. Ripe banana and a small amount of honey do the sweetening, with flaxseed fiber and omega-3s folded in.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_baked_banana_oat_cookies',
    linkedBuilderType: 'bakedGoods',
  },
  {
    id: 'recipe-bev-ginger-turmeric-tonic',
    category: 'recipes',
    title: 'Ginger Turmeric Immunity Tonic',
    teaser: 'Warming, spicy, and citrusy.',
    summary: "A curcumin-and-piperine pairing already documented in this app's own Nutrient Interactions research: black pepper measurably improves how well turmeric's own curcumin actually absorbs.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_bev_ginger_turmeric_tonic',
    linkedBuilderType: 'beverage',
  },
  {
    id: 'recipe-bev-electrolyte-water',
    category: 'recipes',
    title: 'Electrolyte Recovery Water',
    teaser: 'Light, a little salty-sweet, and citrusy.',
    summary: 'A simple homemade alternative to a commercial sports drink, with sodium and potassium-rich citrus, no artificial dye or flavoring.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_bev_electrolyte_water',
    linkedBuilderType: 'beverage',
  },
  {
    id: 'recipe-bev-iced-green-tea-mint',
    category: 'recipes',
    title: 'Iced Green Tea with Mint',
    teaser: 'Light, herbal, and refreshing.',
    summary: 'A plain brewed tea, no added sugar unless you choose to add it yourself.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_bev_iced_green_tea_mint',
    linkedBuilderType: 'beverage',
  },
  {
    id: 'recipe-bev-golden-milk',
    category: 'recipes',
    title: 'Golden Milk (Turmeric Latte)',
    teaser: 'Warm, spiced, and creamy.',
    summary: 'The same curcumin-and-black-pepper pairing as the Ginger Turmeric Tonic above, in a warm, milk-based drink instead.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_bev_golden_milk',
    linkedBuilderType: 'beverage',
  },
  {
    id: 'recipe-ferment-plain-yogurt',
    category: 'recipes',
    title: 'Homemade Plain Yogurt',
    teaser: 'Tangy and thick, the classic homemade yogurt.',
    summary: 'Made with the same two starter cultures Codex Alimentarius requires for anything legally labeled yogurt: S. thermophilus and L. bulgaricus.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_ferment_plain_yogurt',
    linkedBuilderType: 'fermentation',
  },
  {
    id: 'recipe-ferment-probiotic-yogurt',
    category: 'recipes',
    title: 'Probiotic-Boosted Yogurt',
    teaser: 'The same base yogurt, built with a broader culture blend.',
    summary: 'Adds L. acidophilus and Bifidobacterium species alongside the required yogurt starter pair, for a broader culture blend than a plain store yogurt typically carries.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_ferment_probiotic_yogurt',
    linkedBuilderType: 'fermentation',
  },
  {
    id: 'recipe-ferment-sauerkraut',
    category: 'recipes',
    title: 'Classic Sauerkraut',
    teaser: 'Tangy and crunchy, a two-ingredient ferment.',
    summary: 'Fermentation, not vinegar-pickling: Leuconostoc mesenteroides kicks off the process, with Lactobacillus plantarum taking over as it sours.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_ferment_sauerkraut',
    linkedBuilderType: 'fermentation',
  },
  {
    id: 'recipe-ferment-kombucha',
    category: 'recipes',
    title: 'Home-Brewed Kombucha',
    teaser: 'Tangy, lightly fizzy, a fermented tea.',
    summary: "A live SCOBY does the actual fermenting here (not one of this app's own catalogued single strains, deliberately left unlinked rather than guessed at). Start with brewed tea and sugar.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_ferment_kombucha',
    linkedBuilderType: 'fermentation',
  },
  {
    id: 'recipe-handheld-turkey-avocado-wrap',
    category: 'recipes',
    title: 'Turkey & Avocado Wrap',
    teaser: 'Fresh, light, and filling.',
    summary: "Lean turkey and avocado's own healthy fat, in a whole-wheat wrap rather than a processed deli-counter build.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_handheld_turkey_avocado_wrap',
    linkedBuilderType: 'handheld',
  },
  {
    id: 'recipe-handheld-grilled-chicken-sandwich',
    category: 'recipes',
    title: 'Grilled Chicken Sandwich',
    teaser: 'Simple and filling.',
    summary: 'Grilled chicken breast on whole-grain bread, rather than a fried, breaded fast-food version.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_handheld_grilled_chicken_sandwich',
    linkedBuilderType: 'handheld',
  },
  {
    id: 'recipe-handheld-black-bean-sweet-potato-tacos',
    category: 'recipes',
    title: 'Black Bean & Sweet Potato Tacos',
    teaser: 'Warm, a little sweet, and satisfying.',
    summary: 'A plant-forward taco with legume protein and fiber from the black beans, and beta-carotene from the sweet potato.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_handheld_black_bean_sweet_potato_tacos',
    linkedBuilderType: 'handheld',
  },
  {
    id: 'recipe-handheld-egg-salad-lettuce-wraps',
    category: 'recipes',
    title: 'Egg Salad Lettuce Wraps',
    teaser: 'Creamy, savory, and lighter than a bread-based sandwich.',
    summary: 'The same egg salad, in a lettuce wrap instead of bread, for anyone watching refined-carbohydrate intake.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_handheld_egg_salad_lettuce_wraps',
    linkedBuilderType: 'handheld',
  },
  {
    id: 'recipe-salad-mediterranean-chickpea-feta',
    category: 'recipes',
    title: 'Mediterranean Chickpea & Feta',
    teaser: 'Bright, briny, and herby: chickpeas and feta against a lemony olive oil dressing.',
    summary: "A Mediterranean-pattern combination (legumes, olive oil, a vegetable-forward base) that this app's own Cardiovascular Disease research repeatedly finds linked to better heart-health outcomes.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_salad_mediterranean_chickpea_feta',
    linkedBuilderType: 'salad',
  },
  {
    id: 'recipe-salad-kale-citrus-iron',
    category: 'recipes',
    title: 'Kale & Citrus Iron Boost',
    teaser: 'Earthy kale brightened with citrus and a nutty crunch.',
    summary: "Pairs a nonheme-iron source (kale) with a vitamin C source (orange) in the same bite. This app's own Iron research names this exact pairing as a useful way to improve how much of that iron the body actually absorbs.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_salad_kale_citrus_iron',
    linkedBuilderType: 'salad',
  },
  {
    id: 'recipe-salad-sesame-ginger-slaw',
    category: 'recipes',
    title: 'Sesame Ginger Cabbage & Carrot Slaw',
    teaser: 'Crisp, tangy, and a little sweet: a quick raw-vegetable slaw.',
    summary: "A raw cruciferous vegetable (cabbage) alongside fresh ginger. This app's own Problem Foods research covers the goitrogen consideration for raw cruciferous vegetables directly, worth a read if this becomes a regular dish.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_salad_sesame_ginger_slaw',
    linkedBuilderType: 'salad',
  },
  {
    id: 'recipe-salad-beet-walnut-arugula',
    category: 'recipes',
    title: 'Roasted Beet, Walnut & Arugula',
    teaser: 'Sweet roasted beet, peppery arugula, and a crunch from walnut.',
    summary: "Beets carry dietary nitrate, linked in this app's own Cardiovascular Disease research to a measurable blood-pressure benefit, alongside walnut's own unusually high plant-based omega-3 content among common nuts.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_salad_beet_walnut_arugula',
    linkedBuilderType: 'salad',
  },
  {
    id: 'recipe-salad-southwest-quinoa-black-bean',
    category: 'recipes',
    title: 'Southwest Quinoa & Black Bean',
    teaser: 'Hearty, smoky-sweet, and citrus-bright: a complete-protein base.',
    summary: "Quinoa and black beans together form a complementary-protein pairing, each supplying amino acids the other is relatively lower in. This app's own Avocado profile names a serving-size-dependent FODMAP note worth knowing if avocado tends to bother you.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_salad_southwest_quinoa_black_bean',
    linkedBuilderType: 'salad',
  },
  {
    id: 'recipe-salad-spinach-strawberry-almond',
    category: 'recipes',
    title: 'Spinach, Strawberry & Almond',
    teaser: 'Sweet strawberry against fresh spinach, with a crunch from almonds.',
    summary: "The same vitamin C/iron pairing as the Kale & Citrus salad, built from a different combination: strawberry's own vitamin C alongside spinach's own iron content.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_salad_spinach_strawberry_almond',
    linkedBuilderType: 'salad',
  },
  {
    id: 'recipe-sauce-basic-tomato',
    category: 'recipes',
    title: 'Basic Tomato Sauce',
    teaser: 'Rich, garlicky, cooked-down tomato flavor.',
    summary: 'Built from whole tomatoes rather than a jarred sauce with added sugar or preservatives.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_sauce_basic_tomato',
    linkedBuilderType: 'sauce',
  },
  {
    id: 'recipe-sauce-garlic-herb-vinaigrette',
    category: 'recipes',
    title: 'Garlic Herb Vinaigrette',
    teaser: 'Tangy, garlicky, an everyday salad dressing.',
    summary: 'Olive oil and vinegar, no added sugar or stabilizers a bottled dressing typically carries.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_sauce_garlic_herb_vinaigrette',
    linkedBuilderType: 'sauce',
  },
  {
    id: 'recipe-sauce-simple-pesto',
    category: 'recipes',
    title: 'Simple Pesto',
    teaser: 'Herbal, nutty, and garlicky.',
    summary: 'Basil, pine nuts, and olive oil: a made-from-scratch pesto without the added oils and preservatives a jarred pesto usually carries.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_sauce_simple_pesto',
    linkedBuilderType: 'sauce',
  },
  {
    id: 'recipe-sauce-tahini-lemon',
    category: 'recipes',
    title: 'Tahini Lemon Sauce',
    teaser: 'Creamy, nutty, and bright with lemon.',
    summary: 'A whole-sesame sauce with plant protein and healthy fat, versatile over roasted vegetables, a grain bowl, or a wrap.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_sauce_tahini_lemon',
    linkedBuilderType: 'sauce',
  },
  {
    id: 'recipe-side-herb-roasted-potatoes',
    category: 'recipes',
    title: 'Herb-Roasted Breakfast Potatoes',
    teaser: 'Crispy on the outside, tender inside, finished with rosemary and garlic.',
    summary: 'A whole-food breakfast side: potato retains potassium and vitamin C, especially with the skin left on, unlike a processed hash-brown patty.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_side_herb_roasted_potatoes',
    linkedBuilderType: 'side',
  },
  {
    id: 'recipe-side-lemon-garlic-broccoli',
    category: 'recipes',
    title: 'Lemon Garlic Roasted Broccoli',
    teaser: 'Bright, garlicky, with a little char at the edges from roasting.',
    summary: 'Cruciferous fiber and vitamin C, roasted rather than boiled so more of both stay in the food instead of the cooking water.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_side_lemon_garlic_broccoli',
    linkedBuilderType: 'side',
  },
  {
    id: 'recipe-side-garlic-mashed-cauliflower',
    category: 'recipes',
    title: 'Garlic Mashed Cauliflower',
    teaser: 'Creamy and garlicky: a whole-food stand-in for mashed potatoes.',
    summary: "A way to keep dinner's own carbohydrate load lighter without giving up a creamy, mashed side dish.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_side_garlic_mashed_cauliflower',
    linkedBuilderType: 'side',
  },
  {
    id: 'recipe-side-sauteed-spinach-garlic',
    category: 'recipes',
    title: 'Simple Sautéed Spinach with Garlic',
    teaser: 'Quick, garlicky, and simple: an everyday green side.',
    summary: 'Iron- and folate-rich spinach, lightly wilted in a hot pan rather than boiled down to almost nothing.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_side_sauteed_spinach_garlic',
    linkedBuilderType: 'side',
  },
  {
    id: 'recipe-smoothie-green-glow',
    category: 'recipes',
    title: 'Green Glow',
    teaser: 'Mild, sweet, and easy to drink for a first green smoothie.',
    summary: 'A gentle way to work a leafy green into a day without it dominating the flavor: spinach carries a much lower oxalate content than a green like Swiss chard, and pineapple/banana carry enough natural sweetness to mask most of its taste.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_smoothie_green_glow',
    linkedBuilderType: 'smoothie',
  },
  {
    id: 'recipe-smoothie-golden-turmeric',
    category: 'recipes',
    title: 'Golden Turmeric Anti-Inflammatory',
    teaser: 'Warm, spiced, and golden: tastes closer to a chai latte than a green smoothie.',
    summary: "This app's own Nutrient Interactions research covers a well-documented finding: black pepper's own piperine content measurably increases how much curcumin (turmeric's own active compound) the body actually absorbs, both are deliberately paired here for that reason. Uses ground cinnamon; this app's own Choosing the Real Thing topic covers why the species on the label matters if you use cinnamon regularly.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_smoothie_golden_turmeric',
    linkedBuilderType: 'smoothie',
  },
  {
    id: 'recipe-smoothie-brazil-nut-selenium',
    category: 'recipes',
    title: 'Brazil Nut Tropical Selenium Support',
    teaser: 'Creamy, tropical, and nutty: coconut and pineapple carry Brazil nut richness.',
    summary: "A potent selenium source. This app's own Nutrients research covers selenium's own strong Hashimoto's evidence, and a worth-knowing caution goes with it: Brazil nuts carry an unusually high selenium content per nut, so 2 is a deliberate amount here, not a starting point to build up from.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_smoothie_brazil_nut_selenium',
    linkedBuilderType: 'smoothie',
  },
  {
    id: 'recipe-smoothie-berry-antioxidant',
    category: 'recipes',
    title: 'Berry Antioxidant Blast',
    teaser: 'Deep purple, tart-sweet, and filling from fiber content.',
    summary: "Blueberry's own concentrated anthocyanin content (this app's own Blueberry profile covers the research directly) alongside flaxseed's own omega-3 and lignan content: ground flaxseed is what actually makes flaxseed's nutrients accessible, exactly what blending does here.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_smoothie_berry_antioxidant',
    linkedBuilderType: 'smoothie',
  },
  {
    id: 'recipe-smoothie-iron-vitamin-c',
    category: 'recipes',
    title: 'Iron & Vitamin C Boost',
    teaser: 'Bright, sweet, and citrus-forward.',
    summary: "The same vitamin C/iron pairing this app's own Iron research names directly, built into a drinkable form: spinach's own iron alongside orange and strawberry's own vitamin C.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_smoothie_iron_vitamin_c',
    linkedBuilderType: 'smoothie',
  },
  {
    id: 'recipe-smoothie-tropical-ginger',
    category: 'recipes',
    title: 'Tropical Ginger Digestive Soother',
    teaser: 'Bright, zesty, and a little warming from fresh ginger.',
    summary: "Pineapple and ginger are both commonly used traditional digestive aids. This app's own Fermentation Methods and Gut & Microbiome research covers the deeper science behind digestive support more broadly, if this becomes a regular favorite.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_smoothie_tropical_ginger',
    linkedBuilderType: 'smoothie',
  },
  {
    id: 'recipe-snack-roasted-chickpeas',
    category: 'recipes',
    title: 'Roasted Chickpeas',
    teaser: 'Crunchy, salty, a little smoky from paprika.',
    summary: 'A whole-legume alternative to a processed chip: fiber and plant protein in the same crunchy bite.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_snack_roasted_chickpeas',
    linkedBuilderType: 'snack',
  },
  {
    id: 'recipe-snack-trail-mix',
    category: 'recipes',
    title: 'Simple Trail Mix',
    teaser: 'A no-added-sugar mix of nuts, seeds, and dried fruit.',
    summary: "Whole-food fats and protein from the nuts and seeds, with the dried fruit's own natural sugar the only sweetness here.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_snack_trail_mix',
    linkedBuilderType: 'snack',
  },
  {
    id: 'recipe-snack-apple-almond-butter',
    category: 'recipes',
    title: 'Apple Slices with Almond Butter',
    teaser: 'Sweet, tart, and creamy.',
    summary: "Whole apple fiber paired with almond butter's own protein and healthy fat, a more filling combination than fruit alone.",
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_snack_apple_almond_butter',
    linkedBuilderType: 'snack',
  },
  {
    id: 'recipe-snack-berries-yogurt',
    category: 'recipes',
    title: 'Berries with Greek Yogurt',
    teaser: 'Creamy, tangy, and naturally sweet.',
    summary: 'Protein-rich Greek yogurt paired with antioxidant-rich berries: far less added sugar than a flavored, pre-sweetened yogurt cup.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_snack_berries_yogurt',
    linkedBuilderType: 'snack',
  },
  {
    id: 'recipe-soup-chicken-vegetable',
    category: 'recipes',
    title: 'Simple Chicken Vegetable Soup',
    teaser: 'A homey, everyday soup.',
    summary: 'Lean protein and vegetables in one bowl, without the added sodium load a canned soup usually carries.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_soup_chicken_vegetable',
    linkedBuilderType: 'soup',
  },
  {
    id: 'recipe-soup-butternut-squash',
    category: 'recipes',
    title: 'Butternut Squash Soup',
    teaser: 'Creamy and naturally sweet, with a warm hint of nutmeg.',
    summary: 'A whole-vegetable soup with no added cream needed for its own naturally creamy texture once blended.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_soup_butternut_squash',
    linkedBuilderType: 'soup',
  },
  {
    id: 'recipe-soup-red-lentil',
    category: 'recipes',
    title: 'Red Lentil Soup',
    teaser: 'Warm, earthy, and lightly spiced with cumin.',
    summary: 'Plant protein and fiber from the lentils, a filling, whole-food soup that needs no meat at all.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_soup_red_lentil',
    linkedBuilderType: 'soup',
  },
  {
    id: 'recipe-soup-tomato-basil',
    category: 'recipes',
    title: 'Tomato Basil Soup',
    teaser: 'Bright, herbal, and comforting.',
    summary: 'Whole tomatoes rather than a canned condensed soup base, with fresh basil instead of a dried seasoning packet.',
    citations: [],
    overallTier: 'strong',
    linkedCuratedRecipeId: 'curated_soup_tomato_basil',
    linkedBuilderType: 'soup',
  },
];
