// What is wrong with a plant, crop by crop: the basic crops that had no
// guide until batch 5 (I26, 2026-09-29). Peach, dry beans, chickpea,
// lentil, soybean, peanut, ginger, turmeric, collards, mustard greens,
// Florence fennel, tomatillo and cowpea came in as full guides and signs
// together. Gathered by lib/cropSigns.ts, which explains the rules every
// sign here follows: each cites a page about that crop, a sign no source
// for the crop describes is left out rather than borrowed, and the fixes
// are put right from the soil and name no bag or bottle.
//
// The chickpea and lentil nutrient signs come from the USDA ARS
// Compendium of Chickpea and Lentil Diseases and Pests, whose chapter on
// noninfectious disorders describes each shortage on those two crops. The
// field crop pages (Saskatchewan, Manitoba, North Dakota, Kansas State)
// are cited for what the trouble looks like on the plant, which is the
// same in a bed; their field rates are not repeated.
//
// Pure: no React and no database.

import type { CropConfirm, CropSign } from './cropSignTypes';
import type { GuideSource } from './plantNutrients';

const src = (label: string, url: string): GuideSource => ({ label, url });
const ucDry = (slug: string, title: string): GuideSource =>
  src(`UC IPM: ${title} in dry beans`, `https://ipm.ucanr.edu/agriculture/dry-beans/${slug}/`);

// Peach.
const USU_PEACH = src('Utah State University: Peaches in the garden', 'https://extension.usu.edu/yardandgarden/research/peaches-in-the-garden');
const CLEMSON_PEACH = src('Clemson HGIC: Peach diseases', 'https://hgic.clemson.edu/factsheet/peach-diseases/');
const RHS_PEACH = src('RHS: Peaches and nectarines', 'https://www.rhs.org.uk/fruit/peaches/grow-your-own');

// Dry beans, and the blackeye pages that serve cowpea.
const UC_DRY_NUTRIENT = ucDry('nutrient-deficiency-and-toxicity', 'Nutrient deficiency and toxicity');
const UC_WHITE_MOLD = ucDry('white-mold', 'White mold');
const UC_ROOT_ROTS = ucDry('root-rots', 'Root rots');
const UC_FUSARIUM = ucDry('fusarium-wilt', 'Fusarium wilt');
const UC_BACTERIAL_BLIGHT = ucDry('common-bacterial-blight', 'Common bacterial blight');
const UC_HALO = ucDry('halo-blight', 'Halo blight');
const UC_ANTHRACNOSE = ucDry('bean-anthracnose', 'Bean anthracnose');
const UC_NEMATODES = ucDry('nematodes', 'Nematodes');
const UC_SUNSCALD = ucDry('sunscald', 'Sunscald');
const UC_MOSAIC = ucDry('bean-common-mosaic', 'Bean common mosaic');
const UC_CUTOUT = ucDry('cut-out-blackeyes', 'Cut-out of blackeyes');
const UC_ASCOCHYTA = ucDry('ascochyta-blight-garbanzo-beans', 'Ascochyta blight of garbanzo beans');
const USU_BEANS = src('Utah State University: Beans in the garden', 'https://extension.usu.edu/yardandgarden/research/beans-in-the-garden');
const NEV_DRY_BEAN = src('UMass New England Vegetable Management Guide: Bean (snap, lima and dry)', 'https://nevegetable.org/crops/bean-snap-lima-and-dry');

// Chickpea and lentil.
const ARS_COMPENDIUM = src('USDA ARS Compendium of Chickpea and Lentil Diseases: Noninfectious disorders', 'https://www.ars.usda.gov/ARSUserFiles/20902000/Compendium/Part4-Noninfectious_Disorders.doc');
const SASK_CHICKPEA = src('Saskatchewan Pulse Growers: Chickpea seeding', 'https://saskpulse.com/growing-pulses/chickpeas/chickpeas-seeding/');
const MB_LENTIL = src('Manitoba Agriculture: Lentils', 'https://www.gov.mb.ca/agriculture/crops/crop-management/lentils.html');
const NDSU_LENTIL = src('NDSU: Lentil disease diagnostic series', 'https://www.ndsu.edu/agriculture/extension/publications/lentil-disease-diagnostic-series');

// Soybean.
const KSU_SOY = src('Kansas State University: Nutrient deficiencies in soybeans', 'https://www.agronomy.k-state.edu/eupdates/2026/issue-1110-july-2/nutrient-deficiencies-soybeans-2026.html');
const NCSU_SOY = src('NC State: Soybean diagnostic key', 'https://diagnosis.ces.ncsu.edu/soybean/');
const RHS_SOY = src('RHS: Soya beans', 'https://www.rhs.org.uk/vegetables/soya-beans/grow-your-own');

// Peanut.
const CLEMSON_PEANUT = src('Clemson HGIC: Peanut', 'https://hgic.clemson.edu/factsheet/peanut/');
const USU_PEANUT = src('Utah State University: Peanuts in the garden', 'https://extension.usu.edu/yardandgarden/research/peanuts-in-the-garden');
const MSU_PEANUT = src('Mississippi State University: Peanuts', 'https://extension.msstate.edu/lawn-and-garden/vegetable-gardens/peanuts');

// Ginger and turmeric.
const UF_GINGER = src('University of Florida: Ginger', 'https://gardeningsolutions.ifas.ufl.edu/plants/edibles/vegetables/ginger/');
const VT_GINGER = src('Virginia Tech: Ginger', 'https://ext.vt.edu/lawn-garden/Timely_Topics/Ginger.html');
const UVM_GINGER_TURMERIC = src('University of Vermont: Growing ginger and turmeric indoors', 'https://www.uvm.edu/extension/news/growing-ginger-and-turmeric-indoors');
const UGA_GINGER_TURMERIC = src('University of Georgia: Growing ginger and turmeric at home', 'https://site.extension.uga.edu/fultonag/2021/03/growing-ginger-and-turmeric-at-home/');
const NCSU_GINGER_TURMERIC = src('NC State Caldwell County: Ginger and turmeric', 'https://caldwell.ces.ncsu.edu/news/ginger-and-turmeric-tropical-superfoods-for-the-garden/');
const UF_TURMERIC = src('University of Florida: Turmeric', 'https://gardeningsolutions.ifas.ufl.edu/plants/edibles/vegetables/turmeric/');

// Collards and mustard greens.
const CLEMSON_COLLARDS = src('Clemson HGIC: Collards', 'https://hgic.clemson.edu/factsheet/collards/');
const UF_COLLARDS = src('University of Florida: Collards', 'https://gardeningsolutions.ifas.ufl.edu/plants/edibles/vegetables/collards/');
const NEV_BRASSICA = src('UMass New England Vegetable Management Guide: Brassica crops', 'https://nevegetable.org/crops/cabbage-broccoli-cauliflower-and-other-brassica-crops');
const FSA_MUSTARD = src('University of Arkansas FSA6072: Mustard greens', 'https://www.uaex.uada.edu/publications/pdf/FSA-6072.pdf');
const NCSU_MUSTARD = src('NC State Plant Toolbox: Mustard greens', 'https://plants.ces.ncsu.edu/plants/brassica-juncea/common-name/mustard-greens/');
const SASK_MUSTARD_N = src('Saskatchewan Mustard: Nitrogen', 'https://www.saskmustard.com/production-manual/fertility/nitrogen/index.html');

// Fennel.
const USU_FENNEL = src('Utah State University: Fennel in the garden', 'https://extension.usu.edu/yardandgarden/research/fennel-in-the-garden');
const RHS_FENNEL = src('RHS: Florence fennel', 'https://www.rhs.org.uk/vegetables/florence-fennel/grow-your-own');
const UF_FENNEL = src('University of Florida: Fennel', 'https://gardeningsolutions.ifas.ufl.edu/plants/edibles/vegetables/fennel/');

// Tomatillo.
const USU_TOMATILLO = src('Utah State University: Tomatillos in the garden', 'https://extension.usu.edu/yardandgarden/research/tomatillos-in-the-garden');
const UF_TOMATILLO = src('University of Florida: Tomatillos', 'https://gardeningsolutions.ifas.ufl.edu/plants/edibles/vegetables/tomatillos/');
const NCSU_TOMATILLO = src('NC State Wilkes County: Growing tomatillos in the home garden', 'https://wilkes.ces.ncsu.edu/news/growing-tomatillos-in-the-home-garden/');

// Cowpea.
const CLEMSON_SOUTHERN_PEAS = src('Clemson HGIC: Southern peas', 'https://hgic.clemson.edu/factsheet/southern-peas/');
const UF_SOUTHERN_PEAS = src('University of Florida: Southern peas', 'https://gardeningsolutions.ifas.ufl.edu/plants/edibles/vegetables/southern-peas/');

export const NEW_CROP_SIGNS: Record<string, CropSign[]> = {
  peach: [
    {
      kind: 'short',
      nutrient: 'Fe',
      label: 'Iron shortage',
      where: ['yn'],
      looks: 'The young leaves turn yellow between the veins while the veins stay green. In a bad case the leaves go almost white and drop.',
      why: 'Common on high pH soil and on heavy clay, where the iron is there but the roots cannot take it up.',
      fix: 'Test the pH before planting. Mulch with compost every year, keep it off the trunk, and do not overwater a heavy soil, since wet, airless clay makes it worse.',
      sources: [USU_PEACH],
    },
    {
      kind: 'excess',
      nutrient: 'N',
      label: 'Too much growth from nitrogen',
      where: ['st', 'ha'],
      looks: 'Long, soft new shoots and plenty of leaf. A young tree making more than about 24 in of new shoot a year has more than enough.',
      why: 'Young trees average 18 to 24 in of new growth a year. Past that, extra nitrogen goes into leaf at the cost of fruit and ripening.',
      fix: 'Hold back all feeding while the shoots grow more than 24 in a year. A compost mulch is enough for a tree that is growing well.',
      sources: [USU_PEACH, RHS_PEACH],
    },
    {
      kind: 'water',
      label: 'Too much water or poor drainage',
      where: ['yo', 'wi', 'st', 'ro'],
      looks: 'Yellowing leaves, a tree that declines and dies back from the tips, most often a tree planted in the last year or two.',
      why: 'Peach roots need air. Wet, poorly drained soil also lets Phytophthora into the crown.',
      fix: 'Water deeply and seldom, about 30 in over a season, letting the top dry between soaks. On heavy soil plant on a mound or a raised bed 6 to 10 in high, and never deeper than the tree grew in the nursery.',
      sources: [USU_PEACH, CLEMSON_PEACH],
    },
    {
      kind: 'water',
      label: 'Uneven watering at fruiting',
      where: ['ha', 'fl'],
      looks: 'Fruit drops before it ripens, or splits open as it ripens.',
      why: 'Dry spells while the fruit swells drop it; heavy watering or rain as it ripens splits it.',
      fix: 'Keep the soil evenly moist from flowering to harvest under a thick compost mulch, and ease off the watering as the fruit starts to colour.',
      sources: [RHS_PEACH],
    },
    {
      kind: 'ph',
      label: 'Soil pH off, or an old peach site',
      where: ['wi', 'st'],
      looks: 'A young tree that grows well for a few years and then collapses suddenly in spring, the sap sour when the bark is cut.',
      why: 'Peach tree short life is worst on acid, sandy soil and where peaches grew before.',
      fix: 'Test the soil and bring it to about pH 6.5 before planting, working the lime in deeply. Do not replant where a peach tree has just died or been taken out.',
      sources: [CLEMSON_PEACH],
    },
    {
      kind: 'mimic',
      label: 'Peach leaf curl',
      where: ['cu', 'pu'],
      looks: 'In spring the new leaves pucker, thicken and curl, turning red or purple, then yellow and drop.',
      why: 'A fungus that infects the buds in cool, wet weather before they open. Nothing helps once it shows, and the tree grows a second set of leaves.',
      fix: 'A peach grown in a pot can be moved under cover over winter and early spring, which protects it from leaf curl and frost. For a tree in the ground, feed the soil with compost so the second flush grows strongly, and clear fallen leaves.',
      sources: [CLEMSON_PEACH, RHS_PEACH],
    },
    {
      kind: 'mimic',
      label: 'Bacterial spot or shot hole',
      where: ['sp', 'ha'],
      looks: 'Small reddish purple spots on the leaves whose centres fall out and leave holes, then the leaves yellow and drop. The fruit carries reddish spots or cracks.',
      why: 'Spread by rain and wind, and by water splashed on the canopy.',
      fix: 'Keep sprinklers off the leaves and water the soil. When buying a tree choose a resistant variety such as Belle of Georgia or Redhaven, and clear fallen leaves to the compost.',
      sources: [CLEMSON_PEACH, USU_PEACH],
    },
    {
      kind: 'mimic',
      label: 'Brown rot',
      where: ['ha', 'fl'],
      looks: 'Flowers wilt and brown. On the fruit a small round brown spot spreads over the whole peach, which shrivels into a hard mummy that hangs on the tree.',
      why: 'A fungus that lives in the mummies and in cankers on the twigs, and spreads in wet weather at flowering and ripening.',
      fix: 'Pick off every mummy and cut out cankered twigs, prune to let air through the tree, and pick up fallen fruit.',
      sources: [CLEMSON_PEACH],
    },
    {
      kind: 'mimic',
      label: 'Frost or poor pollination',
      where: ['fl', 'ha'],
      looks: 'The tree flowers well but sets little or no fruit.',
      why: 'Peaches flower very early, when frost is likely and few insects are about.',
      fix: 'Grow against a sunny wall where frost is less likely and cover the flowers on frosty nights. Brush pollen from flower to flower with a soft paintbrush on a dry day.',
      sources: [RHS_PEACH, USU_PEACH],
    },
  ],
  drybeans: [
    {
      kind: 'short',
      nutrient: 'N',
      label: 'Nitrogen shortage',
      where: ['yo', 'st', 'fl', 'ha'],
      looks: 'The older, lower leaves turn pale green to yellow, and the plants are stunted, with few flowers and poorly filled pods.',
      why: 'Most common on sandy soil low in organic matter and after heavy rain. The bacteria that let beans make nitrogen for themselves are missing from many soils.',
      fix: 'Dig compost into the bed before sowing and mulch to keep it there. Where beans have not grown before, a bean inoculant at sowing brings the bacteria in.',
      sources: [UC_DRY_NUTRIENT],
    },
    {
      kind: 'short',
      nutrient: 'P',
      label: 'Phosphorus shortage',
      where: ['st', 'yo', 'fl'],
      looks: 'Slow growth, with small, dark green top leaves and the older leaves yellowing then browning. The stems are thin and flowers drop.',
      why: 'Phosphorus is much harder for beans to reach in soil below about pH 6.2.',
      fix: 'Test the pH and lime acid soil by the result. Compost dug in where the roots will be, and living soil fungi on those roots, carry phosphorus to the plant.',
      sources: [UC_DRY_NUTRIENT],
    },
    {
      kind: 'short',
      nutrient: 'K',
      label: 'Potassium shortage',
      where: ['ed', 'yo', 'cu'],
      looks: 'The edges of the older leaves yellow, then scorch between the veins, and the leaves curl.',
      why: 'Shows on poor, sandy soil and in soil below about pH 6.',
      fix: 'Mulch with comfrey leaves and work compost in every year. Add wood ash only after a pH test shows the soil is not already alkaline.',
      sources: [UC_DRY_NUTRIENT],
    },
    {
      kind: 'short',
      nutrient: 'Zn',
      label: 'Zinc shortage',
      where: ['yn', 'st', 'fl'],
      looks: 'The younger leaves come pale and misshapen with yellowing between the veins, then dead patches. Flowers and pods can drop.',
      why: 'Found in alkaline soil, in soil given too much lime or phosphorus, and in compacted soil low in organic matter.',
      fix: 'Test the pH before adding lime, and go easy on phosphorus-rich feeds. Loosen the soil with compost so the roots and their fungi can reach the zinc already there.',
      sources: [UC_DRY_NUTRIENT],
    },
    {
      kind: 'excess',
      nutrient: 'B',
      label: 'Too much boron',
      where: ['ed', 'yo', 'st'],
      looks: 'Yellow leaf tips, yellowing between the veins, and scorching that spreads in from the edges. The plants are stunted.',
      why: 'Beans are very sensitive to boron, and it builds up where the crop before was given it.',
      fix: 'Never add boron to a bean bed, and do not follow a crop that was given boron with beans. Water leaches the excess out over time.',
      sources: [UC_DRY_NUTRIENT],
    },
    {
      kind: 'water',
      label: 'Heat and dry soil at flowering',
      where: ['fl', 'wi'],
      looks: 'The flowers drop without setting pods, most often in a hot spell.',
      why: 'Above about 95°F, and in dry soil, beans shed their flowers.',
      fix: 'Keep the soil evenly moist through flowering under a mulch of straw or compost, and sow so that flowering misses the hottest weeks.',
      sources: [USU_BEANS],
    },
    {
      kind: 'water',
      label: 'Too much water',
      where: ['ro', 'yo', 'st'],
      looks: 'Small, yellowing plants with brick red marks on the roots and the stem at soil level that turn brown.',
      why: 'Root rots are worse in soil kept wet, in soil that goes very dry, and when seed goes into cold soil.',
      fix: 'Sow into warm soil, water deeply and let the top dry between waterings, and grow beans on a bed that drains. Rotate with grasses or grains where it has been bad.',
      sources: [UC_ROOT_ROTS, USU_BEANS],
    },
    {
      kind: 'mimic',
      label: 'White mould',
      where: ['ro', 'wi', 'ha'],
      looks: 'A soft, watery rot on stems and pods covered in white threads, with hard black bodies like seeds. The stems bleach tan.',
      why: 'Worst in a thick, damp canopy, which heavy feeding with nitrogen brings on.',
      fix: 'Space the plants widely, feed the soil with compost rather than extra nitrogen, water the soil early in the day, and pull and bin sick plants with their black bodies.',
      sources: [UC_WHITE_MOLD],
    },
    {
      kind: 'mimic',
      label: 'Fusarium wilt',
      where: ['yo', 'wi'],
      looks: 'The lower leaves yellow and wilt, then the yellowing climbs the plant. Cut the stem and it is streaked red brown inside.',
      why: 'A fungus that lives in the soil for years.',
      fix: 'Grow a resistant variety from clean seed and rotate beans around the garden, keeping them out of a bed where it showed.',
      sources: [UC_FUSARIUM],
    },
    {
      kind: 'mimic',
      label: 'Bacterial blights',
      where: ['sp'],
      looks: 'Water-soaked spots on the leaves. Common blight gives them a lemon yellow border; halo blight gives a wide light green halo.',
      why: 'Both are carried on seed and spread by splashing water.',
      fix: 'Sow clean seed, water the soil rather than the leaves, and stay out of the beans while they are wet.',
      sources: [UC_BACTERIAL_BLIGHT, UC_HALO],
    },
    {
      kind: 'mimic',
      label: 'Anthracnose',
      where: ['sp', 'ha'],
      looks: 'Sunken, black to red brown cankers on the pods, with dark marks along the leaf veins.',
      why: 'Carried on seed and spread in cool, wet weather.',
      fix: 'Sow clean seed, do not save seed from spotted pods, and keep beans off that bed for two to three years.',
      sources: [UC_ANTHRACNOSE],
    },
    {
      kind: 'mimic',
      label: 'Common mosaic virus',
      where: ['cu', 'yn', 'st'],
      looks: 'Leaves mottled light and dark green, puckered and curled down, on stunted plants.',
      why: 'Carried in seed and spread by aphids.',
      fix: 'Sow certified seed or a resistant variety, and pull and bin plants that show it.',
      sources: [UC_MOSAIC],
    },
    {
      kind: 'mimic',
      label: 'Root knot nematodes',
      where: ['yo', 'st', 'wi', 'ro'],
      looks: 'Patches of yellow, stunted plants that wilt in the heat, with lumpy swellings on the roots. Nitrogen nodules come off easily and are pink inside; the swellings do not.',
      why: 'Worst in sandy soil.',
      fix: 'Rotate beans away from the patch and build the soil with compost, which feeds the living things that keep nematodes down.',
      sources: [UC_NEMATODES],
    },
    {
      kind: 'mimic',
      label: 'Sunscald',
      where: ['sp', 'ha'],
      looks: 'Small water-soaked spots on the sunny side of the pods and leaves that turn reddish brown.',
      why: 'Strong sun after a dull, cool spell.',
      fix: 'Nothing is needed; it does not spread. Keep the plants well watered so the leaves stay full over the pods.',
      sources: [UC_SUNSCALD],
    },
  ],
  chickpea: [
    {
      kind: 'short',
      nutrient: 'N',
      label: 'Nitrogen shortage',
      where: ['yo', 'st', 'pu'],
      looks: 'The older leaves turn yellow green and the plants stay small. Desi, the small dark kinds, can turn pink. Nodules that work are pink inside.',
      why: 'The nodule bacteria for chickpea are often missing from garden soil.',
      fix: 'Where chickpeas have not grown before, use a chickpea inoculant at sowing, and work compost in before sowing.',
      sources: [ARS_COMPENDIUM],
    },
    {
      kind: 'short',
      nutrient: 'P',
      label: 'Phosphorus shortage',
      where: ['st', 'yo', 'pu'],
      looks: 'The plants stay dark green and small, then the older leaflets yellow and the lower leaves turn red brown.',
      fix: 'Work compost in and keep the soil living and undisturbed; the soil fungi on chickpea roots carry phosphorus to the plant.',
      sources: [ARS_COMPENDIUM],
    },
    {
      kind: 'short',
      nutrient: 'K',
      label: 'Potassium shortage',
      where: ['ed', 'yo'],
      looks: 'The edges of the older leaves turn yellow green, then redden, and the leaves drop.',
      fix: 'Mulch with comfrey leaves and work compost in every year, testing the pH before adding wood ash.',
      sources: [ARS_COMPENDIUM],
    },
    {
      kind: 'short',
      nutrient: 'Ca',
      label: 'Calcium shortage in acid soil',
      where: ['yn', 'st'],
      looks: 'The growing tip turns rusty and dies back, and the roots stay short and thick.',
      why: 'Shows below about pH 5.5.',
      fix: 'Test the pH and lime by the result before sowing, working the lime into the root zone.',
      sources: [ARS_COMPENDIUM],
    },
    {
      kind: 'short',
      nutrient: 'S',
      label: 'Sulphur shortage',
      where: ['yn', 'pu'],
      looks: 'Yellowing that starts at the top of the plant, with reddish brown stems.',
      why: 'Seen on light soil and on chalky soil of pH 8 or more.',
      fix: 'Compost and animal manures carry sulphur. Dig them in before sowing.',
      sources: [ARS_COMPENDIUM],
    },
    {
      kind: 'short',
      nutrient: 'Fe',
      label: 'Iron shortage',
      where: ['yn'],
      looks: 'The young leaves turn yellow between the veins, some with white patches. It often passes as the soil warms.',
      why: 'Seen on chalky soil of high pH, especially when it is cold and wet.',
      fix: 'Work compost in to open the soil, avoid liming a soil that is already alkaline, and let the soil drain and warm before sowing.',
      sources: [ARS_COMPENDIUM],
    },
    {
      kind: 'short',
      nutrient: 'Zn',
      label: 'Zinc shortage',
      where: ['yn', 'st', 'ed'],
      looks: 'Six to eight weeks from sowing the young leaves yellow and bunch into a rosette, with reddish brown edges.',
      why: 'Worse at high pH and in soil low in organic matter.',
      fix: 'Work compost in every year; organic matter eases it. Avoid heavy phosphorus-rich feeds.',
      sources: [ARS_COMPENDIUM],
    },
    {
      kind: 'excess',
      nutrient: 'B',
      label: 'Too much boron or salt',
      where: ['ed', 'yo'],
      looks: 'The tips of the lower leaflets yellow then brown, or the edges of older leaves die. Salty soil also slows the seed coming up.',
      fix: 'Never add boron to a chickpea bed. Water deeply now and then to wash salts below the roots, and use rain water where the tap water is hard or salty.',
      sources: [ARS_COMPENDIUM],
    },
    {
      kind: 'water',
      label: 'Wet soil or heat at flowering',
      where: ['ro', 'wi', 'fl'],
      looks: 'Plants that yellow and rot at the base in wet soil, or flowers and young pods that drop in a hot spell.',
      why: 'Chickpeas do not tolerate wet soil, and heat of 30°C and above stresses the flowers and pods.',
      fix: 'Grow chickpeas on a bed that drains and water only when the top of the soil is dry. Sow so that flowering comes before the hottest weeks.',
      sources: [SASK_CHICKPEA],
    },
    {
      kind: 'mimic',
      label: 'Ascochyta blight',
      where: ['sp', 'wi', 'ha'],
      looks: 'Brown, round spots on the leaves, stems and pods with tiny black dots in rings. The stems can snap where the spots girdle them.',
      why: 'Carried on seed and on old chickpea stems, not in the soil, and spread in cool rain.',
      fix: 'Sow clean seed, space the plants widely, bury or compost the old plants, and keep chickpeas off that bed for two to three years.',
      sources: [UC_ASCOCHYTA],
    },
  ],
  lentil: [
    {
      kind: 'short',
      nutrient: 'N',
      label: 'Nitrogen shortage',
      where: ['yo', 'st'],
      looks: 'The older leaves turn yellow green and the plants stay small. Nodules that work are pink inside.',
      why: 'The nodule bacteria for lentil are often missing from garden soil.',
      fix: 'Where lentils have not grown before, use a lentil inoculant at sowing; extra nitrogen is not needed once the nodules work.',
      sources: [ARS_COMPENDIUM, MB_LENTIL],
    },
    {
      kind: 'short',
      nutrient: 'S',
      label: 'Sulphur shortage',
      where: ['yn', 'pu'],
      looks: 'Yellowing that starts at the top of the plant, with reddish brown stems.',
      why: 'Sulphur can run short in many soils.',
      fix: 'Compost and animal manures carry sulphur. Dig them in before sowing.',
      sources: [ARS_COMPENDIUM, MB_LENTIL],
    },
    {
      kind: 'short',
      nutrient: 'Zn',
      label: 'Zinc shortage',
      where: ['yn', 'st', 'ed'],
      looks: 'Six to eight weeks from sowing the young leaves yellow and bunch into a rosette, with reddish brown edges.',
      why: 'Lentil needs more zinc than chickpea, and runs short at high pH and in soil low in organic matter.',
      fix: 'Work compost in every year and avoid heavy phosphorus-rich feeds.',
      sources: [ARS_COMPENDIUM],
    },
    {
      kind: 'short',
      nutrient: 'Fe',
      label: 'Iron shortage',
      where: ['yn'],
      looks: 'The young leaves turn yellow between the veins, some with white patches. It often passes as the soil warms.',
      why: 'Seen on chalky soil of high pH.',
      fix: 'Work compost in to open the soil and avoid liming a soil that is already alkaline.',
      sources: [ARS_COMPENDIUM],
    },
    {
      kind: 'excess',
      nutrient: 'B',
      label: 'Too much boron',
      where: ['ed', 'yo'],
      looks: 'The tips of the lower leaflets yellow then turn brown.',
      why: 'Lentil is more sensitive to boron than chickpea.',
      fix: 'Never add boron to a lentil bed, and do not follow a crop that was given boron with lentils.',
      sources: [ARS_COMPENDIUM],
    },
    {
      kind: 'water',
      label: 'Wet, cold soil',
      where: ['ro', 'yo', 'pu', 'st'],
      looks: 'Poor emergence, then stunted plants with yellow or purple leaves from the bottom up and brown roots.',
      why: 'Pythium and other root rots come with cool, waterlogged or compacted soil.',
      fix: 'Grow lentils on a bed that drains, open heavy soil with compost, and water only when the top is dry. Keep lentils off the bed for at least four years where root rot showed.',
      sources: [NDSU_LENTIL, MB_LENTIL],
    },
    {
      kind: 'mimic',
      label: 'Ascochyta blight or anthracnose',
      where: ['sp', 'ha'],
      looks: 'Ascochyta gives light brown spots with dark borders and tiny dots in rings on leaves, stems and pods. Anthracnose starts as white to grey spots at the base of the stem and climbs, the leaves dropping.',
      why: 'Both are carried on seed and old lentil plants and spread in rain.',
      fix: 'Sow clean seed, compost or bury the old plants, and grow lentils in any one bed only once in four years.',
      sources: [MB_LENTIL, NDSU_LENTIL],
    },
    {
      kind: 'mimic',
      label: 'Stemphylium blight',
      where: ['yo', 'sp'],
      looks: 'Tan to light brown spots on the leaflets late in the season, then the leaves go grey brown and drop. It is easy to take for a nitrogen shortage or for the plant ageing.',
      why: 'Long spells of damp air late in the season. Red lentils are hit harder than green.',
      fix: 'Space the plants for air, water the soil and not the leaves, and grow a green lentil where it keeps coming back.',
      sources: [NDSU_LENTIL],
    },
    {
      kind: 'mimic',
      label: 'Grey mould',
      where: ['sp', 'wi', 'ro'],
      looks: 'Grey fuzz on stems, leaves and pods low in the plant. Plants yellow, wilt and die when the stem is girdled.',
      fix: 'Space the plants for air, keep weeds down around them, and pull sick plants to stop it spreading from plant to plant.',
      sources: [NDSU_LENTIL],
    },
  ],
  soybean: [
    {
      kind: 'short',
      nutrient: 'N',
      label: 'Nitrogen shortage',
      where: ['yo', 'st'],
      looks: 'The lower leaves turn pale, with few nodules on the roots.',
      why: 'The nodule bacteria for soya are missing where it has not been grown.',
      fix: 'Use a soybean inoculant at sowing where soya has not grown before, and work compost in.',
      sources: [KSU_SOY],
    },
    {
      kind: 'short',
      nutrient: 'P',
      label: 'Phosphorus shortage',
      where: ['st', 'pu', 'cu', 'fl'],
      looks: 'Dark green plants, the leaves purple tinged and cupped, flowering late.',
      why: 'Seen most in cool, wet soil early in the season.',
      fix: 'Sow into soil that has warmed, and work compost in; the soil fungi on the roots carry phosphorus to the plant.',
      sources: [KSU_SOY],
    },
    {
      kind: 'short',
      nutrient: 'K',
      label: 'Potassium shortage',
      where: ['ed', 'yo'],
      looks: 'The edges of the older leaves turn yellow.',
      fix: 'Mulch with comfrey leaves and work compost in every year, testing the pH before adding wood ash.',
      sources: [KSU_SOY],
    },
    {
      kind: 'short',
      nutrient: 'S',
      label: 'Sulphur shortage',
      where: ['yn'],
      looks: 'The upper, newest leaves come pale while the older ones stay green.',
      why: 'Seen in cool, wet soil and soil low in organic matter.',
      fix: 'Compost and animal manures carry sulphur. Dig them in before sowing.',
      sources: [KSU_SOY],
    },
    {
      kind: 'short',
      nutrient: 'Mg',
      label: 'Magnesium shortage',
      where: ['yo', 'pu'],
      looks: 'The lower leaves go pale and mottled, then bronze.',
      why: 'Most common on sandy soil.',
      fix: 'Work compost in every year to hold nutrients in a sandy soil. Test the soil before adding anything for it.',
      sources: [KSU_SOY],
    },
    {
      kind: 'short',
      nutrient: 'Fe',
      label: 'Iron shortage',
      where: ['yn'],
      looks: 'The young leaves turn yellow between the veins while the veins stay green.',
      why: 'Common on chalky soil of high pH.',
      fix: 'Work compost in and avoid liming a soil that is already alkaline. Plants often grow out of it as the soil warms and dries.',
      sources: [KSU_SOY],
    },
    {
      kind: 'short',
      nutrient: 'Mn',
      label: 'Manganese shortage',
      where: ['yn'],
      looks: 'The young leaves go pale between the veins.',
      why: 'Seen at pH 7 or more, and on sandy or very high organic matter soil.',
      fix: 'Test the pH before liming, and never lime a soil already near neutral.',
      sources: [KSU_SOY],
    },
    {
      kind: 'water',
      label: 'Dry soil at flowering',
      where: ['fl', 'ha'],
      looks: 'Flowers drop and pods stay few or empty.',
      fix: 'Keep the soil moist from flowering on under a mulch.',
      sources: [RHS_SOY],
    },
    {
      kind: 'mimic',
      label: 'A cool summer',
      where: ['st', 'fl'],
      looks: 'Plants that stay small and set few pods.',
      why: 'Soya needs warmth. In a cool climate an early variety and a sheltered, sunny spot matter most.',
      fix: 'Grow an early variety suited to cool summers, sow into warm soil in a sunny, sheltered bed, and warm the soil under a cloche first.',
      sources: [RHS_SOY],
    },
    {
      kind: 'mimic',
      label: 'Mice and slugs',
      where: ['ot', 'ho'],
      looks: 'Seed that never comes up, or seedlings with holes and slime trails.',
      fix: 'Start the seed in pots under cover and plant out once the plants are sturdy. Keep the bed edges trimmed and go out on damp evenings to lift slugs.',
      sources: [RHS_SOY],
    },
  ],
  peanut: [
    {
      kind: 'short',
      nutrient: 'Ca',
      label: 'Calcium shortage in the pod zone',
      where: ['ha'],
      looks: 'Pods that are empty or only partly filled, and pods that rot.',
      why: 'Peanut pods take calcium straight from the soil around them, not through the plant. It runs short on sandy soil in dry spells, and potash left in the top few inches blocks it.',
      fix: 'Test the pH and lime to about 5.8 to 6.2, which also supplies calcium. Dig any potash-rich material about 6 in down rather than leaving it in the top of the soil, and keep the soil moist while the pegs go in.',
      sources: [CLEMSON_PEANUT, MSU_PEANUT],
    },
    {
      kind: 'short',
      nutrient: 'N',
      label: 'Yellow plants from missing nodule bacteria',
      where: ['yo', 'st'],
      looks: 'Plants yellow all over and slow to grow.',
      why: 'Where peanuts have not grown for about four years, the nodule bacteria that feed them nitrogen may be missing.',
      fix: 'Use a peanut inoculant at sowing where peanuts are new to the bed, rather than feeding nitrogen.',
      sources: [CLEMSON_PEANUT],
    },
    {
      kind: 'excess',
      label: 'Feed burn',
      where: ['ed', 'wi', 'st'],
      looks: 'Scorched leaf edges and plants that stall or die after feeding.',
      why: 'Peanuts are very easily burned by feed.',
      fix: 'Feed the soil with compost worked in the season before, and do not put feed close to the seed or the plants.',
      sources: [CLEMSON_PEANUT],
    },
    {
      kind: 'ph',
      label: 'Acid soil',
      where: ['st', 'ha'],
      looks: 'Slow plants and poorly filled pods.',
      why: 'Peanuts are sensitive to low pH and the low calcium that goes with it.',
      fix: 'Test and lime by the result to about pH 5.8 to 6.2, well before sowing.',
      sources: [MSU_PEANUT, CLEMSON_PEANUT],
    },
    {
      kind: 'water',
      label: 'Uneven water, or dry soil while pegging',
      where: ['ha', 'ro', 'fl'],
      looks: 'Few pods where dry soil or a hard crust kept the pegs out, or rotting roots after swings from dry to wet.',
      why: 'Water matters most from about 60 to 110 days, when the pegs push into the soil. A peg that cannot get in makes no pod.',
      fix: 'Keep the soil evenly moist from flowering, loosen or hill it up about 6 in once the plants are a foot tall and then mulch, and stop watering 10 to 14 days before lifting.',
      sources: [CLEMSON_PEANUT, USU_PEANUT, MSU_PEANUT],
    },
    {
      kind: 'mimic',
      label: 'A short or cool season',
      where: ['st', 'ot'],
      looks: 'Seed slow to come up and plants that never fill their pods before the cold.',
      why: 'Peanuts need more than 110 frost-free days, grow best around 85°F and come up best in soil of 68 to 95°F.',
      fix: 'Sow once the soil is warm, or start in deep pots indoors, and grow an early, small-podded kind where summers are short.',
      sources: [USU_PEANUT, CLEMSON_PEANUT],
    },
    {
      kind: 'mimic',
      label: 'Southern blight',
      where: ['ro', 'wi', 'ha'],
      looks: 'A plant that wilts and yellows with white mould at the stem base and on the pods, which rot.',
      fix: 'Keep old plant matter and leaf litter off the stem base, compost the old crop, and grow peanuts in a different bed each year.',
      sources: [MSU_PEANUT],
    },
    {
      kind: 'mimic',
      label: 'Leaf spot',
      where: ['sp', 'yo'],
      looks: 'Spotted leaves that yellow and drop early, so the plant looks ripe too soon and fills fewer pods.',
      fix: 'Grow peanuts in a different bed each year and clear the old tops to the compost.',
      sources: [MSU_PEANUT],
    },
  ],
  ginger: [
    {
      kind: 'water',
      label: 'Rhizome rot from too much water',
      where: ['ro', 'wi', 'yo'],
      looks: 'Leaves that yellow and droop, and a soft, rotting rhizome. It is the only serious trouble ginger has.',
      why: 'Too much water, poor drainage, and cut pieces planted before they dried.',
      fix: 'Let the cut ends dry and callus before planting, grow in loose, compost-rich soil or a free-draining pot, let the top dry slightly between waterings, and water less as the weather cools.',
      sources: [VT_GINGER, UF_GINGER, UVM_GINGER_TURMERIC, UGA_GINGER_TURMERIC],
    },
    {
      kind: 'mimic',
      label: 'Too much sun',
      where: ['ed', 'yo', 'st'],
      looks: 'Brown leaf tips, yellowing leaves and slow growth.',
      why: 'Ginger wants part shade; more than a few hours of strong sun burns it, and plants moved outside without hardening off scorch.',
      fix: 'Give it two to five hours of sun with shade in the afternoon, keep it watered, and bring an indoor plant into the sun a little more each day.',
      sources: [UF_GINGER, VT_GINGER, NCSU_GINGER_TURMERIC, UVM_GINGER_TURMERIC],
    },
    {
      kind: 'mimic',
      label: 'Store ginger that will not sprout',
      where: ['ot'],
      looks: 'A planted rhizome that does nothing for weeks.',
      why: 'Ginger from a shop may have been treated to stop it sprouting, and even untreated ginger can take 50 days or more.',
      fix: 'Plant organic or seed ginger with plump buds, soak and wash store ginger first, keep it at 68°F or more, and wait at least eight weeks before giving up.',
      sources: [VT_GINGER, UGA_GINGER_TURMERIC, UVM_GINGER_TURMERIC],
    },
    {
      kind: 'mimic',
      label: 'Cold',
      where: ['st', 'yo', 'ot'],
      looks: 'Growth stops and the leaves yellow as the nights cool.',
      why: 'Ginger grows at 68°F or more, suffers below 50°F and dies at freezing.',
      fix: 'Plant out only when the soil is above 55°F, and lift the rhizomes or bring the pot indoors before the first frost.',
      sources: [UVM_GINGER_TURMERIC, VT_GINGER, NCSU_GINGER_TURMERIC],
    },
    {
      kind: 'ph',
      label: 'Poor, heavy soil',
      where: ['st', 'ha'],
      looks: 'Small, thin rhizomes, or rhizomes pushing up out of the soil.',
      why: 'Ginger needs rich, loose soil, neutral to slightly acid.',
      fix: 'Grow it in soil rich in compost, and mound more soil or compost over rhizomes that show at the surface.',
      sources: [UF_GINGER, VT_GINGER, NCSU_GINGER_TURMERIC],
    },
  ],
  turmeric: [
    {
      kind: 'water',
      label: 'Rhizome rot from too much water',
      where: ['ro', 'wi', 'yo'],
      looks: 'Leaves that yellow and droop, and a soft, rotting rhizome.',
      why: 'Too much water, poor drainage, and cut pieces planted before they dried.',
      fix: 'Let the cut ends dry before planting, grow in loose, compost-rich soil or a free-draining pot, and let the top dry slightly between waterings.',
      sources: [UF_TURMERIC, UVM_GINGER_TURMERIC, UGA_GINGER_TURMERIC],
    },
    {
      kind: 'mimic',
      label: 'Too much sun',
      where: ['ed', 'yn', 'yo'],
      looks: 'Scorched, yellowing leaves.',
      why: 'Turmeric wants part to full shade, and burns when moved into sun too quickly.',
      fix: 'Grow it in dappled shade, and bring an indoor plant into the light a little more each day.',
      sources: [UF_TURMERIC, UVM_GINGER_TURMERIC, NCSU_GINGER_TURMERIC],
    },
    {
      kind: 'mimic',
      label: 'Slow to sprout',
      where: ['ot', 'st'],
      looks: 'A planted rhizome that does nothing for weeks.',
      why: 'Turmeric sprouts later than ginger, and store rhizomes may have been treated to stop them sprouting.',
      fix: 'Plant organic or seed turmeric with plump buds, keep it warm at 68°F or more, and give it two months or more.',
      sources: [UVM_GINGER_TURMERIC, UGA_GINGER_TURMERIC],
    },
    {
      kind: 'mimic',
      label: 'Cold',
      where: ['st', 'yo'],
      looks: 'Growth stops and the leaves yellow and die back as the nights cool.',
      why: 'Turmeric suffers below 50°F and dies at freezing.',
      fix: 'Plant out only once nights stay warm, and lift the rhizomes or bring the pot indoors before the first frost.',
      sources: [UVM_GINGER_TURMERIC, NCSU_GINGER_TURMERIC],
    },
    {
      kind: 'ph',
      label: 'Poor, heavy soil',
      where: ['st', 'ha'],
      looks: 'Small, thin rhizomes.',
      why: 'Turmeric needs rich, loose soil full of organic matter.',
      fix: 'Grow it in soil or potting mix rich in compost, and top up with compost as it grows.',
      sources: [UF_TURMERIC, NCSU_GINGER_TURMERIC],
    },
  ],
  collards: [
    {
      kind: 'short',
      nutrient: 'N',
      label: 'Nitrogen shortage',
      where: ['yo', 'st'],
      looks: 'Pale, yellowing lower leaves and small, slow plants.',
      why: 'Collards are grown for their leaves, and leaves need nitrogen.',
      fix: 'Dig compost or well-rotted manure in before planting, and side dress with compost as the plants grow.',
      sources: [CLEMSON_COLLARDS],
    },
    {
      kind: 'ph',
      label: 'Soil pH off',
      where: ['st', 'yn'],
      looks: 'Slow, poor plants that feeding does not help.',
      fix: 'Test the soil and bring it to pH 6.0 to 6.5 with lime or compost by the result.',
      sources: [CLEMSON_COLLARDS, UF_COLLARDS],
    },
    {
      kind: 'water',
      label: 'Dry soil',
      where: ['wi', 'ed'],
      looks: 'Leaves that wilt and go limp in the day.',
      fix: 'Water deeply, at least 6 in down, early in the day, and mulch to hold it.',
      sources: [CLEMSON_COLLARDS],
    },
    {
      kind: 'mimic',
      label: 'Bolting after a cold spell',
      where: ['bo'],
      looks: 'The plant sends up a flowering stalk and the leaves toughen.',
      why: 'A long cold spell sets collards to flower.',
      fix: 'Sow a bolt-tolerant variety in spring, and time sowings so young plants do not sit through a long cold spell.',
      sources: [CLEMSON_COLLARDS],
    },
    {
      kind: 'mimic',
      label: 'Black rot, downy mildew and leaf spot',
      where: ['yo', 'ed', 'sp'],
      looks: 'Leaves that yellow from the edges, go spotted or carry mould. Black rot, downy mildew and Alternaria leaf spot are the common diseases of collards, with Fusarium yellows in summer.',
      why: 'Black rot is a bacterium carried on seed and old brassica plants, and all of them spread on wet leaves.',
      fix: 'Grow from clean seed, rotate brassicas around the garden, water the soil early in the day rather than the leaves, and compost or bury old plants.',
      sources: [CLEMSON_COLLARDS],
    },
    {
      kind: 'mimic',
      label: 'Caterpillars and harlequin bugs',
      where: ['ho'],
      looks: 'Ragged holes in the leaves with caterpillars on the undersides, or shield-shaped bugs sucking the leaves. Aphids come most in autumn.',
      fix: 'Cover young plants with fine netting, hand pick caterpillars and bugs, and leave flowering herbs nearby for the wasps that hunt caterpillars.',
      sources: [CLEMSON_COLLARDS, UF_COLLARDS],
    },
    {
      kind: 'mimic',
      label: 'Seed sown too deep',
      where: ['ot'],
      looks: 'Seed that never comes up.',
      fix: 'Sow no deeper than ½ in and keep the surface moist until they come up.',
      sources: [CLEMSON_COLLARDS],
    },
  ],
  mustardgreens: [
    {
      kind: 'short',
      nutrient: 'N',
      label: 'Nitrogen shortage',
      where: ['yo', 'st'],
      looks: 'Pale green to yellow foliage, spindly plants, and yellowing older leaves.',
      fix: 'Dig compost in before sowing and feed the soil with compost between sowings; mustard grows fast and uses a lot.',
      sources: [SASK_MUSTARD_N, FSA_MUSTARD],
    },
    {
      kind: 'water',
      label: 'Heat and dry soil',
      where: ['bo', 'ot', 'wi'],
      looks: 'Plants that bolt, and leaves that turn tough and strong or bitter.',
      why: 'Mustard is a cool season plant; heat, dryness and poor soil make it bolt and strengthen the flavour.',
      fix: 'Sow in spring and autumn, give some shade as the weather warms, keep the soil moist and rich, and pick young.',
      sources: [NCSU_MUSTARD, FSA_MUSTARD],
    },
    {
      kind: 'mimic',
      label: 'Bolting from cold or moving',
      where: ['bo'],
      looks: 'A flower stalk on a young spring plant.',
      why: 'Cold spells and the shock of transplanting set it to flower.',
      fix: 'Sow mustard where it is to grow rather than transplanting it.',
      sources: [NEV_BRASSICA, FSA_MUSTARD],
    },
    {
      kind: 'mimic',
      label: 'Flea beetles',
      where: ['ho'],
      looks: 'Many tiny round holes in the leaves, with small black beetles that jump.',
      fix: 'Cover the seedlings with fine netting from sowing, and keep the soil moist, since the beetles like dry weather.',
      sources: [NEV_BRASSICA, FSA_MUSTARD],
    },
    {
      kind: 'mimic',
      label: 'Caterpillars, aphids and slugs',
      where: ['ho', 'cu'],
      looks: 'Ragged holes, green caterpillars, clusters of small insects under curled leaves, or slime trails.',
      fix: 'Net the bed, hand pick caterpillars, rub off aphids or wash them off with water, and lift slugs on damp evenings.',
      sources: [FSA_MUSTARD, NCSU_MUSTARD],
    },
  ],
  fennel: [
    {
      kind: 'water',
      label: 'Uneven watering',
      where: ['ha', 'bo'],
      looks: 'Split stems and bulbs, and plants that bolt.',
      why: 'Swings between dry and wet soil split the bulb, and dry soil makes it flower.',
      fix: 'Keep the soil evenly moist under a mulch the whole time the bulb swells.',
      sources: [USU_FENNEL, RHS_FENNEL],
    },
    {
      kind: 'mimic',
      label: 'Bolting',
      where: ['bo'],
      looks: 'A tall flower stalk comes up before the bulb swells.',
      why: 'Water stress, root damage, heat, long days, cold and transplant shock all set it to flower.',
      fix: 'Sow where it is to grow or in modules planted out small, sow a bolt-resistant variety in early summer rather than spring, and keep it watered.',
      sources: [USU_FENNEL, RHS_FENNEL],
    },
    {
      kind: 'excess',
      nutrient: 'N',
      label: 'Too much nitrogen',
      where: ['ha', 'st'],
      looks: 'Lush leaf over a small bulb.',
      why: 'Fennel wants moderate nitrogen.',
      fix: 'Feed the soil with compost the season before rather than rich manure at planting.',
      sources: [USU_FENNEL],
    },
    {
      kind: 'ph',
      label: 'Heavy, wet or acid soil',
      where: ['st', 'ro', 'ha'],
      looks: 'Slow plants and small bulbs.',
      why: 'Fennel dislikes clay and waterlogging, and grows best at pH 6.5 to 8.',
      fix: 'Grow it in a light, free-draining bed, open heavy soil with compost, and test the pH before sowing.',
      sources: [USU_FENNEL, RHS_FENNEL],
    },
    {
      kind: 'mimic',
      label: 'The wrong fennel, or summer heat',
      where: ['ha'],
      looks: 'Plants that never make a bulb at all.',
      why: 'Common fennel, grown for leaf and seed, makes no bulb; Florence fennel does. Summer heat also stops the bulb forming.',
      fix: 'Sow a Florence fennel variety, and time it so the bulb swells in cool weather.',
      sources: [USU_FENNEL, UF_FENNEL],
    },
    {
      kind: 'mimic',
      label: 'Aphids, thrips, caterpillars and slugs',
      where: ['ho', 'cu', 'st'],
      looks: 'Insects clustered in the leaves, caterpillars, or slime trails, with smaller bulbs.',
      fix: 'Rub off or wash off aphids, hand pick caterpillars, lift slugs on damp evenings, and let a few plants flower nearby to draw hoverflies and wasps.',
      sources: [USU_FENNEL, RHS_FENNEL],
    },
    {
      kind: 'mimic',
      label: 'Seed not coming up',
      where: ['ot'],
      looks: 'Few seedlings or none.',
      why: 'Fennel comes up in 7 to 10 days in soil of 50 to 75°F.',
      fix: 'Wait for the soil to warm, sow shallowly and keep the surface moist until they come up.',
      sources: [USU_FENNEL],
    },
  ],
  tomatillo: [
    {
      kind: 'mimic',
      label: 'Empty husks from one plant alone',
      where: ['ha', 'fl'],
      looks: 'Husks that swell but stay empty, or very few fruit.',
      why: 'Tomatillos are not self-fertile, so one plant alone sets little. Extreme heat and dry weather also leave husks empty.',
      fix: 'Grow at least two or three plants together, leave flowers nearby for the bees, and keep the soil moist in hot weather.',
      sources: [USU_TOMATILLO, UF_TOMATILLO],
    },
    {
      kind: 'excess',
      nutrient: 'N',
      label: 'Too much feeding',
      where: ['fl', 'st'],
      looks: 'Big, leafy plants that are slow to fruit.',
      fix: 'Feed the soil with compost worked in before planting, and add nothing more once the plants are growing well.',
      sources: [USU_TOMATILLO],
    },
    {
      kind: 'ph',
      label: 'Soil pH off',
      where: ['st', 'yn'],
      looks: 'Slow plants that feeding does not help.',
      fix: 'Test the soil and bring it to pH 6.0 to 7.0 by the result.',
      sources: [NCSU_TOMATILLO],
    },
    {
      kind: 'water',
      label: 'Root rot from too much water',
      where: ['wi', 'ro', 'st'],
      looks: 'Plants that grow poorly and wilt even when the soil is wet.',
      why: 'Tomatillos are fairly drought tolerant, and too much water rots the roots.',
      fix: 'Water deeply and seldom, letting the top of the soil dry, and grow them on a bed that drains.',
      sources: [USU_TOMATILLO],
    },
    {
      kind: 'mimic',
      label: 'Viruses',
      where: ['cu', 'yn', 'st'],
      looks: 'Light green, mottled, misshapen and curled leaves on stunted plants.',
      why: 'Spread by aphids and leafhoppers.',
      fix: 'Pull and bin plants that show it, keep weeds down around the bed, and rotate away from tomatoes, peppers and other nightshades.',
      sources: [USU_TOMATILLO, NCSU_TOMATILLO, UF_TOMATILLO],
    },
    {
      kind: 'mimic',
      label: 'Powdery mildew',
      where: ['sp'],
      looks: 'White powdery patches that start on the older leaves.',
      fix: 'Space and stake the plants for air and pick off the worst leaves.',
      sources: [USU_TOMATILLO],
    },
    {
      kind: 'mimic',
      label: 'Beetles, fruitworms and aphids',
      where: ['ho', 'cu', 'ha'],
      looks: 'Tiny holes from flea beetles, leaves stripped by striped beetles, holes bored into the fruit, or leaves curled by aphids.',
      fix: 'Hand pick beetles and fruitworms, cover young plants with netting, and leave flowering herbs nearby for the insects that hunt them.',
      sources: [USU_TOMATILLO, NCSU_TOMATILLO, UF_TOMATILLO],
    },
  ],
  cowpea: [
    {
      kind: 'excess',
      nutrient: 'N',
      label: 'Too much nitrogen',
      where: ['fl', 'ha'],
      looks: 'Long, leafy vines with few pods and poor seed.',
      why: 'Cowpeas make nitrogen for themselves; nitrogen left in the soil from a heavily fed crop before makes vines instead of peas.',
      fix: 'Grow cowpeas after a crop that was not heavily fed, and add no manure or nitrogen for them.',
      sources: [CLEMSON_SOUTHERN_PEAS],
    },
    {
      kind: 'short',
      nutrient: 'N',
      label: 'Missing nodule bacteria',
      where: ['yo', 'st'],
      looks: 'Pale, slow plants in a bed new to cowpeas.',
      fix: 'Use a cowpea inoculant at sowing where cowpeas have not grown before.',
      sources: [CLEMSON_SOUTHERN_PEAS],
    },
    {
      kind: 'ph',
      label: 'Soil pH off',
      where: ['st', 'yo'],
      looks: 'Slow plants that feeding does not help.',
      fix: 'Test the soil and bring it to pH 5.8 to 6.3 by the result.',
      sources: [CLEMSON_SOUTHERN_PEAS],
    },
    {
      kind: 'water',
      label: 'Cold, heavy or wet soil',
      where: ['ro', 'st', 'ot'],
      looks: 'Poor emergence and small plants.',
      why: 'Seed in soil below 60°F sits and is taken by pests and disease, and cowpeas do poorly in heavy, wet soil.',
      fix: 'Wait until the soil is above 60°F, and grow on a light, well-drained bed or open heavy soil with compost.',
      sources: [CLEMSON_SOUTHERN_PEAS, UF_SOUTHERN_PEAS],
    },
    {
      kind: 'mimic',
      label: 'Cut-out after the first pods',
      where: ['yo', 'fl', 'st'],
      looks: 'Plants that set a first flush of pods and then yellow and stop.',
      why: 'Worse with compacted soil and with too much or too little water.',
      fix: 'Loosen the soil with compost before sowing, and keep it evenly moist without soaking it.',
      sources: [UC_CUTOUT],
    },
    {
      kind: 'mimic',
      label: 'Fusarium wilt',
      where: ['yo', 'wi'],
      looks: 'Plants that yellow widely, set few pods and die. Scrape the stem a few inches above the soil and it is discoloured inside.',
      fix: 'Grow a resistant variety and rotate cowpeas around the garden, keeping them out of a bed where it showed.',
      sources: [UC_FUSARIUM, CLEMSON_SOUTHERN_PEAS],
    },
    {
      kind: 'mimic',
      label: 'Root knot nematodes',
      where: ['st', 'wi', 'ro'],
      looks: 'Stunted plants that wilt in the heat, with lumpy swellings on the roots.',
      fix: 'Grow a resistant variety, rotate, and build the soil with compost, which feeds the living things that keep nematodes down.',
      sources: [UC_NEMATODES, CLEMSON_SOUTHERN_PEAS],
    },
    {
      kind: 'mimic',
      label: 'Southern stem blight',
      where: ['ro', 'wi'],
      looks: 'A plant that wilts, with white mould around the stem at the soil.',
      fix: 'Keep old plant matter away from the stems, compost the old crop, and rotate the bed.',
      sources: [CLEMSON_SOUTHERN_PEAS],
    },
    {
      kind: 'mimic',
      label: 'Curculio, stink bugs and aphids',
      where: ['ha', 'ho', 'cu'],
      looks: 'Pods with small dark marks and grubs in the peas, shrivelled peas, or clusters of small insects on the tips.',
      why: 'Aphids also spread viruses among cowpeas.',
      fix: 'Pick often and pick up fallen pods, hand pick stink bugs, wash off aphids, and leave flowers nearby for the insects that hunt them.',
      sources: [CLEMSON_SOUTHERN_PEAS],
    },
  ],
};

const legumeConfirm = 'Confirm with a soil test for pH and nutrients, and a leaf test from a lab if needed. Pull a plant and cut a nodule open: pink inside means the bacteria are at work.';

export const NEW_CROP_SIGN_CONFIRM: Record<string, CropConfirm> = {
  peach: { text: 'Confirm with a soil test for pH and nutrients before planting, and a leaf test from a lab in midsummer if the tree keeps struggling.', sources: [USU_PEACH, CLEMSON_PEACH] },
  drybeans: { text: legumeConfirm, sources: [UC_DRY_NUTRIENT, UC_NEMATODES, NEV_DRY_BEAN] },
  chickpea: { text: legumeConfirm, sources: [ARS_COMPENDIUM] },
  lentil: { text: legumeConfirm, sources: [ARS_COMPENDIUM, MB_LENTIL] },
  soybean: { text: legumeConfirm, sources: [KSU_SOY, NCSU_SOY] },
  peanut: { text: 'Confirm with a soil test for pH and calcium before sowing, and dig a plant to check the pods are filling.', sources: [CLEMSON_PEANUT] },
  ginger: { text: 'Confirm with a soil test for pH, and lift a rhizome to check it is firm rather than soft.', sources: [NCSU_GINGER_TURMERIC, VT_GINGER] },
  turmeric: { text: 'Confirm with a soil test for pH, and lift a rhizome to check it is firm rather than soft.', sources: [NCSU_GINGER_TURMERIC, UF_TURMERIC] },
  collards: { text: 'Confirm with a soil test for pH and nutrients, and a leaf test from a lab if needed.', sources: [CLEMSON_COLLARDS] },
  mustardgreens: { text: 'Confirm with a soil test for pH and nutrients, and a leaf test from a lab if needed.', sources: [SASK_MUSTARD_N, FSA_MUSTARD] },
  fennel: { text: 'Confirm with a soil test for pH and nutrients, and a leaf test from a lab if needed.', sources: [USU_FENNEL] },
  tomatillo: { text: 'Confirm with a soil test for pH and nutrients, and a leaf test from a lab if needed.', sources: [NCSU_TOMATILLO, USU_TOMATILLO] },
  cowpea: { text: legumeConfirm, sources: [CLEMSON_SOUTHERN_PEAS] },
};
