// How to grow each crop: the soil it wants, how to sow and space it, when
// it is ready, and the shortages and disorders it is known for, with every
// guide pointing out to the advisory service it stands on and to PubMed.
//
// 2026-09-26, direct request: "In the Garden tab, there needs to be
// information about how to grow each thing, what type of soil it likes,
// what deficiencies of nutrients look like and how to fix it based on
// real world gardening advice they can be pointed to, like PubMed,
// outside of the device."
//
// Where the words come from. The how-to is the kind of guidance the Royal
// Horticultural Society and the University of Florida's IFAS extension
// service publish, the first for temperate gardens and the second for
// warm and tropical ones, since the app is not only for cold climates.
// Each guide links to that service's page for the crop, every link
// checked by scripts/test_crop_guides.js. The figures (pH, spacing, days)
// are the ranges those services commonly give; the linked page carries
// the detail for a particular climate, and the in-app help says so.
// PubMed is linked as a search on the crop's Latin name, which shows the
// research for anyone who wants depth and always resolves.
//
// A planting in Garden > Plots & Plantings is matched to its guide by the
// food name it was saved under (findCropGuide), so "Tomatoes, cherry
// tomatoes, fruit" and "Tomato" both open the tomato guide. Longest alias
// wins, so "Squash, zucchini" is a courgette before it is a squash.
//
// Pure data and two lookups, no React, checked without a phone.

import { pubmedSearchUrl, type GuideSource, type PlantNutrientKey } from './plantNutrients';

export type CropGroup = 'vegetables' | 'herbs' | 'fruit' | 'warm';

export const CROP_GROUP_LABELS: Record<CropGroup, string> = {
  vegetables: 'Vegetables',
  herbs: 'Herbs',
  fruit: 'Fruit',
  warm: 'Warm Climate and Tropical',
};

export type CropWatchFor = {
  // The nutrient behind it, when there is one, so the row can open that
  // nutrient's whole account. A disorder with no nutrient (clubroot,
  // bolting) leaves it out.
  nutrient?: PlantNutrientKey;
  label: string;
  note: string;
};

export type CropGuide = {
  key: string;
  name: string;
  // Lower-case words a saved food name starts with. Punctuation is ignored.
  aliases: string[];
  latin: string;
  family: string;
  group: CropGroup;
  season: 'cool' | 'warm' | 'perennial';
  sun: string;
  soil: string;
  ph: [number, number];
  feeding: 'light' | 'moderate' | 'heavy';
  sow: string;
  spacing: string;
  ready: string;
  water: string;
  grow: string;
  watchFor: CropWatchFor[];
  sources: GuideSource[];
};

const rhs = (kind: 'vegetables' | 'fruit' | 'herbs', slug: string, label: string): GuideSource => ({
  label: `RHS: ${label}`,
  url: `https://www.rhs.org.uk/${kind}/${slug}/grow-your-own`,
});
const edis = (id: string, label: string): GuideSource => ({
  label: `University of Florida IFAS: ${label}`,
  url: `https://edis.ifas.ufl.edu/publication/${id}`,
});
const FLORIDA_VEG = edis('VH021', 'Florida Vegetable Gardening Guide');
const TROPICAL_FRUIT = edis('MG373', 'Tropical and subtropical fruit crops');

// The shared disorders, written once so the same thing is said the same
// way on every crop that has it.
const BLOSSOM_END_ROT: CropWatchFor = {
  nutrient: 'Ca',
  label: 'Blossom-end rot',
  note: 'A sunken dark patch at the flower end of the fruit. Calcium that did not reach the fruit because watering was uneven; steady deep watering and mulch fix it, extra calcium usually does not.',
};
const MG_FROM_POTASH: CropWatchFor = {
  nutrient: 'Mg',
  label: 'Yellowing between the veins of older leaves',
  note: 'Magnesium shortage, often brought on by heavy high-potash feeding. Ease off the potash and water Epsom salts onto the soil.',
};
const CLUBROOT: CropWatchFor = {
  label: 'Clubroot',
  note: 'Swollen, distorted roots and plants that wilt on warm days. A soil-borne disease that thrives in acid, wet soil and persists for many years; liming to about pH 7 and good drainage hold it back, and it is not a nutrient shortage.',
};
const BRASSICA_BORON: CropWatchFor = {
  nutrient: 'B',
  label: 'Hollow or cracked stems',
  note: 'Boron shortage, worst on light soils after dry spells or over-liming.',
};
const WHIPTAIL: CropWatchFor = {
  nutrient: 'Mo',
  label: 'Whiptail',
  note: 'New leaves narrowed to little more than the midrib. Molybdenum locked away by acid soil; lime to around pH 6.5.',
};
const TIPBURN: CropWatchFor = {
  nutrient: 'Ca',
  label: 'Tipburn',
  note: 'Browned edges on the inner leaves. Calcium not reaching fast-growing leaves in heat or uneven watering; keep the soil evenly moist.',
};
const IRON_ON_ALKALINE: CropWatchFor = {
  nutrient: 'Fe',
  label: 'Yellow young leaves with green veins',
  note: 'Iron locked away by an alkaline or chalky soil, or hard tap water. Lower the pH, grow it in a container of ericaceous compost, or water with rainwater; chelated iron treats the symptom.',
};
const PALE_OLD_LEAVES: CropWatchFor = {
  nutrient: 'N',
  label: 'Pale old leaves, slow growth',
  note: 'Nitrogen shortage. Compost, a nettle or comfrey feed, or a general fertiliser.',
};
const POTASH_SCORCH: CropWatchFor = {
  nutrient: 'K',
  label: 'Brown, crisp leaf edges',
  note: 'Potassium shortage, common on light soils. Comfrey feed, or sulphate of potash.',
};
const ZINC_LITTLE_LEAF: CropWatchFor = {
  nutrient: 'Zn',
  label: 'Small bunched new leaves',
  note: 'Zinc shortage, usual on alkaline or limestone soils. A zinc foliar spray after a soil test.',
};
const MN_ALKALINE: CropWatchFor = {
  nutrient: 'Mn',
  label: 'Speckled yellow young leaves',
  note: 'Manganese locked away by alkaline or over-limed soil.',
};

export const CROP_GUIDES: CropGuide[] = [
  // ---------------------------------------------------------------- Vegetables
  {
    key: 'tomato',
    name: 'Tomatoes',
    aliases: ['tomato', 'tomatoes'],
    latin: 'Solanum lycopersicum',
    family: 'Nightshade family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun, at least 6 to 8 hours a day.',
    soil: 'Deep, fertile, well-drained soil with plenty of compost worked in.',
    ph: [6.0, 6.8],
    feeding: 'heavy',
    sow: 'Sow indoors 6 to 8 weeks before the last frost and plant out once nights stay above about 10°C. Plant deeper than they grew in the pot; the buried stem roots.',
    spacing: '45 to 60 cm apart; bush kinds need more room than cordons.',
    ready: 'About 60 to 85 days from planting out, depending on kind.',
    water: 'Deeply and evenly, at the soil rather than on the leaves. Uneven watering causes split fruit and blossom-end rot.',
    grow: 'Stake or cage cordon kinds and pinch out the side shoots that form where a leaf meets the stem. Mulch once the soil is warm. Change to a high-potash feed when the first fruits set. Basil and marigolds grown alongside draw in the pollinators and predators that keep pests down.',
    watchFor: [
      BLOSSOM_END_ROT,
      MG_FROM_POTASH,
      { nutrient: 'K', label: 'Blotchy ripening', note: 'Hard green or yellow patches on ripe fruit. Potassium shortage, or fruit overheated in strong sun.' },
      { nutrient: 'P', label: 'Purple seedlings', note: 'Usually cold soil rather than a shortage; they green up as it warms.' },
    ],
    sources: [rhs('vegetables', 'tomatoes', 'Tomatoes'), FLORIDA_VEG],
  },
  {
    key: 'pepper',
    name: 'Peppers and Chillies',
    aliases: ['pepper', 'peppers', 'chilli', 'chili', 'chile', 'jalapeno', 'serrano', 'capsicum', 'bell pepper', 'pepper hot', 'peppers hot', 'peppers sweet'],
    latin: 'Capsicum annuum',
    family: 'Nightshade family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun and warmth; they stall below about 15°C.',
    soil: 'Fertile, well-drained soil rich in compost.',
    ph: [6.0, 6.8],
    feeding: 'moderate',
    sow: 'Sow indoors 8 to 10 weeks before the last frost, in warmth (about 21°C). Plant out when the soil is warm.',
    spacing: '45 cm apart.',
    ready: 'About 60 to 90 days from planting out for green fruit, longer for fully coloured.',
    water: 'Evenly. Dry spells drop flowers and cause blossom-end rot.',
    grow: 'Stake tall kinds. Too much nitrogen gives leaves and few fruit. Hot kinds grow as short-lived perennials in frost-free climates.',
    watchFor: [BLOSSOM_END_ROT, MG_FROM_POTASH],
    sources: [rhs('vegetables', 'peppers', 'Peppers'), FLORIDA_VEG],
  },
  {
    key: 'aubergine',
    name: 'Aubergines (Eggplant)',
    aliases: ['aubergine', 'aubergines', 'eggplant', 'eggplants', 'brinjal'],
    latin: 'Solanum melongena',
    family: 'Nightshade family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun and heat; the warmest spot in the garden.',
    soil: 'Fertile, well-drained soil rich in organic matter.',
    ph: [5.5, 6.8],
    feeding: 'heavy',
    sow: 'Sow indoors in warmth 8 to 10 weeks before the last frost; plant out only when nights are warm.',
    spacing: '60 cm apart.',
    ready: 'About 70 to 85 days from planting out, while the skin is still glossy.',
    water: 'Evenly and generously.',
    grow: 'Stake the plants. In a short season, limit each plant to five or six fruits so they ripen.',
    watchFor: [MG_FROM_POTASH, POTASH_SCORCH],
    sources: [rhs('vegetables', 'aubergines', 'Aubergines'), FLORIDA_VEG],
  },
  {
    key: 'potato',
    name: 'Potatoes',
    aliases: ['potato', 'potatoes'],
    latin: 'Solanum tuberosum',
    family: 'Nightshade family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Deep, loose, fertile soil. Dug-in compost or rotted manure the autumn before suits them.',
    ph: [5.0, 6.5],
    feeding: 'heavy',
    sow: 'Plant seed potatoes (sprouted first in light, if you like) 10 to 15 cm deep from early spring. In warm climates, grow them in the coolest months.',
    spacing: '30 cm apart for earlies, 38 cm for maincrop, rows 60 to 75 cm apart.',
    ready: 'Earlies about 10 to 12 weeks after planting, maincrop 15 to 20 weeks.',
    water: 'Steadily once tubers are forming, which is around flowering.',
    grow: 'Draw soil up around the stems as they grow (earthing up) so no tuber sees light; green potatoes are toxic. Do not lime before potatoes. Rotate beds to keep blight and pests from building up.',
    watchFor: [
      { label: 'Common scab', note: 'Rough corky patches on the skin. Worse in dry, alkaline or freshly limed soil; water through tuber formation and do not lime. Not a nutrient shortage.' },
      MG_FROM_POTASH,
      POTASH_SCORCH,
    ],
    sources: [rhs('vegetables', 'potatoes', 'Potatoes'), edis('HS183', 'Potato production')],
  },
  {
    key: 'lettuce',
    name: 'Lettuce',
    aliases: ['lettuce'],
    latin: 'Lactuca sativa',
    family: 'Daisy family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun in cool weather, light shade in heat.',
    soil: 'Moisture-retentive soil with plenty of organic matter.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow a short row every two or three weeks for a steady supply. Seed may not germinate above about 25°C, so sow in the evening or in shade in hot weather.',
    spacing: '15 cm for loose-leaf, 30 cm for hearting kinds.',
    ready: 'Loose-leaf in about 30 days, hearting kinds in 60 to 80.',
    water: 'Little and often; dry soil makes lettuce bitter and quick to run to seed.',
    grow: 'Heat and long days make it bolt (run to seed). In hot climates it is a cool-season crop.',
    watchFor: [TIPBURN, PALE_OLD_LEAVES],
    sources: [rhs('vegetables', 'lettuce', 'Lettuce'), FLORIDA_VEG],
  },
  {
    key: 'spinach',
    name: 'Spinach',
    aliases: ['spinach'],
    latin: 'Spinacia oleracea',
    family: 'Amaranth family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or part shade.',
    soil: 'Fertile, moisture-retentive soil. It does poorly in acid soil.',
    ph: [6.5, 7.5],
    feeding: 'moderate',
    sow: 'Sow direct in spring and late summer. Long days and heat make it bolt.',
    spacing: '7 to 15 cm apart.',
    ready: 'About 40 to 50 days.',
    water: 'Keep evenly moist.',
    grow: 'In hot weather, Malabar spinach or chard are easier leafy greens.',
    watchFor: [PALE_OLD_LEAVES, MN_ALKALINE],
    sources: [rhs('vegetables', 'spinach', 'Spinach')],
  },
  {
    key: 'chard',
    name: 'Chard',
    aliases: ['chard', 'swiss chard', 'silverbeet', 'leaf beet'],
    latin: 'Beta vulgaris subsp. vulgaris',
    family: 'Amaranth family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or part shade.',
    soil: 'Fertile soil with compost worked in.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Sow direct from spring to late summer.',
    spacing: '30 to 40 cm apart.',
    ready: 'About 50 to 60 days, then picked leaf by leaf for months.',
    water: 'Keep evenly moist.',
    grow: 'Takes heat far better than spinach. Pick outer leaves and let the centre keep growing.',
    watchFor: [MN_ALKALINE, { nutrient: 'B', label: 'Cracked stalks', note: 'Boron shortage on light soils.' }],
    sources: [rhs('vegetables', 'chard', 'Chard')],
  },
  {
    key: 'kale',
    name: 'Kale',
    aliases: ['kale'],
    latin: 'Brassica oleracea (Acephala group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or light shade.',
    soil: 'Firm, fertile soil; brassicas grow poorly in loose, freshly dug ground.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Sow in spring, transplant in early summer for autumn and winter picking.',
    spacing: '45 to 60 cm apart.',
    ready: 'About 55 to 75 days, then picked for months.',
    water: 'Keep moist, especially when young.',
    grow: 'The hardiest brassica; frost sweetens the leaves. Net against cabbage white caterpillars and pigeons.',
    watchFor: [CLUBROOT, MG_FROM_POTASH, BRASSICA_BORON],
    sources: [rhs('vegetables', 'kale', 'Kale')],
  },
  {
    key: 'cabbage',
    name: 'Cabbages',
    aliases: ['cabbage', 'cabbages'],
    latin: 'Brassica oleracea (Capitata group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Firm, fertile, moisture-retentive soil.',
    ph: [6.5, 7.5],
    feeding: 'heavy',
    sow: 'Sow in modules and transplant; timings vary by kind (spring, summer, autumn, winter cabbages).',
    spacing: '35 to 50 cm apart.',
    ready: 'About 70 to 120 days depending on kind.',
    water: 'Keep evenly moist; a heavy watering after drought splits heads.',
    grow: 'Plant firmly and deeply. Net against caterpillars and birds. Rotate brassicas to a new bed each year.',
    watchFor: [CLUBROOT, TIPBURN, WHIPTAIL, BRASSICA_BORON],
    sources: [rhs('vegetables', 'cabbages', 'Cabbages')],
  },
  {
    key: 'broccoli',
    name: 'Broccoli and Calabrese',
    aliases: ['broccoli', 'calabrese', 'broccolini'],
    latin: 'Brassica oleracea (Italica group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Firm, fertile soil.',
    ph: [6.5, 7.5],
    feeding: 'heavy',
    sow: 'Calabrese is sown in spring for summer heads; sprouting broccoli is sown in spring for the following spring.',
    spacing: '30 cm for calabrese, 60 cm for sprouting broccoli.',
    ready: 'Calabrese in about 60 to 90 days; cut before the flower buds open.',
    water: 'Keep moist; dry spells make heads small and early.',
    grow: 'Cutting the main head brings on side shoots for weeks.',
    watchFor: [BRASSICA_BORON, WHIPTAIL, CLUBROOT],
    sources: [rhs('vegetables', 'broccoli', 'Broccoli')],
  },
  {
    key: 'cauliflower',
    name: 'Cauliflowers',
    aliases: ['cauliflower', 'cauliflowers'],
    latin: 'Brassica oleracea (Botrytis group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Deep, firm, fertile soil that holds moisture.',
    ph: [6.5, 7.5],
    feeding: 'heavy',
    sow: 'Sow in modules and transplant without disturbing roots; any check in growth makes small, early heads (buttoning).',
    spacing: '50 to 60 cm apart.',
    ready: 'About 60 to 100 days from planting out.',
    water: 'Steady moisture throughout.',
    grow: 'The most demanding brassica. Fold leaves over a forming head to keep it white in sun.',
    watchFor: [WHIPTAIL, BRASSICA_BORON, CLUBROOT],
    sources: [rhs('vegetables', 'cauliflower', 'Cauliflowers')],
  },
  {
    key: 'brussels',
    name: 'Brussels Sprouts',
    aliases: ['brussels sprouts', 'brussels sprout', 'brussel sprouts'],
    latin: 'Brassica oleracea (Gemmifera group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Very firm, fertile soil; loose soil gives loose, open sprouts.',
    ph: [6.5, 7.5],
    feeding: 'heavy',
    sow: 'Sow in spring and transplant in early summer.',
    spacing: '60 cm apart.',
    ready: 'From about 90 days, picked from the bottom up through autumn and winter.',
    water: 'Keep moist through summer.',
    grow: 'Stake tall plants in windy gardens. Too much nitrogen also gives open sprouts.',
    watchFor: [BRASSICA_BORON, MG_FROM_POTASH, WHIPTAIL],
    sources: [rhs('vegetables', 'brussels-sprouts', 'Brussels sprouts')],
  },
  {
    key: 'kohlrabi',
    name: 'Kohlrabi',
    aliases: ['kohlrabi', 'kohl rabi'],
    latin: 'Brassica oleracea (Gongylodes group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Fertile, moisture-retentive soil.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Sow direct little and often from spring to late summer.',
    spacing: '15 to 25 cm apart.',
    ready: 'About 45 to 60 days, when the swollen stem is the size of a tennis ball.',
    water: 'Steady moisture keeps it tender.',
    grow: 'Faster and more heat-tolerant than most brassicas.',
    watchFor: [BRASSICA_BORON, CLUBROOT],
    sources: [rhs('vegetables', 'kohl-rabi', 'Kohl rabi')],
  },
  {
    key: 'pakchoi',
    name: 'Pak Choi',
    aliases: ['pak choi', 'bok choy', 'bok choi', 'pak choy', 'chinese cabbage'],
    latin: 'Brassica rapa (Chinensis group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or light shade.',
    soil: 'Fertile, moisture-retentive soil.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Sow direct from midsummer; spring sowings bolt as days lengthen.',
    spacing: '15 to 30 cm apart.',
    ready: 'About 30 to 45 days.',
    water: 'Keep moist; dry soil makes it bolt.',
    grow: 'Cut whole heads, or pick leaves young.',
    watchFor: [TIPBURN, BRASSICA_BORON],
    sources: [rhs('vegetables', 'pak-choi', 'Pak choi')],
  },
  {
    key: 'rocket',
    name: 'Rocket (Arugula)',
    aliases: ['rocket', 'arugula', 'roquette'],
    latin: 'Eruca vesicaria',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun, or part shade in summer.',
    soil: 'Most soils that hold some moisture.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Sow direct little and often from spring to autumn.',
    spacing: '15 cm apart, or sown thickly and cut as young leaves.',
    ready: 'About 21 to 40 days.',
    water: 'Keep moist; heat and dry soil make it hot and quick to flower.',
    grow: 'The flowers are edible and loved by bees.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('vegetables', 'rocket', 'Rocket')],
  },
  {
    key: 'carrot',
    name: 'Carrots',
    aliases: ['carrot', 'carrots'],
    latin: 'Daucus carota subsp. sativus',
    family: 'Carrot family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Deep, loose, stone-free soil. Fresh manure and stones make roots fork.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Sow direct, thinly, from spring to summer; they do not transplant.',
    spacing: 'Thin to 5 to 7 cm apart, rows 15 to 30 cm apart.',
    ready: 'About 70 to 80 days, earlier for baby carrots.',
    water: 'Evenly; heavy watering after drought splits roots.',
    grow: 'Carrot fly finds carrots by scent, so thin in the evening and cover with fine mesh, or grow them among onions or in a raised bed. Grow in deep containers on heavy clay.',
    watchFor: [
      { label: 'Forked roots', note: 'Stones, compacted soil or fresh manure. Not a nutrient shortage.' },
      { nutrient: 'Ca', label: 'Cavity spot', note: 'Small sunken lesions on the root, linked with soil conditions and calcium; rotate and avoid waterlogging.' },
    ],
    sources: [rhs('vegetables', 'carrots', 'Carrots')],
  },
  {
    key: 'beetroot',
    name: 'Beetroot',
    aliases: ['beetroot', 'beet', 'beets'],
    latin: 'Beta vulgaris',
    family: 'Amaranth family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Well-drained, fertile soil. Poor in acid soil.',
    ph: [6.5, 7.5],
    feeding: 'moderate',
    sow: 'Sow direct from spring to midsummer. Each seed is a cluster, so thin to one seedling.',
    spacing: '10 cm apart.',
    ready: 'About 55 to 70 days; the leaves are edible too.',
    water: 'Evenly; dry spells make roots woody.',
    grow: 'Pull when golf-ball to tennis-ball size for tender roots.',
    watchFor: [
      { nutrient: 'B', label: 'Black patches inside the root', note: 'Boron shortage (heart rot), on light or over-limed soils.' },
      MN_ALKALINE,
    ],
    sources: [rhs('vegetables', 'beetroot', 'Beetroot')],
  },
  {
    key: 'radish',
    name: 'Radishes',
    aliases: ['radish', 'radishes', 'daikon'],
    latin: 'Raphanus sativus',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or light shade.',
    soil: 'Light, moisture-retentive soil.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Sow direct every two weeks; the quickest crop there is.',
    spacing: '2 to 5 cm apart; winter radishes and daikon 15 cm.',
    ready: 'About 25 to 30 days for summer radishes.',
    water: 'Keep moist; heat and dry soil make them hot, pithy and quick to bolt.',
    grow: 'Useful sown alongside slow carrots and parsnips to mark the row.',
    watchFor: [BRASSICA_BORON],
    sources: [rhs('vegetables', 'radishes', 'Radishes')],
  },
  {
    key: 'turnip',
    name: 'Turnips',
    aliases: ['turnip', 'turnips', 'swede', 'rutabaga'],
    latin: 'Brassica rapa (Rapifera group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or light shade.',
    soil: 'Fertile, moisture-retentive soil.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Sow direct from spring to late summer.',
    spacing: '15 to 23 cm apart.',
    ready: 'About 40 to 60 days; the tops are edible greens.',
    water: 'Keep moist.',
    grow: 'Pull young for tenderness.',
    watchFor: [
      { nutrient: 'B', label: 'Brown heart', note: 'Brown, watery flesh inside the root. Boron shortage on light soils.' },
      CLUBROOT,
    ],
    sources: [rhs('vegetables', 'turnips', 'Turnips')],
  },
  {
    key: 'parsnip',
    name: 'Parsnips',
    aliases: ['parsnip', 'parsnips'],
    latin: 'Pastinaca sativa',
    family: 'Carrot family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Deep, stone-free soil.',
    ph: [6.5, 7.0],
    feeding: 'light',
    sow: 'Sow fresh seed direct in spring; old seed germinates poorly, and slowly even when fresh.',
    spacing: '15 cm apart.',
    ready: 'About 120 days or more; frost sweetens them.',
    water: 'Steady moisture.',
    grow: 'The sap can blister skin in sunlight, so wear gloves handling the leaves.',
    watchFor: [{ label: 'Canker', note: 'Orange-brown rot on the shoulder of the root. A disease worse in acid, damaged or fresh-manured soil; resistant kinds help. Not a nutrient shortage.' }],
    sources: [rhs('vegetables', 'parsnips', 'Parsnips')],
  },
  {
    key: 'onion',
    name: 'Onions',
    aliases: ['onion', 'onions', 'scallion', 'scallions', 'spring onion', 'spring onions', 'green onion', 'green onions'],
    latin: 'Allium cepa',
    family: 'Onion family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Firm, well-drained soil with compost worked in the season before.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Plant sets in spring or autumn, or sow seed. Bulbing is triggered by day length, so choose short-day kinds nearer the equator and long-day kinds far from it.',
    spacing: '5 to 10 cm apart, rows 30 cm apart.',
    ready: 'About 90 to 150 days; ready when the tops yellow and fall over.',
    water: 'Only in dry spells, and stop once bulbs swell.',
    grow: 'Weed carefully; onions cannot compete. Too much nitrogen late in the season delays bulbing and spoils storage.',
    watchFor: [{ label: 'White rot and downy mildew', note: 'Diseases, not shortages; rotate onions to a new bed each year.' }],
    sources: [rhs('vegetables', 'onions', 'Onions'), FLORIDA_VEG],
  },
  {
    key: 'shallot',
    name: 'Shallots',
    aliases: ['shallot', 'shallots'],
    latin: 'Allium cepa (Aggregatum group)',
    family: 'Onion family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Firm, well-drained soil.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Plant sets with the tip just showing, in late winter or early spring.',
    spacing: '15 to 20 cm apart.',
    ready: 'Midsummer, when the leaves yellow; each set becomes a cluster.',
    water: 'Only in long dry spells.',
    grow: 'Keep weeded, and dry the clusters in the sun before storing.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('vegetables', 'shallots', 'Shallots')],
  },
  {
    key: 'garlic',
    name: 'Garlic',
    aliases: ['garlic'],
    latin: 'Allium sativum',
    family: 'Onion family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Well-drained soil; it rots in wet clay.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Plant single cloves, tip up, in autumn. Most kinds need several weeks below about 10°C to form cloves; in warm climates, chill cloves in the fridge before planting.',
    spacing: '15 cm apart, 2 to 3 cm deep.',
    ready: 'The following summer, when the lower leaves yellow.',
    water: 'In dry spells in spring, then stop as leaves yellow.',
    grow: 'Snap off the flower stalks of hardneck kinds (the scapes are good to eat). Dry bulbs well before storing.',
    watchFor: [{ label: 'Rust', note: 'Orange spots on the leaves. A fungus, worse in humid weather and crowded or high-nitrogen plantings.' }],
    sources: [rhs('vegetables', 'garlic', 'Garlic')],
  },
  {
    key: 'leek',
    name: 'Leeks',
    aliases: ['leek', 'leeks'],
    latin: 'Allium ampeloprasum (Porrum group)',
    family: 'Onion family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Deep, fertile, moisture-retentive soil.',
    ph: [6.0, 7.5],
    feeding: 'heavy',
    sow: 'Sow in spring and transplant when pencil-thick into deep holes made with a dibber, watering them in without filling the hole.',
    spacing: '15 cm apart.',
    ready: 'About 120 to 150 days, and hardy enough to stand through winter.',
    water: 'Keep moist.',
    grow: 'Draw soil up the stems for longer white shanks.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('vegetables', 'leeks', 'Leeks')],
  },
  {
    key: 'peas',
    name: 'Peas',
    aliases: ['pea', 'peas', 'snow pea', 'snow peas', 'mangetout', 'sugar snap'],
    latin: 'Pisum sativum',
    family: 'Pea family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or light shade.',
    soil: 'Moisture-retentive soil with organic matter. No nitrogen feed needed.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Sow direct from early spring; in warm climates, in the cool season.',
    spacing: '5 to 8 cm apart in a wide drill, with support.',
    ready: 'About 60 to 70 days.',
    water: 'Once flowering starts, water well; that is when pods form.',
    grow: 'Bacteria in the root nodules fix nitrogen from the air, so after harvest cut the plants at soil level and leave the roots in for the next crop.',
    watchFor: [
      { nutrient: 'Mn', label: 'Marsh spot', note: 'A brown patch inside the seed. Manganese shortage on alkaline soil.' },
      { nutrient: 'Mo', label: 'Pale plants with few nodules', note: 'Molybdenum locked away in acid soil, which the nitrogen-fixing bacteria need.' },
    ],
    sources: [rhs('vegetables', 'peas', 'Peas')],
  },
  {
    key: 'greenbeans',
    name: 'Green Beans (French Beans)',
    aliases: ['green bean', 'green beans', 'french bean', 'french beans', 'bean green', 'beans snap', 'snap bean', 'snap beans', 'string beans', 'pole beans', 'bush beans', 'haricot'],
    latin: 'Phaseolus vulgaris',
    family: 'Pea family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun and shelter.',
    soil: 'Warm, well-drained soil with organic matter.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Sow direct once the soil is above about 12°C; seed rots in cold, wet soil.',
    spacing: '10 to 15 cm for bush kinds, 20 cm for climbers with support.',
    ready: 'About 50 to 65 days; pick often and young to keep them coming.',
    water: 'Well once flowering.',
    grow: 'Like peas, they fix nitrogen from the air. The same plant gives fresh pods, or dried beans if left to ripen.',
    watchFor: [MN_ALKALINE, ZINC_LITTLE_LEAF],
    sources: [rhs('vegetables', 'french-beans', 'French beans'), FLORIDA_VEG],
  },
  {
    key: 'runnerbeans',
    name: 'Runner Beans',
    aliases: ['runner bean', 'runner beans'],
    latin: 'Phaseolus coccineus',
    family: 'Pea family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun, out of strong wind.',
    soil: 'Deep, rich soil that holds moisture; a trench filled with compost the winter before suits them.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow direct after the last frost, or indoors a few weeks earlier.',
    spacing: '15 to 20 cm apart up tall supports.',
    ready: 'About 70 to 90 days.',
    water: 'Generously in dry weather; dry roots and hot nights make flowers drop without setting.',
    grow: 'The red flowers bring in bumblebees. Pick every few days.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('vegetables', 'runner-beans', 'Runner beans')],
  },
  {
    key: 'broadbeans',
    name: 'Broad Beans (Fava)',
    aliases: ['broad bean', 'broad beans', 'fava', 'fava beans', 'faba'],
    latin: 'Vicia faba',
    family: 'Pea family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Most well-drained soils.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Sow direct in autumn or early spring.',
    spacing: '20 cm apart.',
    ready: 'About 80 to 100 days from a spring sowing.',
    water: 'At flowering in dry spells.',
    grow: 'Pinch out the tips once the first pods set, which removes the blackfly that cluster there. People with G6PD deficiency should not eat them.',
    watchFor: [{ label: 'Chocolate spot', note: 'Brown spots on the leaves. A fungus, worse in damp, crowded plantings; space them well.' }, MN_ALKALINE],
    sources: [rhs('vegetables', 'broad-beans', 'Broad beans')],
  },
  {
    key: 'cucumber',
    name: 'Cucumbers',
    aliases: ['cucumber', 'cucumbers', 'gherkin'],
    latin: 'Cucumis sativus',
    family: 'Squash family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun and warmth.',
    soil: 'Rich, well-drained soil full of organic matter.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Sow indoors, one seed per pot on its edge, and plant out after the last frost.',
    spacing: '45 to 60 cm apart, trained up a trellis.',
    ready: 'About 50 to 70 days.',
    water: 'Steadily; stress makes the fruit bitter.',
    grow: 'Pick often and young. Outdoor kinds need bees to pollinate; all-female greenhouse kinds do not and go bitter if pollinated.',
    watchFor: [MG_FROM_POTASH, POTASH_SCORCH, PALE_OLD_LEAVES],
    sources: [rhs('vegetables', 'cucumbers', 'Cucumbers'), FLORIDA_VEG],
  },
  {
    key: 'courgette',
    name: 'Courgettes (Zucchini)',
    aliases: ['courgette', 'courgettes', 'zucchini', 'squash zucchini', 'squash summer', 'summer squash', 'marrow'],
    latin: 'Cucurbita pepo',
    family: 'Squash family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun.',
    soil: 'Rich soil, ideally a planting hole filled with compost.',
    ph: [6.0, 7.5],
    feeding: 'heavy',
    sow: 'Sow indoors or direct after the last frost.',
    spacing: '90 cm apart.',
    ready: 'About 45 to 55 days; pick at 10 to 15 cm.',
    water: 'Generously at the base.',
    grow: 'Small fruits that shrivel from the tip were not pollinated; there are more bees later in the season, or move pollen from a male flower by hand.',
    watchFor: [BLOSSOM_END_ROT, MG_FROM_POTASH, { label: 'Powdery mildew', note: 'White dust on the leaves late in the season. A fungus encouraged by dry roots; water the soil, not the leaves.' }],
    sources: [rhs('vegetables', 'courgettes', 'Courgettes'), FLORIDA_VEG],
  },
  {
    key: 'squash',
    name: 'Winter Squash and Pumpkins',
    aliases: ['squash', 'squash winter', 'winter squash', 'butternut', 'pumpkin', 'pumpkins', 'calabaza'],
    latin: 'Cucurbita maxima, C. moschata, C. pepo',
    family: 'Squash family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun.',
    soil: 'Very rich soil; they are often grown on the edge of a compost heap.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Sow indoors or direct after the last frost.',
    spacing: '90 to 150 cm apart; trailing kinds spread far.',
    ready: 'About 85 to 120 days; the stalk dries and the skin hardens so a fingernail cannot dent it.',
    water: 'Deeply at the base until fruits swell.',
    grow: 'Cure in the sun for a week or two after cutting for long storage. The Three Sisters (corn, beans and squash together) is the traditional way of growing them.',
    watchFor: [BLOSSOM_END_ROT, MG_FROM_POTASH],
    sources: [rhs('vegetables', 'squash', 'Squash'), rhs('vegetables', 'pumpkins', 'Pumpkins'), FLORIDA_VEG],
  },
  {
    key: 'sweetcorn',
    name: 'Sweetcorn',
    aliases: ['sweetcorn', 'sweet corn', 'corn', 'maize', 'elote'],
    latin: 'Zea mays',
    family: 'Grass family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun and shelter.',
    soil: 'Fertile, well-drained soil.',
    ph: [5.8, 7.0],
    feeding: 'heavy',
    sow: 'Sow after the last frost once the soil is warm, in a block rather than a row, since the wind carries pollen from plant to plant.',
    spacing: '35 to 45 cm apart each way.',
    ready: 'About 70 to 100 days; ready when the tassels at the cob tip turn brown and a pressed kernel shows milky juice.',
    water: 'Well at tasselling and while cobs fill.',
    grow: 'Keep sweet kinds apart from popcorn or field corn, which spoil their sweetness if they cross.',
    watchFor: [
      { nutrient: 'N', label: 'Yellow V down the midrib of lower leaves', note: 'Nitrogen shortage, the classic corn symptom.' },
      { nutrient: 'P', label: 'Purple leaves on young plants', note: 'Usually cold soil; phosphorus shortage if it lasts.' },
      { nutrient: 'Zn', label: 'Pale stripes either side of the midrib', note: 'Zinc shortage on alkaline soils.' },
      POTASH_SCORCH,
    ],
    sources: [rhs('vegetables', 'sweetcorn', 'Sweetcorn'), FLORIDA_VEG],
  },
  {
    key: 'celery',
    name: 'Celery',
    aliases: ['celery', 'celeriac'],
    latin: 'Apium graveolens',
    family: 'Carrot family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or light shade.',
    soil: 'Very rich, moisture-retentive soil.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Sow indoors on the surface (it needs light to germinate) 10 weeks before planting out.',
    spacing: '25 to 30 cm apart in a block.',
    ready: 'About 100 to 130 days.',
    water: 'Constantly moist; dry spells make stringy, bitter stems.',
    grow: 'Planting in a block shades the stems and keeps them pale and tender.',
    watchFor: [
      { nutrient: 'B', label: 'Stems cracked across', note: 'Boron shortage.' },
      { nutrient: 'Ca', label: 'Blackheart', note: 'The heart leaves brown and rot. Calcium not reaching them; steady watering.' },
      MG_FROM_POTASH,
    ],
    sources: [rhs('vegetables', 'celery', 'Celery')],
  },
  {
    key: 'asparagus',
    name: 'Asparagus',
    aliases: ['asparagus'],
    latin: 'Asparagus officinalis',
    family: 'Asparagus family',
    group: 'vegetables',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained soil cleared of perennial weeds; a bed lasts 20 years.',
    ph: [6.5, 7.5],
    feeding: 'moderate',
    sow: 'Plant one-year-old crowns in spring, spread over a ridge of soil in a trench.',
    spacing: '30 to 45 cm apart.',
    ready: 'Cut nothing the first two years, lightly in the third, then for six to eight weeks each spring.',
    water: 'In dry spells while establishing.',
    grow: 'Let the ferny growth stand after harvest to feed the crowns, and mulch with compost each spring.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('vegetables', 'asparagus', 'Asparagus')],
  },
  {
    key: 'rhubarb',
    name: 'Rhubarb',
    aliases: ['rhubarb'],
    latin: 'Rheum × hybridum',
    family: 'Dock family',
    group: 'vegetables',
    season: 'perennial',
    sun: 'Sun or light shade.',
    soil: 'Rich, moisture-retentive soil that does not waterlog in winter.',
    ph: [5.5, 7.0],
    feeding: 'heavy',
    sow: 'Plant crowns in autumn or early spring with the buds at soil level.',
    spacing: '90 cm apart.',
    ready: 'Pull no stalks the first year, a few the second, then until early summer each year.',
    water: 'In dry spells.',
    grow: 'The leaves are poisonous (oxalic acid); eat only the stalks and compost the leaves. Needs a winter chill, so it struggles in the tropics.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('vegetables', 'rhubarb', 'Rhubarb')],
  },
  {
    key: 'globeartichoke',
    name: 'Globe Artichokes',
    aliases: ['artichoke', 'artichokes', 'globe artichoke'],
    latin: 'Cynara cardunculus (Scolymus group)',
    family: 'Daisy family',
    group: 'vegetables',
    season: 'perennial',
    sun: 'Full sun and shelter.',
    soil: 'Fertile, well-drained soil; wet winter soil kills them.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Plant offsets or young plants in spring.',
    spacing: '90 cm apart.',
    ready: 'From the second summer, cut before the scales open.',
    water: 'In dry spells.',
    grow: 'Unpicked heads open into purple thistle flowers bees love. Replace plants every three or four years.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('vegetables', 'globe-artichokes', 'Globe artichokes')],
  },
  {
    key: 'jerusalemartichoke',
    name: 'Jerusalem Artichokes',
    aliases: ['jerusalem artichoke', 'jerusalem artichokes', 'sunchoke', 'sunchokes'],
    latin: 'Helianthus tuberosus',
    family: 'Daisy family',
    group: 'vegetables',
    season: 'perennial',
    sun: 'Sun or light shade.',
    soil: 'Almost any soil.',
    ph: [5.8, 7.0],
    feeding: 'light',
    sow: 'Plant tubers 10 to 15 cm deep in early spring.',
    spacing: '30 cm apart.',
    ready: 'From autumn, once the stems die back.',
    water: 'Rarely needed.',
    grow: 'Any tuber left in the ground regrows, so give them a bed of their own. Tall stems make a summer windbreak.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('vegetables', 'jerusalem-artichokes', 'Jerusalem artichokes')],
  },

  // --------------------------------------------------------------------- Herbs
  {
    key: 'basil',
    name: 'Basil',
    aliases: ['basil'],
    latin: 'Ocimum basilicum',
    family: 'Mint family',
    group: 'herbs',
    season: 'warm',
    sun: 'Full sun and warmth; cold nights blacken it.',
    soil: 'Fertile, well-drained soil or compost.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow in warmth from spring, and plant out only when nights are warm.',
    spacing: '20 to 30 cm apart.',
    ready: 'Pick from about 30 days.',
    water: 'In the morning, at the base; wet evenings encourage rot.',
    grow: 'Pinch out the tips to make bushy plants and stop it flowering. A perennial in frost-free climates.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('herbs', 'basil', 'Basil')],
  },
  {
    key: 'parsley',
    name: 'Parsley',
    aliases: ['parsley'],
    latin: 'Petroselinum crispum',
    family: 'Carrot family',
    group: 'herbs',
    season: 'cool',
    sun: 'Sun or part shade.',
    soil: 'Fertile, moisture-retentive soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow direct or in pots; germination is slow, up to four weeks.',
    spacing: '15 to 23 cm apart.',
    ready: 'About 70 to 90 days from sowing.',
    water: 'Keep moist.',
    grow: 'A biennial: it runs to seed in its second year, when the flowers feed hoverflies.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('herbs', 'parsley', 'Parsley')],
  },
  {
    key: 'coriander',
    name: 'Coriander (Cilantro)',
    aliases: ['coriander', 'cilantro'],
    latin: 'Coriandrum sativum',
    family: 'Carrot family',
    group: 'herbs',
    season: 'cool',
    sun: 'Sun, or light shade in heat.',
    soil: 'Well-drained, moderately fertile soil.',
    ph: [6.2, 6.8],
    feeding: 'light',
    sow: 'Sow direct every three weeks; it resents transplanting.',
    spacing: '5 to 20 cm apart.',
    ready: 'Leaves from about 30 days, seed from about 90.',
    water: 'Keep moist; dry soil makes it bolt.',
    grow: 'Heat and long days bring on flowering fast, so in hot climates it is a cool-season crop. The seeds are the spice coriander.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('herbs', 'coriander', 'Coriander')],
  },
  {
    key: 'mint',
    name: 'Mint',
    aliases: ['mint', 'spearmint', 'peppermint', 'hierbabuena'],
    latin: 'Mentha spp.',
    family: 'Mint family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Sun or part shade.',
    soil: 'Moist, fertile soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant a rooted piece or pot in spring.',
    spacing: 'One plant fills a large pot.',
    ready: 'Pick from spring to autumn.',
    water: 'Keep moist.',
    grow: 'Spreads fast by underground runners, so grow it in a pot, sunk in the ground if you like.',
    watchFor: [{ label: 'Mint rust', note: 'Orange pustules on distorted shoots. A fungus; cut affected stems to the ground and move the mint.' }],
    sources: [rhs('herbs', 'mint', 'Mint')],
  },
  {
    key: 'rosemary',
    name: 'Rosemary',
    aliases: ['rosemary'],
    latin: 'Salvia rosmarinus',
    family: 'Mint family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Poor to moderate, very well-drained soil; it dies in wet winter soil.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Plant young plants or root cuttings in spring.',
    spacing: '60 to 90 cm apart.',
    ready: 'Pick all year once established.',
    water: 'Little once established.',
    grow: 'A Mediterranean shrub; rich feeding gives soft, weakly flavoured growth. Trim after flowering.',
    watchFor: [{ label: 'Root rot', note: 'Sudden browning and death in waterlogged soil. Drainage, not feeding.' }],
    sources: [rhs('herbs', 'rosemary', 'Rosemary')],
  },
  {
    key: 'thyme',
    name: 'Thyme',
    aliases: ['thyme'],
    latin: 'Thymus vulgaris',
    family: 'Mint family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Lean, sharply drained soil; gravel suits it.',
    ph: [6.0, 8.0],
    feeding: 'light',
    sow: 'Plant young plants in spring.',
    spacing: '20 to 30 cm apart.',
    ready: 'Pick all year.',
    water: 'Rarely.',
    grow: 'Trim after flowering to stop it turning woody. Bees work the flowers constantly.',
    watchFor: [{ label: 'Rot in wet soil', note: 'Drainage, not feeding.' }],
    sources: [rhs('herbs', 'thyme', 'Thyme')],
  },
  {
    key: 'oregano',
    name: 'Oregano and Marjoram',
    aliases: ['oregano', 'marjoram'],
    latin: 'Origanum vulgare',
    family: 'Mint family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Lean, well-drained soil.',
    ph: [6.0, 8.0],
    feeding: 'light',
    sow: 'Plant young plants in spring, or sow on the surface.',
    spacing: '30 cm apart.',
    ready: 'Pick from early summer; flavour peaks just before flowering.',
    water: 'Rarely.',
    grow: 'Leave some to flower for the bees and butterflies.',
    watchFor: [{ label: 'Rot in wet soil', note: 'Drainage, not feeding.' }],
    sources: [rhs('herbs', 'oregano', 'Oregano')],
  },
  {
    key: 'sage',
    name: 'Sage',
    aliases: ['sage'],
    latin: 'Salvia officinalis',
    family: 'Mint family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained, not too rich.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Plant young plants in spring.',
    spacing: '45 to 60 cm apart.',
    ready: 'Pick all year.',
    water: 'Rarely once established.',
    grow: 'Prune lightly in spring and replace woody plants every few years.',
    watchFor: [{ label: 'Rot in wet soil', note: 'Drainage, not feeding.' }],
    sources: [rhs('herbs', 'sage', 'Sage')],
  },
  {
    key: 'dill',
    name: 'Dill',
    aliases: ['dill'],
    latin: 'Anethum graveolens',
    family: 'Carrot family',
    group: 'herbs',
    season: 'cool',
    sun: 'Full sun, sheltered from wind.',
    soil: 'Well-drained soil.',
    ph: [5.8, 6.5],
    feeding: 'light',
    sow: 'Sow direct every few weeks; it dislikes transplanting.',
    spacing: '20 to 30 cm apart.',
    ready: 'Leaves from about 40 days.',
    water: 'Keep moist; dry soil makes it bolt.',
    grow: 'Flowers draw in hoverflies and parasitic wasps that eat aphids. Keep it away from fennel, which it crosses with.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('herbs', 'dill', 'Dill')],
  },
  {
    key: 'chives',
    name: 'Chives',
    aliases: ['chives', 'chive'],
    latin: 'Allium schoenoprasum',
    family: 'Onion family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Sun or light shade.',
    soil: 'Fertile, moisture-retentive soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow in spring or plant a clump.',
    spacing: '15 to 20 cm apart.',
    ready: 'Cut from about 60 days, back to 5 cm each time.',
    water: 'Keep moist.',
    grow: 'Lift and divide clumps every few years. The flowers are edible.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('herbs', 'chives', 'Chives')],
  },
  {
    key: 'tarragon',
    name: 'Tarragon',
    aliases: ['tarragon'],
    latin: 'Artemisia dracunculus',
    family: 'Daisy family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained, not too rich.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'French tarragon sets no seed; buy a plant or take root cuttings. Seed sold as tarragon is the coarser Russian kind.',
    spacing: '45 to 60 cm apart.',
    ready: 'Pick from early summer.',
    water: 'Little.',
    grow: 'Divide every few years to keep it vigorous.',
    watchFor: [{ label: 'Rot in wet soil', note: 'Drainage, not feeding.' }],
    sources: [rhs('herbs', 'tarragon', 'Tarragon')],
  },
  {
    key: 'lemonbalm',
    name: 'Lemon Balm',
    aliases: ['lemon balm', 'melissa'],
    latin: 'Melissa officinalis',
    family: 'Mint family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Sun or part shade.',
    soil: 'Most soils.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Sow or plant in spring.',
    spacing: '45 cm apart.',
    ready: 'Pick from early summer.',
    water: 'In dry spells.',
    grow: 'Seeds itself freely; cut back after flowering to stop it spreading. Melissa means honeybee, for good reason.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('herbs', 'lemon-balm', 'Lemon balm')],
  },

  // --------------------------------------------------------------------- Fruit
  {
    key: 'strawberry',
    name: 'Strawberries',
    aliases: ['strawberry', 'strawberries'],
    latin: 'Fragaria × ananassa',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Fertile, well-drained soil, slightly acid.',
    ph: [5.5, 6.5],
    feeding: 'moderate',
    sow: 'Plant runners or young plants in late summer or spring, with the crown at soil level.',
    spacing: '35 to 45 cm apart.',
    ready: 'The first summer after planting.',
    water: 'Regularly while fruit swells, at the base.',
    grow: 'Straw under the fruit keeps it clean. Replace plants every three or four years with rooted runners, on a fresh bed.',
    watchFor: [IRON_ON_ALKALINE, MG_FROM_POTASH, POTASH_SCORCH],
    sources: [rhs('fruit', 'strawberries', 'Strawberries')],
  },
  {
    key: 'raspberry',
    name: 'Raspberries',
    aliases: ['raspberry', 'raspberries'],
    latin: 'Rubus idaeus',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Sun or light shade.',
    soil: 'Moisture-retentive, well-drained, slightly acid soil.',
    ph: [5.5, 6.5],
    feeding: 'moderate',
    sow: 'Plant canes in winter, then cut them to 25 cm.',
    spacing: '40 to 45 cm apart along a wire support.',
    ready: 'Summer kinds the second summer, autumn kinds the first autumn.',
    water: 'In dry spells, especially as fruit swells.',
    grow: 'Mulch thickly; the roots are shallow. Summer kinds fruit on last year’s canes, autumn kinds on this year’s.',
    watchFor: [IRON_ON_ALKALINE, MN_ALKALINE, POTASH_SCORCH],
    sources: [rhs('fruit', 'raspberries', 'Raspberries')],
  },
  {
    key: 'blackberry',
    name: 'Blackberries',
    aliases: ['blackberry', 'blackberries'],
    latin: 'Rubus fruticosus agg.',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Sun or part shade.',
    soil: 'Almost any soil that does not waterlog.',
    ph: [5.5, 7.0],
    feeding: 'moderate',
    sow: 'Plant in winter against wires or a fence.',
    spacing: '2 to 4 metres apart for vigorous kinds.',
    ready: 'Late summer, from the second year.',
    water: 'In dry spells.',
    grow: 'Fruit comes on last year’s canes; cut them out after fruiting and tie in the new ones.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('fruit', 'blackberries', 'Blackberries')],
  },
  {
    key: 'blueberry',
    name: 'Blueberries',
    aliases: ['blueberry', 'blueberries'],
    latin: 'Vaccinium corymbosum',
    family: 'Heather family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Sun or part shade.',
    soil: 'Acid soil only; in a chalky or alkaline garden, grow them in pots of ericaceous compost.',
    ph: [4.5, 5.5],
    feeding: 'light',
    sow: 'Plant in autumn or winter. Two different kinds together give heavier crops.',
    spacing: '1.5 metres apart.',
    ready: 'Midsummer onward, from the second or third year.',
    water: 'With rainwater; hard tap water raises the pH over time.',
    grow: 'Mulch with pine needles or composted bark. Feed with an ericaceous feed, never lime.',
    watchFor: [IRON_ON_ALKALINE, PALE_OLD_LEAVES],
    sources: [rhs('fruit', 'blueberries', 'Blueberries')],
  },
  {
    key: 'gooseberry',
    name: 'Gooseberries',
    aliases: ['gooseberry', 'gooseberries'],
    latin: 'Ribes uva-crispa',
    family: 'Currant family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Sun or part shade.',
    soil: 'Moisture-retentive, well-drained soil.',
    ph: [6.0, 6.7],
    feeding: 'moderate',
    sow: 'Plant in winter.',
    spacing: '1.2 to 1.5 metres apart.',
    ready: 'Early to midsummer, from the second year.',
    water: 'In dry spells.',
    grow: 'Prune to an open goblet shape for air and easy picking.',
    watchFor: [POTASH_SCORCH, { label: 'Gooseberry sawfly', note: 'Leaves stripped by green caterpillars in weeks. A pest; check under leaves from spring.' }],
    sources: [rhs('fruit', 'gooseberries', 'Gooseberries')],
  },
  {
    key: 'blackcurrant',
    name: 'Blackcurrants',
    aliases: ['blackcurrant', 'blackcurrants', 'black currant', 'black currants'],
    latin: 'Ribes nigrum',
    family: 'Currant family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Sun.',
    soil: 'Rich, moisture-retentive soil.',
    ph: [6.0, 6.5],
    feeding: 'heavy',
    sow: 'Plant deeper than before, in winter, to encourage shoots from below ground.',
    spacing: '1.5 metres apart.',
    ready: 'Midsummer.',
    water: 'In dry spells.',
    grow: 'Fruits on young wood, so cut out a third of the oldest stems each winter.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('fruit', 'blackcurrants', 'Blackcurrants')],
  },
  {
    key: 'redcurrant',
    name: 'Redcurrants and Whitecurrants',
    aliases: ['redcurrant', 'redcurrants', 'red currant', 'red currants', 'whitecurrant', 'white currants'],
    latin: 'Ribes rubrum',
    family: 'Currant family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Sun or part shade.',
    soil: 'Well-drained soil.',
    ph: [6.0, 6.7],
    feeding: 'moderate',
    sow: 'Plant in winter.',
    spacing: '1.2 to 1.5 metres apart.',
    ready: 'Midsummer.',
    water: 'In dry spells.',
    grow: 'Can be trained flat against a wall. Net against birds.',
    watchFor: [POTASH_SCORCH],
    sources: [rhs('fruit', 'redcurrants', 'Redcurrants')],
  },
  {
    key: 'apple',
    name: 'Apples',
    aliases: ['apple', 'apples'],
    latin: 'Malus domestica',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Deep, well-drained soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant in winter. The rootstock decides the size of tree, and most kinds need a pollination partner that flowers at the same time.',
    spacing: 'From 1.5 metres for dwarf rootstocks to 6 for vigorous ones.',
    ready: 'Late summer to autumn by kind, from about the third year.',
    water: 'Young trees in dry spells.',
    grow: 'Thin crowded fruitlets in early summer for larger fruit and to even out biennial bearing. Needs a winter chill, so choose low-chill kinds in warm climates.',
    watchFor: [
      { nutrient: 'Ca', label: 'Bitter pit', note: 'Small brown sunken spots in the fruit. Calcium not reaching it; even watering, and calcium sprays in bad years.' },
      MG_FROM_POTASH,
      POTASH_SCORCH,
    ],
    sources: [rhs('fruit', 'apples', 'Apples')],
  },
  {
    key: 'pear',
    name: 'Pears',
    aliases: ['pear', 'pears'],
    latin: 'Pyrus communis',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, sheltered; they flower early.',
    soil: 'Deep, moisture-retentive soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant in winter, with a pollination partner.',
    spacing: '3 to 5 metres apart depending on rootstock.',
    ready: 'Pick while still firm and ripen indoors.',
    water: 'In dry spells.',
    grow: 'Frost at flowering is the usual reason for no crop.',
    watchFor: [IRON_ON_ALKALINE, { nutrient: 'B', label: 'Blossom that withers, pitted fruit', note: 'Boron shortage.' }],
    sources: [rhs('fruit', 'pears', 'Pears')],
  },
  {
    key: 'plum',
    name: 'Plums',
    aliases: ['plum', 'plums', 'damson', 'gage'],
    latin: 'Prunus domestica',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, sheltered.',
    soil: 'Moisture-retentive, well-drained soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant in winter. Many kinds are self-fertile.',
    spacing: '3 to 5 metres apart.',
    ready: 'Late summer.',
    water: 'In dry spells.',
    grow: 'Prune only in summer, which limits silver leaf disease entering the cuts.',
    watchFor: [POTASH_SCORCH, MG_FROM_POTASH],
    sources: [rhs('fruit', 'plums', 'Plums')],
  },
  {
    key: 'cherry',
    name: 'Cherries',
    aliases: ['cherry', 'cherries'],
    latin: 'Prunus avium, P. cerasus',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun; sour cherries tolerate some shade.',
    soil: 'Deep, well-drained soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant in winter; check whether the kind is self-fertile.',
    spacing: '3 to 5 metres apart on a dwarfing rootstock.',
    ready: 'Early to midsummer.',
    water: 'Evenly as fruit swells; rain on ripe fruit splits it.',
    grow: 'Net against birds. Prune in summer, like plums.',
    watchFor: [POTASH_SCORCH],
    sources: [rhs('fruit', 'cherries', 'Cherries')],
  },
  {
    key: 'apricot',
    name: 'Apricots',
    aliases: ['apricot', 'apricots'],
    latin: 'Prunus armeniaca',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, a warm wall in cool climates.',
    soil: 'Deep, well-drained, slightly alkaline to neutral soil.',
    ph: [6.5, 7.5],
    feeding: 'moderate',
    sow: 'Plant in winter; most are self-fertile.',
    spacing: '4 to 5 metres, or fan-trained against a wall.',
    ready: 'Midsummer.',
    water: 'Well as fruit swells.',
    grow: 'Flowers very early, so hand-pollinate with a soft brush when few insects are about.',
    watchFor: [POTASH_SCORCH, IRON_ON_ALKALINE],
    sources: [rhs('fruit', 'apricots', 'Apricots')],
  },
  {
    key: 'fig',
    name: 'Figs',
    aliases: ['fig', 'figs'],
    latin: 'Ficus carica',
    family: 'Mulberry family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, a warm wall in cool climates.',
    soil: 'Well-drained soil; rich soil gives leaves rather than fruit, so roots are often restricted.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Plant in spring. The common kinds set fruit with no pollinator.',
    spacing: '3 to 5 metres.',
    ready: 'Late summer; ripe when soft and drooping.',
    water: 'Regularly as fruit swells, especially in pots.',
    grow: 'The sap irritates skin in sunlight. In the tropics figs fruit through much of the year.',
    watchFor: [POTASH_SCORCH, { label: 'Root-knot nematodes', note: 'Stunted trees in sandy soils. Thick mulch helps.' }],
    sources: [rhs('fruit', 'figs', 'Figs'), edis('MG214', 'Fig growing in the Florida home landscape')],
  },
  {
    key: 'grape',
    name: 'Grapes',
    aliases: ['grape', 'grapes'],
    latin: 'Vitis vinifera',
    family: 'Grape family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, the warmest spot available.',
    soil: 'Deep, well-drained soil; not too rich.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant in winter against wires, a pergola or a wall.',
    spacing: '1.2 to 1.5 metres along wires.',
    ready: 'Late summer to autumn, from the third year.',
    water: 'Young vines in dry spells.',
    grow: 'Prune hard in winter; grapes fruit on the current season’s shoots.',
    watchFor: [MG_FROM_POTASH, POTASH_SCORCH],
    sources: [rhs('fruit', 'grapes', 'Grapes')],
  },
  {
    key: 'kiwi',
    name: 'Kiwifruit',
    aliases: ['kiwi', 'kiwifruit', 'kiwi fruit'],
    latin: 'Actinidia deliciosa',
    family: 'Kiwifruit family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, sheltered.',
    soil: 'Deep, fertile, well-drained, slightly acid soil.',
    ph: [5.5, 7.0],
    feeding: 'moderate',
    sow: 'Plant in spring. Most kinds need a male and a female plant; a few are self-fertile.',
    spacing: '3 to 5 metres along strong supports.',
    ready: 'Autumn, from about the fourth year.',
    water: 'Generously in summer.',
    grow: 'A very vigorous climber; prune in winter and summer.',
    watchFor: [IRON_ON_ALKALINE],
    sources: [rhs('fruit', 'kiwi', 'Kiwi')],
  },
  {
    key: 'melon',
    name: 'Melons',
    aliases: ['melon', 'melons', 'cantaloupe', 'honeydew', 'muskmelon', 'watermelon', 'watermelons'],
    latin: 'Cucumis melo',
    family: 'Squash family',
    group: 'fruit',
    season: 'warm',
    sun: 'Full sun and heat; a greenhouse in cool climates.',
    soil: 'Rich, well-drained soil.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Sow in warmth and plant out when nights are warm.',
    spacing: '90 cm apart.',
    ready: 'About 80 to 100 days; ripe melons smell sweet and the stalk cracks away.',
    water: 'Generously until fruits are full size, then less, for sweetness.',
    grow: 'Limit each plant to a few fruits in short seasons. Watermelon (Citrullus lanatus) is grown the same way with more room and heat.',
    watchFor: [MG_FROM_POTASH, { nutrient: 'B', label: 'Cracked, misshapen fruit', note: 'Boron shortage.' }],
    sources: [rhs('fruit', 'melons', 'Melons'), FLORIDA_VEG],
  },
  {
    key: 'citrus',
    name: 'Oranges and Mandarins',
    aliases: ['orange', 'oranges', 'mandarin', 'mandarins', 'tangerine', 'tangerines', 'grapefruit', 'clementine', 'citrus'],
    latin: 'Citrus sinensis, C. reticulata',
    family: 'Citrus family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun; in frosty climates, in pots brought under cover for winter.',
    soil: 'Well-drained soil or a gritty citrus compost in pots.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Plant grafted trees in spring.',
    spacing: '4 to 6 metres in the ground.',
    ready: 'Fruit takes 6 to 12 months to ripen on the tree.',
    water: 'Deeply, then let the top dry; waterlogging rots roots.',
    grow: 'Feed through the growing season with a citrus feed. Citrus show shortages of magnesium, iron, zinc and manganese more readily than most plants.',
    watchFor: [MG_FROM_POTASH, IRON_ON_ALKALINE, ZINC_LITTLE_LEAF, MN_ALKALINE],
    sources: [rhs('fruit', 'citrus', 'Citrus'), edis('HS132', 'Citrus culture in the home landscape')],
  },

  // ------------------------------------------------- Warm climate and tropical
  {
    key: 'lemon',
    name: 'Lemons',
    aliases: ['lemon', 'lemons'],
    latin: 'Citrus limon',
    family: 'Citrus family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained soil; lemons tolerate poorer soil than oranges.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Plant grafted trees in the warm season.',
    spacing: '4 to 6 metres.',
    ready: 'Several flushes of fruit a year in warm climates.',
    water: 'Deeply and regularly; never waterlogged.',
    grow: 'The most frost-tender common citrus. Prune out thorny shoots from below the graft.',
    watchFor: [MG_FROM_POTASH, IRON_ON_ALKALINE, ZINC_LITTLE_LEAF],
    sources: [edis('HS402', 'Lemon growing in the home landscape'), edis('HS132', 'Citrus culture in the home landscape')],
  },
  {
    key: 'lime',
    name: 'Limes',
    aliases: ['lime', 'limes', 'key lime', 'persian lime', 'limon'],
    latin: 'Citrus × aurantiifolia, C. × latifolia',
    family: 'Citrus family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained soil; very sensitive to waterlogging.',
    ph: [6.0, 7.5],
    feeding: 'heavy',
    sow: 'Plant in the warm season.',
    spacing: '4 to 5 metres.',
    ready: 'Fruit through much of the year in the tropics.',
    water: 'Regularly in dry seasons.',
    grow: 'Key (Mexican) limes are the most cold-sensitive; Persian (Tahiti) limes are seedless and larger. On limestone soils they show iron and zinc shortage readily.',
    watchFor: [IRON_ON_ALKALINE, ZINC_LITTLE_LEAF, MN_ALKALINE],
    sources: [edis('CH092', 'Key lime growing in the home landscape'), edis('HS132', 'Citrus culture in the home landscape')],
  },
  {
    key: 'mango',
    name: 'Mangoes',
    aliases: ['mango', 'mangoes', 'mangos'],
    latin: 'Mangifera indica',
    family: 'Cashew family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Deep, well-drained soil of almost any texture.',
    ph: [5.5, 7.5],
    feeding: 'moderate',
    sow: 'Plant grafted trees at the start of the rainy or warm season; seedlings take years longer to fruit.',
    spacing: '7 to 10 metres, less for small kinds kept pruned.',
    ready: 'Grafted trees from about the third or fourth year; fruit ripens 100 to 150 days after flowering.',
    water: 'Young trees regularly; mature trees flower best after a dry, cooler spell.',
    grow: 'Rain at flowering brings anthracnose, the black spotting on flowers and fruit, so dry-season flowering kinds suit humid coasts. Prune after harvest to keep the tree low.',
    watchFor: [ZINC_LITTLE_LEAF, IRON_ON_ALKALINE, MN_ALKALINE],
    sources: [edis('MG216', 'Mango growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'banana',
    name: 'Bananas and Plantains',
    aliases: ['banana', 'bananas', 'plantain', 'plantains', 'platano'],
    latin: 'Musa spp.',
    family: 'Banana family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun, sheltered from wind.',
    soil: 'Deep, rich, well-drained soil full of organic matter.',
    ph: [5.5, 7.0],
    feeding: 'heavy',
    sow: 'Plant suckers (pups) or tissue-cultured plants in the warm season.',
    spacing: '3 to 4 metres.',
    ready: 'About 9 to 15 months from planting to a bunch; cut it when the fruits fill out and lose their angles.',
    water: 'Large amounts; the leaves are mostly water.',
    grow: 'Each stem fruits once. After harvest cut it down, chop it as mulch around the base, and keep one or two suckers to follow. Heavy feeders of potassium above all.',
    watchFor: [POTASH_SCORCH, MG_FROM_POTASH, PALE_OLD_LEAVES],
    sources: [edis('MG040', 'Banana growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'papaya',
    name: 'Papayas',
    aliases: ['papaya', 'papayas', 'pawpaw'],
    latin: 'Carica papaya',
    family: 'Papaya family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Very well-drained soil; a day of standing water can kill it.',
    ph: [5.5, 7.0],
    feeding: 'heavy',
    sow: 'Sow fresh seed in the warm season, several to a spot, and keep the strongest.',
    spacing: '2.5 to 3 metres.',
    ready: 'About 6 to 11 months from planting.',
    water: 'Regularly, never waterlogged.',
    grow: 'Plants are male, female or bisexual; bisexual plants fruit on their own, and a female needs a male nearby. Short-lived, so replant every few years.',
    watchFor: [
      { nutrient: 'B', label: 'Lumpy, misshapen fruit', note: 'Boron shortage, well documented in papaya.' },
      PALE_OLD_LEAVES,
    ],
    sources: [edis('MG054', 'Papaya growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'avocado',
    name: 'Avocados',
    aliases: ['avocado', 'avocados', 'aguacate'],
    latin: 'Persea americana',
    family: 'Laurel family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Deep, very well-drained soil; root rot follows any waterlogging.',
    ph: [5.5, 7.0],
    feeding: 'moderate',
    sow: 'Plant grafted trees on a mound in the warm season.',
    spacing: '6 to 9 metres.',
    ready: 'Grafted trees from about the third or fourth year. Fruit ripens only after picking.',
    water: 'Deeply and regularly, letting the surface dry between.',
    grow: 'Leave fallen leaves as mulch under the tree; they suppress root rot. Flower types A and B shed pollen at different times, so one of each sets more fruit.',
    watchFor: [IRON_ON_ALKALINE, ZINC_LITTLE_LEAF, { label: 'Root rot', note: 'Small pale leaves and dieback in wet soil. Phytophthora, a water mould; drainage is the fix.' }],
    sources: [edis('MG213', 'Avocado growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'pineapple',
    name: 'Pineapples',
    aliases: ['pineapple', 'pineapples', 'pina'],
    latin: 'Ananas comosus',
    family: 'Bromeliad family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun or light shade.',
    soil: 'Sandy, well-drained, acid soil.',
    ph: [4.5, 6.5],
    feeding: 'moderate',
    sow: 'Plant the leafy top of a bought fruit, dried for a few days, or a sucker.',
    spacing: '30 to 60 cm.',
    ready: 'About 18 to 24 months to fruit.',
    water: 'Moderately; the leaf bases hold water.',
    grow: 'Grows well in pots. After fruiting, suckers give the next crop.',
    watchFor: [IRON_ON_ALKALINE, PALE_OLD_LEAVES],
    sources: [edis('MG055', 'Pineapple growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'guava',
    name: 'Guavas',
    aliases: ['guava', 'guavas', 'guayaba'],
    latin: 'Psidium guajava',
    family: 'Myrtle family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Most well-drained soils.',
    ph: [4.5, 7.0],
    feeding: 'moderate',
    sow: 'Plant in the warm season.',
    spacing: '4 to 6 metres.',
    ready: 'From the second or third year; ripe fruit softens and smells strongly.',
    water: 'Regularly while fruiting.',
    grow: 'Tough and quick. Can seed itself widely and become weedy in some tropical places.',
    watchFor: [ZINC_LITTLE_LEAF, MN_ALKALINE],
    sources: [edis('MG045', 'Guava growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'pomegranate',
    name: 'Pomegranates',
    aliases: ['pomegranate', 'pomegranates', 'granada'],
    latin: 'Punica granatum',
    family: 'Loosestrife family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun and heat.',
    soil: 'Well-drained soil; tolerates alkaline soil.',
    ph: [5.5, 7.5],
    feeding: 'light',
    sow: 'Plant in spring or at the start of the warm season.',
    spacing: '4 to 5 metres.',
    ready: 'About 5 to 7 months after flowering.',
    water: 'Drought-tolerant, but steady watering stops fruit splitting.',
    grow: 'A shrub or small tree; prune suckers from the base.',
    watchFor: [{ label: 'Split fruit', note: 'Heavy water after a dry spell. Steady watering, not feeding.' }],
    sources: [edis('MG056', 'Pomegranate growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'lychee',
    name: 'Lychees',
    aliases: ['lychee', 'lychees', 'litchi'],
    latin: 'Litchi chinensis',
    family: 'Soapberry family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun, sheltered from wind.',
    soil: 'Deep, well-drained, slightly acid soil.',
    ph: [5.0, 6.5],
    feeding: 'moderate',
    sow: 'Plant air-layered trees in the warm season.',
    spacing: '6 to 9 metres.',
    ready: 'From about the fourth or fifth year.',
    water: 'Regularly, but a dry, cool spell before flowering sets the crop.',
    grow: 'Irregular bearers without that cool, dry winter. Shows iron and zinc shortage on alkaline soils.',
    watchFor: [IRON_ON_ALKALINE, ZINC_LITTLE_LEAF],
    sources: [edis('MG051', 'Lychee growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'longan',
    name: 'Longans',
    aliases: ['longan', 'longans'],
    latin: 'Dimocarpus longan',
    family: 'Soapberry family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained, slightly acid soil.',
    ph: [5.5, 6.5],
    feeding: 'moderate',
    sow: 'Plant air-layered or grafted trees in the warm season.',
    spacing: '6 to 9 metres.',
    ready: 'From about the third to fifth year.',
    water: 'Regularly, less before flowering.',
    grow: 'Like lychee, flowers best after a cool, dry spell.',
    watchFor: [IRON_ON_ALKALINE, ZINC_LITTLE_LEAF],
    sources: [edis('MG049', 'Longan growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'loquat',
    name: 'Loquats',
    aliases: ['loquat', 'loquats', 'nispero'],
    latin: 'Eriobotrya japonica',
    family: 'Rose family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun or light shade.',
    soil: 'Most well-drained soils.',
    ph: [5.5, 7.5],
    feeding: 'moderate',
    sow: 'Plant grafted trees in the warm season.',
    spacing: '5 to 7 metres.',
    ready: 'Late winter to spring, from about the third year.',
    water: 'In dry spells while fruiting.',
    grow: 'Flowers in autumn and winter, feeding bees when little else does.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [edis('MG050', 'Loquat growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'sapodilla',
    name: 'Sapodillas (Chicozapote)',
    aliases: ['sapodilla', 'sapodillas', 'chicozapote', 'chico'],
    latin: 'Manilkara zapota',
    family: 'Sapote family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Almost any well-drained soil; tolerates salt spray and limestone.',
    ph: [6.0, 8.0],
    feeding: 'light',
    sow: 'Plant grafted trees in the warm season.',
    spacing: '7 to 9 metres.',
    ready: 'From about the third to fifth year; pick mature and ripen off the tree.',
    water: 'Drought-tolerant once established.',
    grow: 'Slow-growing and long-lived. The sap is chicle, the original chewing gum.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [edis('MG057', 'Sapodilla growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'sugarapple',
    name: 'Sugar Apples (Anona)',
    aliases: ['sugar apple', 'sugar apples', 'sweetsop', 'anona', 'custard apple'],
    latin: 'Annona squamosa',
    family: 'Custard apple family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained soil; tolerates poor, rocky ground.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Plant in the warm season.',
    spacing: '4 to 6 metres.',
    ready: 'From about the third year; ripe when the segments separate and yellow between.',
    water: 'Drought-tolerant; water as fruit sets.',
    grow: 'Small beetles pollinate it, so fruit set improves with a little hand pollination in dry climates.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [edis('MG330', 'Sugar apple growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'jackfruit',
    name: 'Jackfruit',
    aliases: ['jackfruit', 'jack fruit', 'yaca'],
    latin: 'Artocarpus heterophyllus',
    family: 'Mulberry family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Deep, well-drained soil; will not tolerate waterlogging.',
    ph: [5.0, 7.5],
    feeding: 'moderate',
    sow: 'Plant grafted trees in the warm season.',
    spacing: '8 to 10 metres.',
    ready: 'From about the third or fourth year for grafted trees.',
    water: 'Regularly while young.',
    grow: 'Fruit can weigh over 20 kg and grows straight from the trunk. Prune to keep the tree low enough to reach.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [edis('MG370', 'Jackfruit growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'passionfruit',
    name: 'Passion Fruit (Maracuyá)',
    aliases: ['passion fruit', 'passionfruit', 'maracuya', 'granadilla'],
    latin: 'Passiflora edulis',
    family: 'Passionflower family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained soil rich in organic matter.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Plant in the warm season against a strong trellis or fence.',
    spacing: '3 to 5 metres along the support.',
    ready: 'From about 12 to 18 months; ripe fruit drops.',
    water: 'Regularly; drought drops fruit.',
    grow: 'Yellow kinds mostly need carpenter bees or hand pollination to set fruit, purple kinds set their own. Vines are short-lived, so replant every few years.',
    watchFor: [POTASH_SCORCH, PALE_OLD_LEAVES],
    sources: [edis('HS1406', 'Passion fruit growing in the home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'sweetpotato',
    name: 'Sweet Potatoes (Camote)',
    aliases: ['sweet potato', 'sweet potatoes', 'sweetpotato', 'camote', 'boniato', 'kumara'],
    latin: 'Ipomoea batatas',
    family: 'Morning glory family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun and heat.',
    soil: 'Light, well-drained soil; rich soil gives leaves rather than roots.',
    ph: [5.5, 6.5],
    feeding: 'light',
    sow: 'Plant rooted shoots (slips) once the soil is warm.',
    spacing: '30 to 45 cm apart.',
    ready: 'About 90 to 120 days.',
    water: 'Regularly until established, then less.',
    grow: 'The young leaves are a leafy green in their own right. Cure dug roots somewhere warm for a week for sweetness and storage.',
    watchFor: [POTASH_SCORCH, { nutrient: 'B', label: 'Cracked, misshapen roots', note: 'Boron shortage on light soils.' }],
    sources: [rhs('vegetables', 'sweet-potatoes', 'Sweet potatoes'), FLORIDA_VEG],
  },
  {
    key: 'okra',
    name: 'Okra',
    aliases: ['okra', 'bamia'],
    latin: 'Abelmoschus esculentus',
    family: 'Mallow family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun and heat.',
    soil: 'Well-drained, fertile soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow direct once the soil is above about 20°C; soak seed overnight first.',
    spacing: '30 to 45 cm apart.',
    ready: 'About 50 to 65 days; pick pods at 5 to 10 cm every day or two.',
    water: 'Deeply in dry spells.',
    grow: 'Pods left on turn woody and stop new ones. The flowers bring bees in.',
    watchFor: [PALE_OLD_LEAVES, POTASH_SCORCH, { label: 'Root-knot nematodes', note: 'Stunted plants with knotted roots, common in warm sandy soils. Rotate, and add plenty of organic matter.' }],
    sources: [rhs('vegetables', 'okra', 'Okra'), FLORIDA_VEG],
  },
  {
    key: 'cassava',
    name: 'Cassava (Yuca)',
    aliases: ['cassava', 'yuca', 'manioc'],
    latin: 'Manihot esculenta',
    family: 'Spurge family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun.',
    soil: 'Well-drained soil; grows in poor, acid soils where little else will.',
    ph: [5.5, 6.5],
    feeding: 'light',
    sow: 'Plant stem cuttings 20 to 30 cm long in the warm season.',
    spacing: '90 cm apart.',
    ready: 'About 8 to 12 months.',
    water: 'Drought-tolerant once established.',
    grow: 'The roots contain compounds that release cyanide, so they are always peeled and cooked, never eaten raw. Too much nitrogen gives leaves rather than roots.',
    watchFor: [POTASH_SCORCH],
    sources: [FLORIDA_VEG],
  },
  {
    key: 'chayote',
    name: 'Chayote',
    aliases: ['chayote', 'chayotes', 'christophene', 'mirliton'],
    latin: 'Sechium edule',
    family: 'Squash family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun or light shade.',
    soil: 'Rich, well-drained soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant a whole mature fruit, sprouted end angled down, half-buried.',
    spacing: 'One vine covers a large trellis.',
    ready: 'From about 4 months; pick young and tender.',
    water: 'Regularly.',
    grow: 'A vigorous perennial vine in frost-free places; the shoots and root are edible too.',
    watchFor: [PALE_OLD_LEAVES, MG_FROM_POTASH],
    sources: [FLORIDA_VEG],
  },
  {
    key: 'malanga',
    name: 'Malanga and Taro',
    aliases: ['malanga', 'taro', 'yautia', 'dasheen', 'eddo'],
    latin: 'Xanthosoma sagittifolium, Colocasia esculenta',
    family: 'Arum family',
    group: 'warm',
    season: 'warm',
    sun: 'Sun or part shade.',
    soil: 'Moist, rich soil; taro tolerates wet ground, malanga needs drainage.',
    ph: [5.5, 6.5],
    feeding: 'moderate',
    sow: 'Plant small corms or top cuttings in the warm season.',
    spacing: '60 to 90 cm apart.',
    ready: 'About 9 to 12 months.',
    water: 'Plenty.',
    grow: 'The corms and leaves hold calcium oxalate crystals that irritate the mouth and throat raw, so they are always cooked.',
    watchFor: [PALE_OLD_LEAVES, POTASH_SCORCH],
    sources: [FLORIDA_VEG],
  },
  {
    key: 'roselle',
    name: 'Roselle (Jamaica)',
    aliases: ['roselle', 'jamaica', 'flor de jamaica', 'hibiscus'],
    latin: 'Hibiscus sabdariffa',
    family: 'Mallow family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun.',
    soil: 'Most well-drained soils.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Sow at the start of the warm season. It flowers only as days shorten, so plants sown late flower small.',
    spacing: '90 cm apart.',
    ready: 'Pick the red calyces about 10 days after the flowers open.',
    water: 'Regularly while young.',
    grow: 'The calyces make agua de jamaica; the young leaves are eaten as a sour green.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [FLORIDA_VEG],
  },
  {
    key: 'malabarspinach',
    name: 'Malabar Spinach',
    aliases: ['malabar spinach', 'basella'],
    latin: 'Basella alba',
    family: 'Basella family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun or light shade.',
    soil: 'Moist, fertile soil.',
    ph: [5.5, 7.5],
    feeding: 'moderate',
    sow: 'Sow or root cuttings in the warm season.',
    spacing: '30 cm apart along a trellis.',
    ready: 'Pick from about 70 days.',
    water: 'Keep moist.',
    grow: 'A heat-loving climbing green for when true spinach bolts.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [FLORIDA_VEG],
  },
  {
    key: 'pigeonpea',
    name: 'Pigeon Peas (Gandul)',
    aliases: ['pigeon pea', 'pigeon peas', 'gandul', 'gandules', 'toor', 'arhar'],
    latin: 'Cajanus cajan',
    family: 'Pea family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun.',
    soil: 'Most well-drained soils, including poor ones.',
    ph: [5.0, 7.0],
    feeding: 'light',
    sow: 'Sow direct in the warm season.',
    spacing: '60 to 90 cm apart.',
    ready: 'Green pods from about 4 to 5 months.',
    water: 'Drought-tolerant.',
    grow: 'A short-lived shrub that fixes nitrogen, so it doubles as living fertiliser, a windbreak and chop-and-drop mulch.',
    watchFor: [{ nutrient: 'Mo', label: 'Pale plants with few nodules', note: 'Molybdenum locked away in very acid soil.' }],
    sources: [FLORIDA_VEG],
  },
  {
    key: 'lemongrass',
    name: 'Lemongrass',
    aliases: ['lemongrass', 'lemon grass', 'zacate limon', 'te de limon'],
    latin: 'Cymbopogon citratus',
    family: 'Grass family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Fertile, moist, well-drained soil.',
    ph: [5.5, 7.5],
    feeding: 'moderate',
    sow: 'Root a stalk from the shop in water, then plant it out.',
    spacing: '60 to 90 cm apart.',
    ready: 'Cut stalks from about 4 months.',
    water: 'Regularly.',
    grow: 'Frost-tender; in cold climates, keep in a pot under cover for winter. Divide large clumps.',
    watchFor: [PALE_OLD_LEAVES],
    sources: [rhs('herbs', 'lemongrass', 'Lemongrass')],
  },
];

export function cropPubmedUrl(guide: CropGuide): string {
  const species = guide.latin.split(',')[0].replace(/\(.*?\)/g, '').replace(/\bspp\.|\bsubsp\..*$|\bagg\./g, '').trim();
  return pubmedSearchUrl(`${species} nutrient deficiency`);
}

// Every source a guide shows: its advisory services, then PubMed.
export function cropSources(guide: CropGuide): GuideSource[] {
  return [...guide.sources, { label: 'PubMed: the research on this crop', url: cropPubmedUrl(guide) }];
}

function normalize(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9 ]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// Food names that begin with a crop's word but are not the crop.
const NOT_A_CROP = ['pepper black', 'black pepper', 'pepper white', 'white pepper', 'corn flakes', 'cornflakes', 'corn starch', 'cornstarch', 'orange juice drink', 'lime juice cordial'];

type AliasEntry = { alias: string; guide: CropGuide };
const ALIAS_INDEX: AliasEntry[] = CROP_GUIDES.flatMap((guide) => guide.aliases.map((alias) => ({ alias: normalize(alias), guide }))).sort(
  (a, b) => b.alias.length - a.alias.length,
);

// The guide for a saved food name, or null. The name has to begin with
// the alias as whole words, so "Mangosteen" is not a mango and
// "Peppermint" is mint only because mint lists it.
export function findCropGuide(foodName: string | null | undefined): CropGuide | null {
  if (!foodName) return null;
  const name = normalize(foodName);
  if (!name || NOT_A_CROP.some((phrase) => name.startsWith(phrase))) return null;
  for (const { alias, guide } of ALIAS_INDEX) {
    if (name === alias || name.startsWith(`${alias} `)) return guide;
  }
  return null;
}

export function findCropGuideByKey(key: string | null | undefined): CropGuide | null {
  if (!key) return null;
  return CROP_GUIDES.find((guide) => guide.key === key) ?? null;
}

export function searchCropGuides(query: string): CropGuide[] {
  const q = normalize(query);
  if (!q) return CROP_GUIDES;
  return CROP_GUIDES.filter((guide) => {
    const haystack = normalize([guide.name, guide.latin, guide.family, ...guide.aliases].join(' '));
    return q.split(' ').every((word) => haystack.includes(word));
  });
}

export function formatPh([low, high]: [number, number]): string {
  return `pH ${low.toFixed(1)} to ${high.toFixed(1)}`;
}

export const FEEDING_LABELS: Record<CropGuide['feeding'], string> = {
  light: 'Light feeder',
  moderate: 'Moderate feeder',
  heavy: 'Heavy feeder',
};

export const SEASON_LABELS: Record<CropGuide['season'], string> = {
  cool: 'Cool season',
  warm: 'Warm season',
  perennial: 'Perennial',
};
