// How to grow each crop: the soil it wants, how to sow and space it, when
// it is ready, and the three problems it is known for (lib/cropProblems.ts),
// with every guide pointing out to the advisory service it stands on, to
// an organic growing guide, and to PubMed.
//
// 2026-09-26, direct request: "In the Garden tab, there needs to be
// information about how to grow each thing, what type of soil it likes,
// what deficiencies of nutrients look like and how to fix it based on
// real world gardening advice they can be pointed to, like PubMed,
// outside of the device."
//
// Where the words come from. The how-to is the kind of guidance the Royal
// Horticultural Society and the University of Florida's IFAS extension
// service publish, the first for temperate gardens and the second for
// warm and tropical ones, since the app is not only for cold climates.
// Each guide links to that service's page for the crop, every link
// checked by scripts/test_crop_guides.js. The figures (pH, spacing, days)
// are the ranges those services commonly give; the linked page carries
// the detail for a particular climate, and the in-app help says so.
// PubMed is linked as a search on the crop's Latin name, which shows the
// research for anyone who wants depth and always resolves.
//
// A planting in Garden > Plots & Plantings is matched to its guide by the
// food name it was saved under (findCropGuide), so "Tomatoes, cherry
// tomatoes, fruit" and "Tomato" both open the tomato guide. Longest alias
// wins, so "Squash, zucchini" is a courgette before it is a squash.
//
// The crop problems, and the sources after a guide, lean on living soil
// rather than a bag or bottle (2026-09-26, direct statement: "we are trying
// to promote not using chemicals to grow their crops and instead make live
// soil through composting and other methods such as Korean Natural
// Farming, with chemical be persuaded against"). The persuasion stays
// truthful: where something is only practitioner experience, as most of
// Korean Natural Farming is, lib/plantNutrients.ts says so.
//
// Pure data and two lookups, no React, checked without a phone.

import { CROP_ORGANIC_SOURCES } from './cropProblems';
import { GO_COMPOST, GO_MULCH, GO_NO_DIG, KNF_IMO, pubmedSearchUrl, type GuideSource } from './plantNutrients';

export type CropGroup = 'vegetables' | 'herbs' | 'fruit' | 'warm';

export const CROP_GROUP_LABELS: Record<CropGroup, string> = {
  vegetables: 'Vegetables',
  herbs: 'Herbs',
  fruit: 'Fruit',
  warm: 'Warm Climate and Tropical',
};

export type CropGuide = {
  key: string;
  name: string;
  // Lower-case words a saved food name starts with. Punctuation is ignored.
  aliases: string[];
  latin: string;
  family: string;
  group: CropGroup;
  season: 'cool' | 'warm' | 'perennial';
  sun: string;
  soil: string;
  ph: [number, number];
  feeding: 'light' | 'moderate' | 'heavy';
  sow: string;
  spacing: string;
  ready: string;
  water: string;
  grow: string;
  sources: GuideSource[];
};

const rhs = (kind: 'vegetables' | 'fruit' | 'herbs', slug: string, label: string): GuideSource => ({
  label: `RHS: ${label}`,
  url: `https://www.rhs.org.uk/${kind}/${slug}/grow-your-own`,
});
const edis = (id: string, label: string): GuideSource => ({
  label: `University of Florida IFAS: ${label}`,
  url: `https://edis.ifas.ufl.edu/publication/${id}`,
});
const FLORIDA_VEG = edis('VH021', 'Florida Vegetable Gardening Guide');
const TROPICAL_FRUIT = edis('MG373', 'Tropical and subtropical fruit crops');

export const CROP_GUIDES: CropGuide[] = [
  // ---------------------------------------------------------------- Vegetables
  {
    key: 'tomato',
    name: 'Tomatoes',
    aliases: ['tomato', 'tomatoes'],
    latin: 'Solanum lycopersicum',
    family: 'Nightshade family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun, at least 6 to 8 hours a day.',
    soil: 'Deep, fertile, well-drained soil with plenty of compost worked in.',
    ph: [6.0, 6.8],
    feeding: 'heavy',
    sow: 'Sow indoors 6 to 8 weeks before the last frost and plant out once nights stay above about 10°C. Plant deeper than they grew in the pot; the buried stem roots.',
    spacing: '45 to 60 cm apart; bush kinds need more room than cordons.',
    ready: 'About 60 to 85 days from planting out, depending on kind.',
    water: 'Deeply and evenly, at the soil rather than on the leaves. Uneven watering causes split fruit and blossom-end rot.',
    grow: 'Stake or cage cordon kinds and pinch out the side shoots that form where a leaf meets the stem. Mulch once the soil is warm. Once the first fruits set, water on comfrey liquid every week or two. Basil and marigolds grown alongside draw in the pollinators and predators that keep pests down.',
    sources: [rhs('vegetables', 'tomatoes', 'Tomatoes'), FLORIDA_VEG],
  },
  {
    key: 'pepper',
    name: 'Peppers and Chillies',
    aliases: ['pepper', 'peppers', 'chilli', 'chili', 'chile', 'jalapeno', 'serrano', 'capsicum', 'bell pepper', 'pepper hot', 'peppers hot', 'peppers sweet'],
    latin: 'Capsicum annuum',
    family: 'Nightshade family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun and warmth; they stall below about 15°C.',
    soil: 'Fertile, well-drained soil rich in compost.',
    ph: [6.0, 6.8],
    feeding: 'moderate',
    sow: 'Sow indoors 8 to 10 weeks before the last frost, in warmth (about 21°C). Plant out when the soil is warm.',
    spacing: '45 cm apart.',
    ready: 'About 60 to 90 days from planting out for green fruit, longer for fully coloured.',
    water: 'Evenly. Dry spells drop flowers and cause blossom-end rot.',
    grow: 'Stake tall kinds. Too much nitrogen gives leaves and few fruit. Hot kinds grow as short-lived perennials in frost-free climates.',
    sources: [rhs('vegetables', 'peppers', 'Peppers'), FLORIDA_VEG],
  },
  {
    key: 'aubergine',
    name: 'Aubergines (Eggplant)',
    aliases: ['aubergine', 'aubergines', 'eggplant', 'eggplants', 'brinjal'],
    latin: 'Solanum melongena',
    family: 'Nightshade family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun and heat; the warmest spot in the garden.',
    soil: 'Fertile, well-drained soil rich in organic matter.',
    ph: [5.5, 6.8],
    feeding: 'heavy',
    sow: 'Sow indoors in warmth 8 to 10 weeks before the last frost; plant out only when nights are warm.',
    spacing: '60 cm apart.',
    ready: 'About 70 to 85 days from planting out, while the skin is still glossy.',
    water: 'Evenly and generously.',
    grow: 'Stake the plants. In a short season, limit each plant to five or six fruits so they ripen.',
    sources: [rhs('vegetables', 'aubergines', 'Aubergines'), FLORIDA_VEG],
  },
  {
    key: 'potato',
    name: 'Potatoes',
    aliases: ['potato', 'potatoes'],
    latin: 'Solanum tuberosum',
    family: 'Nightshade family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Deep, loose, fertile soil. Dug-in compost or rotted manure the autumn before suits them.',
    ph: [5.0, 6.5],
    feeding: 'heavy',
    sow: 'Plant seed potatoes (sprouted first in light, if you like) 10 to 15 cm deep from early spring. In warm climates, grow them in the coolest months.',
    spacing: '30 cm apart for earlies, 38 cm for maincrop, rows 60 to 75 cm apart.',
    ready: 'Earlies about 10 to 12 weeks after planting, maincrop 15 to 20 weeks.',
    water: 'Steadily once tubers are forming, which is around flowering.',
    grow: 'Draw soil up around the stems as they grow (earthing up) so no tuber sees light; green potatoes are toxic. Do not lime before potatoes. Rotate beds to keep blight and pests from building up.',
    sources: [rhs('vegetables', 'potatoes', 'Potatoes'), edis('HS183', 'Potato production')],
  },
  {
    key: 'lettuce',
    name: 'Lettuce',
    aliases: ['lettuce'],
    latin: 'Lactuca sativa',
    family: 'Daisy family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun in cool weather, light shade in heat.',
    soil: 'Moisture-retentive soil with plenty of organic matter.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow a short row every two or three weeks for a steady supply. Seed may not germinate above about 25°C, so sow in the evening or in shade in hot weather.',
    spacing: '15 cm for loose-leaf, 30 cm for hearting kinds.',
    ready: 'Loose-leaf in about 30 days, hearting kinds in 60 to 80.',
    water: 'Little and often; dry soil makes lettuce bitter and quick to run to seed.',
    grow: 'Heat and long days make it bolt (run to seed). In hot climates it is a cool-season crop.',
    sources: [rhs('vegetables', 'lettuce', 'Lettuce'), FLORIDA_VEG],
  },
  {
    key: 'spinach',
    name: 'Spinach',
    aliases: ['spinach'],
    latin: 'Spinacia oleracea',
    family: 'Amaranth family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or part shade.',
    soil: 'Fertile, moisture-retentive soil. It does poorly in acid soil.',
    ph: [6.5, 7.5],
    feeding: 'moderate',
    sow: 'Sow direct in spring and late summer. Long days and heat make it bolt.',
    spacing: '7 to 15 cm apart.',
    ready: 'About 40 to 50 days.',
    water: 'Keep evenly moist.',
    grow: 'In hot weather, Malabar spinach or chard are easier leafy greens.',
    sources: [rhs('vegetables', 'spinach', 'Spinach')],
  },
  {
    key: 'chard',
    name: 'Chard',
    aliases: ['chard', 'swiss chard', 'silverbeet', 'leaf beet'],
    latin: 'Beta vulgaris subsp. vulgaris',
    family: 'Amaranth family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or part shade.',
    soil: 'Fertile soil with compost worked in.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Sow direct from spring to late summer.',
    spacing: '30 to 40 cm apart.',
    ready: 'About 50 to 60 days, then picked leaf by leaf for months.',
    water: 'Keep evenly moist.',
    grow: 'Takes heat far better than spinach. Pick outer leaves and let the centre keep growing.',
    sources: [rhs('vegetables', 'chard', 'Chard')],
  },
  {
    key: 'kale',
    name: 'Kale',
    aliases: ['kale'],
    latin: 'Brassica oleracea (Acephala group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or light shade.',
    soil: 'Firm, fertile soil; brassicas grow poorly in loose, freshly dug ground.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Sow in spring, transplant in early summer for autumn and winter picking.',
    spacing: '45 to 60 cm apart.',
    ready: 'About 55 to 75 days, then picked for months.',
    water: 'Keep moist, especially when young.',
    grow: 'The hardiest brassica; frost sweetens the leaves. Net against cabbage white caterpillars and pigeons.',
    sources: [rhs('vegetables', 'kale', 'Kale')],
  },
  {
    key: 'cabbage',
    name: 'Cabbages',
    aliases: ['cabbage', 'cabbages'],
    latin: 'Brassica oleracea (Capitata group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Firm, fertile, moisture-retentive soil.',
    ph: [6.5, 7.5],
    feeding: 'heavy',
    sow: 'Sow in modules and transplant; timings vary by kind (spring, summer, autumn, winter cabbages).',
    spacing: '35 to 50 cm apart.',
    ready: 'About 70 to 120 days depending on kind.',
    water: 'Keep evenly moist; a heavy watering after drought splits heads.',
    grow: 'Plant firmly and deeply. Net against caterpillars and birds. Rotate brassicas to a new bed each year.',
    sources: [rhs('vegetables', 'cabbages', 'Cabbages')],
  },
  {
    key: 'broccoli',
    name: 'Broccoli and Calabrese',
    aliases: ['broccoli', 'calabrese', 'broccolini'],
    latin: 'Brassica oleracea (Italica group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Firm, fertile soil.',
    ph: [6.5, 7.5],
    feeding: 'heavy',
    sow: 'Calabrese is sown in spring for summer heads; sprouting broccoli is sown in spring for the following spring.',
    spacing: '30 cm for calabrese, 60 cm for sprouting broccoli.',
    ready: 'Calabrese in about 60 to 90 days; cut before the flower buds open.',
    water: 'Keep moist; dry spells make heads small and early.',
    grow: 'Cutting the main head brings on side shoots for weeks.',
    sources: [rhs('vegetables', 'broccoli', 'Broccoli')],
  },
  {
    key: 'cauliflower',
    name: 'Cauliflowers',
    aliases: ['cauliflower', 'cauliflowers'],
    latin: 'Brassica oleracea (Botrytis group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Deep, firm, fertile soil that holds moisture.',
    ph: [6.5, 7.5],
    feeding: 'heavy',
    sow: 'Sow in modules and transplant without disturbing roots; any check in growth makes small, early heads (buttoning).',
    spacing: '50 to 60 cm apart.',
    ready: 'About 60 to 100 days from planting out.',
    water: 'Steady moisture throughout.',
    grow: 'The most demanding brassica. Fold leaves over a forming head to keep it white in sun.',
    sources: [rhs('vegetables', 'cauliflower', 'Cauliflowers')],
  },
  {
    key: 'brussels',
    name: 'Brussels Sprouts',
    aliases: ['brussels sprouts', 'brussels sprout', 'brussel sprouts'],
    latin: 'Brassica oleracea (Gemmifera group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Very firm, fertile soil; loose soil gives loose, open sprouts.',
    ph: [6.5, 7.5],
    feeding: 'heavy',
    sow: 'Sow in spring and transplant in early summer.',
    spacing: '60 cm apart.',
    ready: 'From about 90 days, picked from the bottom up through autumn and winter.',
    water: 'Keep moist through summer.',
    grow: 'Stake tall plants in windy gardens. Too much nitrogen also gives open sprouts.',
    sources: [rhs('vegetables', 'brussels-sprouts', 'Brussels sprouts')],
  },
  {
    key: 'kohlrabi',
    name: 'Kohlrabi',
    aliases: ['kohlrabi', 'kohl rabi'],
    latin: 'Brassica oleracea (Gongylodes group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Fertile, moisture-retentive soil.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Sow direct little and often from spring to late summer.',
    spacing: '15 to 25 cm apart.',
    ready: 'About 45 to 60 days, when the swollen stem is the size of a tennis ball.',
    water: 'Steady moisture keeps it tender.',
    grow: 'Faster and more heat-tolerant than most brassicas.',
    sources: [rhs('vegetables', 'kohl-rabi', 'Kohl rabi')],
  },
  {
    key: 'pakchoi',
    name: 'Pak Choi',
    aliases: ['pak choi', 'bok choy', 'bok choi', 'pak choy', 'chinese cabbage'],
    latin: 'Brassica rapa (Chinensis group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or light shade.',
    soil: 'Fertile, moisture-retentive soil.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Sow direct from midsummer; spring sowings bolt as days lengthen.',
    spacing: '15 to 30 cm apart.',
    ready: 'About 30 to 45 days.',
    water: 'Keep moist; dry soil makes it bolt.',
    grow: 'Cut whole heads, or pick leaves young.',
    sources: [rhs('vegetables', 'pak-choi', 'Pak choi')],
  },
  {
    key: 'rocket',
    name: 'Rocket (Arugula)',
    aliases: ['rocket', 'arugula', 'roquette'],
    latin: 'Eruca vesicaria',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun, or part shade in summer.',
    soil: 'Most soils that hold some moisture.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Sow direct little and often from spring to autumn.',
    spacing: '15 cm apart, or sown thickly and cut as young leaves.',
    ready: 'About 21 to 40 days.',
    water: 'Keep moist; heat and dry soil make it hot and quick to flower.',
    grow: 'The flowers are edible and loved by bees.',
    sources: [rhs('vegetables', 'rocket', 'Rocket')],
  },
  {
    key: 'carrot',
    name: 'Carrots',
    aliases: ['carrot', 'carrots'],
    latin: 'Daucus carota subsp. sativus',
    family: 'Carrot family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Deep, loose, stone-free soil. Fresh manure and stones make roots fork.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Sow direct, thinly, from spring to summer; they do not transplant.',
    spacing: 'Thin to 5 to 7 cm apart, rows 15 to 30 cm apart.',
    ready: 'About 70 to 80 days, earlier for baby carrots.',
    water: 'Evenly; heavy watering after drought splits roots.',
    grow: 'Carrot fly finds carrots by scent, so thin in the evening and cover with fine mesh, or grow them among onions or in a raised bed. Grow in deep containers on heavy clay.',
    sources: [rhs('vegetables', 'carrots', 'Carrots')],
  },
  {
    key: 'beetroot',
    name: 'Beetroot',
    aliases: ['beetroot', 'beet', 'beets'],
    latin: 'Beta vulgaris',
    family: 'Amaranth family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Well-drained, fertile soil. Poor in acid soil.',
    ph: [6.5, 7.5],
    feeding: 'moderate',
    sow: 'Sow direct from spring to midsummer. Each seed is a cluster, so thin to one seedling.',
    spacing: '10 cm apart.',
    ready: 'About 55 to 70 days; the leaves are edible too.',
    water: 'Evenly; dry spells make roots woody.',
    grow: 'Pull when golf-ball to tennis-ball size for tender roots.',
    sources: [rhs('vegetables', 'beetroot', 'Beetroot')],
  },
  {
    key: 'radish',
    name: 'Radishes',
    aliases: ['radish', 'radishes', 'daikon'],
    latin: 'Raphanus sativus',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or light shade.',
    soil: 'Light, moisture-retentive soil.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Sow direct every two weeks; the quickest crop there is.',
    spacing: '2 to 5 cm apart; winter radishes and daikon 15 cm.',
    ready: 'About 25 to 30 days for summer radishes.',
    water: 'Keep moist; heat and dry soil make them hot, pithy and quick to bolt.',
    grow: 'Useful sown alongside slow carrots and parsnips to mark the row.',
    sources: [rhs('vegetables', 'radishes', 'Radishes')],
  },
  {
    key: 'turnip',
    name: 'Turnips',
    aliases: ['turnip', 'turnips', 'swede', 'rutabaga'],
    latin: 'Brassica rapa (Rapifera group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or light shade.',
    soil: 'Fertile, moisture-retentive soil.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Sow direct from spring to late summer.',
    spacing: '15 to 23 cm apart.',
    ready: 'About 40 to 60 days; the tops are edible greens.',
    water: 'Keep moist.',
    grow: 'Pull young for tenderness.',
    sources: [rhs('vegetables', 'turnips', 'Turnips')],
  },
  {
    key: 'parsnip',
    name: 'Parsnips',
    aliases: ['parsnip', 'parsnips'],
    latin: 'Pastinaca sativa',
    family: 'Carrot family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Deep, stone-free soil.',
    ph: [6.5, 7.0],
    feeding: 'light',
    sow: 'Sow fresh seed direct in spring; old seed germinates poorly, and slowly even when fresh.',
    spacing: '15 cm apart.',
    ready: 'About 120 days or more; frost sweetens them.',
    water: 'Steady moisture.',
    grow: 'The sap can blister skin in sunlight, so wear gloves handling the leaves.',
    sources: [rhs('vegetables', 'parsnips', 'Parsnips')],
  },
  {
    key: 'onion',
    name: 'Onions',
    aliases: ['onion', 'onions', 'scallion', 'scallions', 'spring onion', 'spring onions', 'green onion', 'green onions'],
    latin: 'Allium cepa',
    family: 'Onion family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Firm, well-drained soil with compost worked in the season before.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Plant sets in spring or autumn, or sow seed. Bulbing is triggered by day length, so choose short-day kinds nearer the equator and long-day kinds far from it.',
    spacing: '5 to 10 cm apart, rows 30 cm apart.',
    ready: 'About 90 to 150 days; ready when the tops yellow and fall over.',
    water: 'Only in dry spells, and stop once bulbs swell.',
    grow: 'Weed carefully; onions cannot compete. Too much nitrogen late in the season delays bulbing and spoils storage.',
    sources: [rhs('vegetables', 'onions', 'Onions'), FLORIDA_VEG],
  },
  {
    key: 'shallot',
    name: 'Shallots',
    aliases: ['shallot', 'shallots'],
    latin: 'Allium cepa (Aggregatum group)',
    family: 'Onion family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Firm, well-drained soil.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Plant sets with the tip just showing, in late winter or early spring.',
    spacing: '15 to 20 cm apart.',
    ready: 'Midsummer, when the leaves yellow; each set becomes a cluster.',
    water: 'Only in long dry spells.',
    grow: 'Keep weeded, and dry the clusters in the sun before storing.',
    sources: [rhs('vegetables', 'shallots', 'Shallots')],
  },
  {
    key: 'garlic',
    name: 'Garlic',
    aliases: ['garlic'],
    latin: 'Allium sativum',
    family: 'Onion family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Well-drained soil; it rots in wet clay.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Plant single cloves, tip up, in autumn. Most kinds need several weeks below about 10°C to form cloves; in warm climates, chill cloves in the fridge before planting.',
    spacing: '15 cm apart, 2 to 3 cm deep.',
    ready: 'The following summer, when the lower leaves yellow.',
    water: 'In dry spells in spring, then stop as leaves yellow.',
    grow: 'Snap off the flower stalks of hardneck kinds (the scapes are good to eat). Dry bulbs well before storing.',
    sources: [rhs('vegetables', 'garlic', 'Garlic')],
  },
  {
    key: 'leek',
    name: 'Leeks',
    aliases: ['leek', 'leeks'],
    latin: 'Allium ampeloprasum (Porrum group)',
    family: 'Onion family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Deep, fertile, moisture-retentive soil.',
    ph: [6.0, 7.5],
    feeding: 'heavy',
    sow: 'Sow in spring and transplant when pencil-thick into deep holes made with a dibber, watering them in without filling the hole.',
    spacing: '15 cm apart.',
    ready: 'About 120 to 150 days, and hardy enough to stand through winter.',
    water: 'Keep moist.',
    grow: 'Draw soil up the stems for longer white shanks.',
    sources: [rhs('vegetables', 'leeks', 'Leeks')],
  },
  {
    key: 'peas',
    name: 'Peas',
    aliases: ['pea', 'peas', 'snow pea', 'snow peas', 'mangetout', 'sugar snap'],
    latin: 'Pisum sativum',
    family: 'Pea family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or light shade.',
    soil: 'Moisture-retentive soil with organic matter. No nitrogen feed needed.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Sow direct from early spring; in warm climates, in the cool season.',
    spacing: '5 to 8 cm apart in a wide drill, with support.',
    ready: 'About 60 to 70 days.',
    water: 'Once flowering starts, water well; that is when pods form.',
    grow: 'Bacteria in the root nodules fix nitrogen from the air, so after harvest cut the plants at soil level and leave the roots in for the next crop.',
    sources: [rhs('vegetables', 'peas', 'Peas')],
  },
  {
    key: 'greenbeans',
    name: 'Green Beans (French Beans)',
    aliases: ['green bean', 'green beans', 'french bean', 'french beans', 'bean green', 'beans snap', 'snap bean', 'snap beans', 'string beans', 'pole beans', 'bush beans', 'haricot'],
    latin: 'Phaseolus vulgaris',
    family: 'Pea family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun and shelter.',
    soil: 'Warm, well-drained soil with organic matter.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Sow direct once the soil is above about 12°C; seed rots in cold, wet soil.',
    spacing: '10 to 15 cm for bush kinds, 20 cm for climbers with support.',
    ready: 'About 50 to 65 days; pick often and young to keep them coming.',
    water: 'Well once flowering.',
    grow: 'Like peas, they fix nitrogen from the air. The same plant gives fresh pods, or dried beans if left to ripen.',
    sources: [rhs('vegetables', 'french-beans', 'French beans'), FLORIDA_VEG],
  },
  {
    key: 'runnerbeans',
    name: 'Runner Beans',
    aliases: ['runner bean', 'runner beans'],
    latin: 'Phaseolus coccineus',
    family: 'Pea family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun, out of strong wind.',
    soil: 'Deep, rich soil that holds moisture; a trench filled with compost the winter before suits them.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow direct after the last frost, or indoors a few weeks earlier.',
    spacing: '15 to 20 cm apart up tall supports.',
    ready: 'About 70 to 90 days.',
    water: 'Generously in dry weather; dry roots and hot nights make flowers drop without setting.',
    grow: 'The red flowers bring in bumblebees. Pick every few days.',
    sources: [rhs('vegetables', 'runner-beans', 'Runner beans')],
  },
  {
    key: 'broadbeans',
    name: 'Broad Beans (Fava)',
    aliases: ['broad bean', 'broad beans', 'fava', 'fava beans', 'faba'],
    latin: 'Vicia faba',
    family: 'Pea family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Most well-drained soils.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Sow direct in autumn or early spring.',
    spacing: '20 cm apart.',
    ready: 'About 80 to 100 days from a spring sowing.',
    water: 'At flowering in dry spells.',
    grow: 'Pinch out the tips once the first pods set, which removes the blackfly that cluster there. People with G6PD deficiency should not eat them.',
    sources: [rhs('vegetables', 'broad-beans', 'Broad beans')],
  },
  {
    key: 'cucumber',
    name: 'Cucumbers',
    aliases: ['cucumber', 'cucumbers', 'gherkin'],
    latin: 'Cucumis sativus',
    family: 'Squash family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun and warmth.',
    soil: 'Rich, well-drained soil full of organic matter.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Sow indoors, one seed per pot on its edge, and plant out after the last frost.',
    spacing: '45 to 60 cm apart, trained up a trellis.',
    ready: 'About 50 to 70 days.',
    water: 'Steadily; stress makes the fruit bitter.',
    grow: 'Pick often and young. Outdoor kinds need bees to pollinate; all-female greenhouse kinds do not and go bitter if pollinated.',
    sources: [rhs('vegetables', 'cucumbers', 'Cucumbers'), FLORIDA_VEG],
  },
  {
    key: 'courgette',
    name: 'Courgettes (Zucchini)',
    aliases: ['courgette', 'courgettes', 'zucchini', 'squash zucchini', 'squash summer', 'summer squash', 'marrow'],
    latin: 'Cucurbita pepo',
    family: 'Squash family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun.',
    soil: 'Rich soil, ideally a planting hole filled with compost.',
    ph: [6.0, 7.5],
    feeding: 'heavy',
    sow: 'Sow indoors or direct after the last frost.',
    spacing: '90 cm apart.',
    ready: 'About 45 to 55 days; pick at 10 to 15 cm.',
    water: 'Generously at the base.',
    grow: 'Small fruits that shrivel from the tip were not pollinated; there are more bees later in the season, or move pollen from a male flower by hand.',
    sources: [rhs('vegetables', 'courgettes', 'Courgettes'), FLORIDA_VEG],
  },
  {
    key: 'squash',
    name: 'Winter Squash and Pumpkins',
    aliases: ['squash', 'squash winter', 'winter squash', 'butternut', 'pumpkin', 'pumpkins', 'calabaza'],
    latin: 'Cucurbita maxima, C. moschata, C. pepo',
    family: 'Squash family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun.',
    soil: 'Very rich soil; they are often grown on the edge of a compost heap.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Sow indoors or direct after the last frost.',
    spacing: '90 to 150 cm apart; trailing kinds spread far.',
    ready: 'About 85 to 120 days; the stalk dries and the skin hardens so a fingernail cannot dent it.',
    water: 'Deeply at the base until fruits swell.',
    grow: 'Cure in the sun for a week or two after cutting for long storage. The Three Sisters (corn, beans and squash together) is the traditional way of growing them.',
    sources: [rhs('vegetables', 'squash', 'Squash'), rhs('vegetables', 'pumpkins', 'Pumpkins'), FLORIDA_VEG],
  },
  {
    key: 'sweetcorn',
    name: 'Sweetcorn',
    aliases: ['sweetcorn', 'sweet corn', 'corn', 'maize', 'elote'],
    latin: 'Zea mays',
    family: 'Grass family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun and shelter.',
    soil: 'Fertile, well-drained soil.',
    ph: [5.8, 7.0],
    feeding: 'heavy',
    sow: 'Sow after the last frost once the soil is warm, in a block rather than a row, since the wind carries pollen from plant to plant.',
    spacing: '35 to 45 cm apart each way.',
    ready: 'About 70 to 100 days; ready when the tassels at the cob tip turn brown and a pressed kernel shows milky juice.',
    water: 'Well at tasselling and while cobs fill.',
    grow: 'Keep sweet kinds apart from popcorn or field corn, which spoil their sweetness if they cross.',
    sources: [rhs('vegetables', 'sweetcorn', 'Sweetcorn'), FLORIDA_VEG],
  },
  {
    key: 'celery',
    name: 'Celery',
    aliases: ['celery', 'celeriac'],
    latin: 'Apium graveolens',
    family: 'Carrot family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Sun or light shade.',
    soil: 'Very rich, moisture-retentive soil.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Sow indoors on the surface (it needs light to germinate) 10 weeks before planting out.',
    spacing: '25 to 30 cm apart in a block.',
    ready: 'About 100 to 130 days.',
    water: 'Constantly moist; dry spells make stringy, bitter stems.',
    grow: 'Planting in a block shades the stems and keeps them pale and tender.',
    sources: [rhs('vegetables', 'celery', 'Celery')],
  },
  {
    key: 'asparagus',
    name: 'Asparagus',
    aliases: ['asparagus'],
    latin: 'Asparagus officinalis',
    family: 'Asparagus family',
    group: 'vegetables',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained soil cleared of perennial weeds; a bed lasts 20 years.',
    ph: [6.5, 7.5],
    feeding: 'moderate',
    sow: 'Plant one-year-old crowns in spring, spread over a ridge of soil in a trench.',
    spacing: '30 to 45 cm apart.',
    ready: 'Cut nothing the first two years, lightly in the third, then for six to eight weeks each spring.',
    water: 'In dry spells while establishing.',
    grow: 'Let the ferny growth stand after harvest to feed the crowns, and mulch with compost each spring.',
    sources: [rhs('vegetables', 'asparagus', 'Asparagus')],
  },
  {
    key: 'rhubarb',
    name: 'Rhubarb',
    aliases: ['rhubarb'],
    latin: 'Rheum × hybridum',
    family: 'Dock family',
    group: 'vegetables',
    season: 'perennial',
    sun: 'Sun or light shade.',
    soil: 'Rich, moisture-retentive soil that does not waterlog in winter.',
    ph: [5.5, 7.0],
    feeding: 'heavy',
    sow: 'Plant crowns in autumn or early spring with the buds at soil level.',
    spacing: '90 cm apart.',
    ready: 'Pull no stalks the first year, a few the second, then until early summer each year.',
    water: 'In dry spells.',
    grow: 'The leaves are poisonous (oxalic acid); eat only the stalks and compost the leaves. Needs a winter chill, so it struggles in the tropics.',
    sources: [rhs('vegetables', 'rhubarb', 'Rhubarb')],
  },
  {
    key: 'globeartichoke',
    name: 'Globe Artichokes',
    aliases: ['artichoke', 'artichokes', 'globe artichoke'],
    latin: 'Cynara cardunculus (Scolymus group)',
    family: 'Daisy family',
    group: 'vegetables',
    season: 'perennial',
    sun: 'Full sun and shelter.',
    soil: 'Fertile, well-drained soil; wet winter soil kills them.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Plant offsets or young plants in spring.',
    spacing: '90 cm apart.',
    ready: 'From the second summer, cut before the scales open.',
    water: 'In dry spells.',
    grow: 'Unpicked heads open into purple thistle flowers bees love. Replace plants every three or four years.',
    sources: [rhs('vegetables', 'globe-artichokes', 'Globe artichokes')],
  },
  {
    key: 'jerusalemartichoke',
    name: 'Jerusalem Artichokes',
    aliases: ['jerusalem artichoke', 'jerusalem artichokes', 'sunchoke', 'sunchokes'],
    latin: 'Helianthus tuberosus',
    family: 'Daisy family',
    group: 'vegetables',
    season: 'perennial',
    sun: 'Sun or light shade.',
    soil: 'Almost any soil.',
    ph: [5.8, 7.0],
    feeding: 'light',
    sow: 'Plant tubers 10 to 15 cm deep in early spring.',
    spacing: '30 cm apart.',
    ready: 'From autumn, once the stems die back.',
    water: 'Rarely needed.',
    grow: 'Any tuber left in the ground regrows, so give them a bed of their own. Tall stems make a summer windbreak.',
    sources: [rhs('vegetables', 'jerusalem-artichokes', 'Jerusalem artichokes')],
  },

  // --------------------------------------------------------------------- Herbs
  {
    key: 'basil',
    name: 'Basil',
    aliases: ['basil'],
    latin: 'Ocimum basilicum',
    family: 'Mint family',
    group: 'herbs',
    season: 'warm',
    sun: 'Full sun and warmth; cold nights blacken it.',
    soil: 'Fertile, well-drained soil or compost.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow in warmth from spring, and plant out only when nights are warm.',
    spacing: '20 to 30 cm apart.',
    ready: 'Pick from about 30 days.',
    water: 'In the morning, at the base; wet evenings encourage rot.',
    grow: 'Pinch out the tips to make bushy plants and stop it flowering. A perennial in frost-free climates.',
    sources: [rhs('herbs', 'basil', 'Basil')],
  },
  {
    key: 'parsley',
    name: 'Parsley',
    aliases: ['parsley'],
    latin: 'Petroselinum crispum',
    family: 'Carrot family',
    group: 'herbs',
    season: 'cool',
    sun: 'Sun or part shade.',
    soil: 'Fertile, moisture-retentive soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow direct or in pots; germination is slow, up to four weeks.',
    spacing: '15 to 23 cm apart.',
    ready: 'About 70 to 90 days from sowing.',
    water: 'Keep moist.',
    grow: 'A biennial: it runs to seed in its second year, when the flowers feed hoverflies.',
    sources: [rhs('herbs', 'parsley', 'Parsley')],
  },
  {
    key: 'coriander',
    name: 'Coriander (Cilantro)',
    aliases: ['coriander', 'cilantro'],
    latin: 'Coriandrum sativum',
    family: 'Carrot family',
    group: 'herbs',
    season: 'cool',
    sun: 'Sun, or light shade in heat.',
    soil: 'Well-drained, moderately fertile soil.',
    ph: [6.2, 6.8],
    feeding: 'light',
    sow: 'Sow direct every three weeks; it resents transplanting.',
    spacing: '5 to 20 cm apart.',
    ready: 'Leaves from about 30 days, seed from about 90.',
    water: 'Keep moist; dry soil makes it bolt.',
    grow: 'Heat and long days bring on flowering fast, so in hot climates it is a cool-season crop. The seeds are the spice coriander.',
    sources: [rhs('herbs', 'coriander', 'Coriander')],
  },
  {
    key: 'mint',
    name: 'Mint',
    aliases: ['mint', 'spearmint', 'peppermint', 'hierbabuena'],
    latin: 'Mentha spp.',
    family: 'Mint family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Sun or part shade.',
    soil: 'Moist, fertile soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant a rooted piece or pot in spring.',
    spacing: 'One plant fills a large pot.',
    ready: 'Pick from spring to autumn.',
    water: 'Keep moist.',
    grow: 'Spreads fast by underground runners, so grow it in a pot, sunk in the ground if you like.',
    sources: [rhs('herbs', 'mint', 'Mint')],
  },
  {
    key: 'rosemary',
    name: 'Rosemary',
    aliases: ['rosemary'],
    latin: 'Salvia rosmarinus',
    family: 'Mint family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Poor to moderate, very well-drained soil; it dies in wet winter soil.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Plant young plants or root cuttings in spring.',
    spacing: '60 to 90 cm apart.',
    ready: 'Pick all year once established.',
    water: 'Little once established.',
    grow: 'A Mediterranean shrub; rich feeding gives soft, weakly flavoured growth. Trim after flowering.',
    sources: [rhs('herbs', 'rosemary', 'Rosemary')],
  },
  {
    key: 'thyme',
    name: 'Thyme',
    aliases: ['thyme'],
    latin: 'Thymus vulgaris',
    family: 'Mint family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Lean, sharply drained soil; gravel suits it.',
    ph: [6.0, 8.0],
    feeding: 'light',
    sow: 'Plant young plants in spring.',
    spacing: '20 to 30 cm apart.',
    ready: 'Pick all year.',
    water: 'Rarely.',
    grow: 'Trim after flowering to stop it turning woody. Bees work the flowers constantly.',
    sources: [rhs('herbs', 'thyme', 'Thyme')],
  },
  {
    key: 'oregano',
    name: 'Oregano and Marjoram',
    aliases: ['oregano', 'marjoram'],
    latin: 'Origanum vulgare',
    family: 'Mint family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Lean, well-drained soil.',
    ph: [6.0, 8.0],
    feeding: 'light',
    sow: 'Plant young plants in spring, or sow on the surface.',
    spacing: '30 cm apart.',
    ready: 'Pick from early summer; flavour peaks just before flowering.',
    water: 'Rarely.',
    grow: 'Leave some to flower for the bees and butterflies.',
    sources: [rhs('herbs', 'oregano', 'Oregano')],
  },
  {
    key: 'sage',
    name: 'Sage',
    aliases: ['sage'],
    latin: 'Salvia officinalis',
    family: 'Mint family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained, not too rich.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Plant young plants in spring.',
    spacing: '45 to 60 cm apart.',
    ready: 'Pick all year.',
    water: 'Rarely once established.',
    grow: 'Prune lightly in spring and replace woody plants every few years.',
    sources: [rhs('herbs', 'sage', 'Sage')],
  },
  {
    key: 'dill',
    name: 'Dill',
    aliases: ['dill'],
    latin: 'Anethum graveolens',
    family: 'Carrot family',
    group: 'herbs',
    season: 'cool',
    sun: 'Full sun, sheltered from wind.',
    soil: 'Well-drained soil.',
    ph: [5.8, 6.5],
    feeding: 'light',
    sow: 'Sow direct every few weeks; it dislikes transplanting.',
    spacing: '20 to 30 cm apart.',
    ready: 'Leaves from about 40 days.',
    water: 'Keep moist; dry soil makes it bolt.',
    grow: 'Flowers draw in hoverflies and parasitic wasps that eat aphids. Keep it away from fennel, which it crosses with.',
    sources: [rhs('herbs', 'dill', 'Dill')],
  },
  {
    key: 'chives',
    name: 'Chives',
    aliases: ['chives', 'chive'],
    latin: 'Allium schoenoprasum',
    family: 'Onion family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Sun or light shade.',
    soil: 'Fertile, moisture-retentive soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow in spring or plant a clump.',
    spacing: '15 to 20 cm apart.',
    ready: 'Cut from about 60 days, back to 5 cm each time.',
    water: 'Keep moist.',
    grow: 'Lift and divide clumps every few years. The flowers are edible.',
    sources: [rhs('herbs', 'chives', 'Chives')],
  },
  {
    key: 'tarragon',
    name: 'Tarragon',
    aliases: ['tarragon'],
    latin: 'Artemisia dracunculus',
    family: 'Daisy family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained, not too rich.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'French tarragon sets no seed; buy a plant or take root cuttings. Seed sold as tarragon is the coarser Russian kind.',
    spacing: '45 to 60 cm apart.',
    ready: 'Pick from early summer.',
    water: 'Little.',
    grow: 'Divide every few years to keep it vigorous.',
    sources: [rhs('herbs', 'tarragon', 'Tarragon')],
  },
  {
    key: 'lemonbalm',
    name: 'Lemon Balm',
    aliases: ['lemon balm', 'melissa'],
    latin: 'Melissa officinalis',
    family: 'Mint family',
    group: 'herbs',
    season: 'perennial',
    sun: 'Sun or part shade.',
    soil: 'Most soils.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Sow or plant in spring.',
    spacing: '45 cm apart.',
    ready: 'Pick from early summer.',
    water: 'In dry spells.',
    grow: 'Seeds itself freely; cut back after flowering to stop it spreading. Melissa means honeybee, for good reason.',
    sources: [rhs('herbs', 'lemon-balm', 'Lemon balm')],
  },

  // --------------------------------------------------------------------- Fruit
  {
    key: 'strawberry',
    name: 'Strawberries',
    aliases: ['strawberry', 'strawberries'],
    latin: 'Fragaria × ananassa',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Fertile, well-drained soil, slightly acid.',
    ph: [5.5, 6.5],
    feeding: 'moderate',
    sow: 'Plant runners or young plants in late summer or spring, with the crown at soil level.',
    spacing: '35 to 45 cm apart.',
    ready: 'The first summer after planting.',
    water: 'Regularly while fruit swells, at the base.',
    grow: 'Straw under the fruit keeps it clean. Replace plants every three or four years with rooted runners, on a fresh bed.',
    sources: [rhs('fruit', 'strawberries', 'Strawberries')],
  },
  {
    key: 'raspberry',
    name: 'Raspberries',
    aliases: ['raspberry', 'raspberries'],
    latin: 'Rubus idaeus',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Sun or light shade.',
    soil: 'Moisture-retentive, well-drained, slightly acid soil.',
    ph: [5.5, 6.5],
    feeding: 'moderate',
    sow: 'Plant canes in winter, then cut them to 25 cm.',
    spacing: '40 to 45 cm apart along a wire support.',
    ready: 'Summer kinds the second summer, autumn kinds the first autumn.',
    water: 'In dry spells, especially as fruit swells.',
    grow: 'Mulch thickly; the roots are shallow. Summer kinds fruit on last year’s canes, autumn kinds on this year’s.',
    sources: [rhs('fruit', 'raspberries', 'Raspberries')],
  },
  {
    key: 'blackberry',
    name: 'Blackberries',
    aliases: ['blackberry', 'blackberries'],
    latin: 'Rubus fruticosus agg.',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Sun or part shade.',
    soil: 'Almost any soil that does not waterlog.',
    ph: [5.5, 7.0],
    feeding: 'moderate',
    sow: 'Plant in winter against wires or a fence.',
    spacing: '2 to 4 metres apart for vigorous kinds.',
    ready: 'Late summer, from the second year.',
    water: 'In dry spells.',
    grow: 'Fruit comes on last year’s canes; cut them out after fruiting and tie in the new ones.',
    sources: [rhs('fruit', 'blackberries', 'Blackberries')],
  },
  {
    key: 'blueberry',
    name: 'Blueberries',
    aliases: ['blueberry', 'blueberries'],
    latin: 'Vaccinium corymbosum',
    family: 'Heather family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Sun or part shade.',
    soil: 'Acid soil only; in a chalky or alkaline garden, grow them in pots of ericaceous compost.',
    ph: [4.5, 5.5],
    feeding: 'light',
    sow: 'Plant in autumn or winter. Two different kinds together give heavier crops.',
    spacing: '1.5 metres apart.',
    ready: 'Midsummer onward, from the second or third year.',
    water: 'With rainwater; hard tap water raises the pH over time.',
    grow: 'Mulch with pine needles or composted bark. Feed with leafmould, pine-needle mulch and rainwater, never lime.',
    sources: [rhs('fruit', 'blueberries', 'Blueberries')],
  },
  {
    key: 'gooseberry',
    name: 'Gooseberries',
    aliases: ['gooseberry', 'gooseberries'],
    latin: 'Ribes uva-crispa',
    family: 'Currant family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Sun or part shade.',
    soil: 'Moisture-retentive, well-drained soil.',
    ph: [6.0, 6.7],
    feeding: 'moderate',
    sow: 'Plant in winter.',
    spacing: '1.2 to 1.5 metres apart.',
    ready: 'Early to midsummer, from the second year.',
    water: 'In dry spells.',
    grow: 'Prune to an open goblet shape for air and easy picking.',
    sources: [rhs('fruit', 'gooseberries', 'Gooseberries')],
  },
  {
    key: 'blackcurrant',
    name: 'Blackcurrants',
    aliases: ['blackcurrant', 'blackcurrants', 'black currant', 'black currants'],
    latin: 'Ribes nigrum',
    family: 'Currant family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Sun.',
    soil: 'Rich, moisture-retentive soil.',
    ph: [6.0, 6.5],
    feeding: 'heavy',
    sow: 'Plant deeper than before, in winter, to encourage shoots from below ground.',
    spacing: '1.5 metres apart.',
    ready: 'Midsummer.',
    water: 'In dry spells.',
    grow: 'Fruits on young wood, so cut out a third of the oldest stems each winter.',
    sources: [rhs('fruit', 'blackcurrants', 'Blackcurrants')],
  },
  {
    key: 'redcurrant',
    name: 'Redcurrants and Whitecurrants',
    aliases: ['redcurrant', 'redcurrants', 'red currant', 'red currants', 'whitecurrant', 'white currants'],
    latin: 'Ribes rubrum',
    family: 'Currant family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Sun or part shade.',
    soil: 'Well-drained soil.',
    ph: [6.0, 6.7],
    feeding: 'moderate',
    sow: 'Plant in winter.',
    spacing: '1.2 to 1.5 metres apart.',
    ready: 'Midsummer.',
    water: 'In dry spells.',
    grow: 'Can be trained flat against a wall. Net against birds.',
    sources: [rhs('fruit', 'redcurrants', 'Redcurrants')],
  },
  {
    key: 'apple',
    name: 'Apples',
    aliases: ['apple', 'apples'],
    latin: 'Malus domestica',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Deep, well-drained soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant in winter. The rootstock decides the size of tree, and most kinds need a pollination partner that flowers at the same time.',
    spacing: 'From 1.5 metres for dwarf rootstocks to 6 for vigorous ones.',
    ready: 'Late summer to autumn by kind, from about the third year.',
    water: 'Young trees in dry spells.',
    grow: 'Thin crowded fruitlets in early summer for larger fruit and to even out biennial bearing. Needs a winter chill, so choose low-chill kinds in warm climates.',
    sources: [rhs('fruit', 'apples', 'Apples')],
  },
  {
    key: 'pear',
    name: 'Pears',
    aliases: ['pear', 'pears'],
    latin: 'Pyrus communis',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, sheltered; they flower early.',
    soil: 'Deep, moisture-retentive soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant in winter, with a pollination partner.',
    spacing: '3 to 5 metres apart depending on rootstock.',
    ready: 'Pick while still firm and ripen indoors.',
    water: 'In dry spells.',
    grow: 'Frost at flowering is the usual reason for no crop.',
    sources: [rhs('fruit', 'pears', 'Pears')],
  },
  {
    key: 'plum',
    name: 'Plums',
    aliases: ['plum', 'plums', 'damson', 'gage'],
    latin: 'Prunus domestica',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, sheltered.',
    soil: 'Moisture-retentive, well-drained soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant in winter. Many kinds are self-fertile.',
    spacing: '3 to 5 metres apart.',
    ready: 'Late summer.',
    water: 'In dry spells.',
    grow: 'Prune only in summer, which limits silver leaf disease entering the cuts.',
    sources: [rhs('fruit', 'plums', 'Plums')],
  },
  {
    key: 'cherry',
    name: 'Cherries',
    aliases: ['cherry', 'cherries'],
    latin: 'Prunus avium, P. cerasus',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun; sour cherries tolerate some shade.',
    soil: 'Deep, well-drained soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant in winter; check whether the kind is self-fertile.',
    spacing: '3 to 5 metres apart on a dwarfing rootstock.',
    ready: 'Early to midsummer.',
    water: 'Evenly as fruit swells; rain on ripe fruit splits it.',
    grow: 'Net against birds. Prune in summer, like plums.',
    sources: [rhs('fruit', 'cherries', 'Cherries')],
  },
  {
    key: 'apricot',
    name: 'Apricots',
    aliases: ['apricot', 'apricots'],
    latin: 'Prunus armeniaca',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, a warm wall in cool climates.',
    soil: 'Deep, well-drained, slightly alkaline to neutral soil.',
    ph: [6.5, 7.5],
    feeding: 'moderate',
    sow: 'Plant in winter; most are self-fertile.',
    spacing: '4 to 5 metres, or fan-trained against a wall.',
    ready: 'Midsummer.',
    water: 'Well as fruit swells.',
    grow: 'Flowers very early, so hand-pollinate with a soft brush when few insects are about.',
    sources: [rhs('fruit', 'apricots', 'Apricots')],
  },
  {
    key: 'fig',
    name: 'Figs',
    aliases: ['fig', 'figs'],
    latin: 'Ficus carica',
    family: 'Mulberry family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, a warm wall in cool climates.',
    soil: 'Well-drained soil; rich soil gives leaves rather than fruit, so roots are often restricted.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Plant in spring. The common kinds set fruit with no pollinator.',
    spacing: '3 to 5 metres.',
    ready: 'Late summer; ripe when soft and drooping.',
    water: 'Regularly as fruit swells, especially in pots.',
    grow: 'The sap irritates skin in sunlight. In the tropics figs fruit through much of the year.',
    sources: [rhs('fruit', 'figs', 'Figs'), edis('MG214', 'Fig growing in the Florida home landscape')],
  },
  {
    key: 'grape',
    name: 'Grapes',
    aliases: ['grape', 'grapes'],
    latin: 'Vitis vinifera',
    family: 'Grape family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, the warmest spot available.',
    soil: 'Deep, well-drained soil; not too rich.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant in winter against wires, a pergola or a wall.',
    spacing: '1.2 to 1.5 metres along wires.',
    ready: 'Late summer to autumn, from the third year.',
    water: 'Young vines in dry spells.',
    grow: 'Prune hard in winter; grapes fruit on the current season’s shoots.',
    sources: [rhs('fruit', 'grapes', 'Grapes')],
  },
  {
    key: 'kiwi',
    name: 'Kiwifruit',
    aliases: ['kiwi', 'kiwifruit', 'kiwi fruit'],
    latin: 'Actinidia deliciosa',
    family: 'Kiwifruit family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, sheltered.',
    soil: 'Deep, fertile, well-drained, slightly acid soil.',
    ph: [5.5, 7.0],
    feeding: 'moderate',
    sow: 'Plant in spring. Most kinds need a male and a female plant; a few are self-fertile.',
    spacing: '3 to 5 metres along strong supports.',
    ready: 'Autumn, from about the fourth year.',
    water: 'Generously in summer.',
    grow: 'A very vigorous climber; prune in winter and summer.',
    sources: [rhs('fruit', 'kiwi', 'Kiwi')],
  },
  {
    key: 'melon',
    name: 'Melons',
    aliases: ['melon', 'melons', 'cantaloupe', 'honeydew', 'muskmelon', 'watermelon', 'watermelons'],
    latin: 'Cucumis melo',
    family: 'Squash family',
    group: 'fruit',
    season: 'warm',
    sun: 'Full sun and heat; a greenhouse in cool climates.',
    soil: 'Rich, well-drained soil.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Sow in warmth and plant out when nights are warm.',
    spacing: '90 cm apart.',
    ready: 'About 80 to 100 days; ripe melons smell sweet and the stalk cracks away.',
    water: 'Generously until fruits are full size, then less, for sweetness.',
    grow: 'Limit each plant to a few fruits in short seasons. Watermelon (Citrullus lanatus) is grown the same way with more room and heat.',
    sources: [rhs('fruit', 'melons', 'Melons'), FLORIDA_VEG],
  },
  {
    key: 'citrus',
    name: 'Oranges and Mandarins',
    aliases: ['orange', 'oranges', 'mandarin', 'mandarins', 'tangerine', 'tangerines', 'grapefruit', 'clementine', 'citrus'],
    latin: 'Citrus sinensis, C. reticulata',
    family: 'Citrus family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun; in frosty climates, in pots brought under cover for winter.',
    soil: 'Well-drained soil or a gritty citrus compost in pots.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Plant grafted trees in spring.',
    spacing: '4 to 6 metres in the ground.',
    ready: 'Fruit takes 6 to 12 months to ripen on the tree.',
    water: 'Deeply, then let the top dry; waterlogging rots roots.',
    grow: 'Feed through the growing season with compost, a mulch of leaves and a monthly liquid feed of comfrey or fish amino acid. Citrus show shortages of magnesium, iron, zinc and manganese more readily than most plants.',
    sources: [rhs('fruit', 'citrus', 'Citrus'), edis('HS132', 'Citrus culture in the home landscape')],
  },

  // ------------------------------------------------- Warm climate and tropical
  {
    key: 'lemon',
    name: 'Lemons',
    aliases: ['lemon', 'lemons'],
    latin: 'Citrus limon',
    family: 'Citrus family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained soil; lemons tolerate poorer soil than oranges.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Plant grafted trees in the warm season.',
    spacing: '4 to 6 metres.',
    ready: 'Several flushes of fruit a year in warm climates.',
    water: 'Deeply and regularly; never waterlogged.',
    grow: 'The most frost-tender common citrus. Prune out thorny shoots from below the graft.',
    sources: [edis('HS402', 'Lemon growing in the home landscape'), edis('HS132', 'Citrus culture in the home landscape')],
  },
  {
    key: 'lime',
    name: 'Limes',
    aliases: ['lime', 'limes', 'key lime', 'persian lime', 'limon'],
    latin: 'Citrus × aurantiifolia, C. × latifolia',
    family: 'Citrus family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained soil; very sensitive to waterlogging.',
    ph: [6.0, 7.5],
    feeding: 'heavy',
    sow: 'Plant in the warm season.',
    spacing: '4 to 5 metres.',
    ready: 'Fruit through much of the year in the tropics.',
    water: 'Regularly in dry seasons.',
    grow: 'Key (Mexican) limes are the most cold-sensitive; Persian (Tahiti) limes are seedless and larger. On limestone soils they show iron and zinc shortage readily.',
    sources: [edis('CH092', 'Key lime growing in the home landscape'), edis('HS132', 'Citrus culture in the home landscape')],
  },
  {
    key: 'mango',
    name: 'Mangoes',
    aliases: ['mango', 'mangoes', 'mangos'],
    latin: 'Mangifera indica',
    family: 'Cashew family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Deep, well-drained soil of almost any texture.',
    ph: [5.5, 7.5],
    feeding: 'moderate',
    sow: 'Plant grafted trees at the start of the rainy or warm season; seedlings take years longer to fruit.',
    spacing: '7 to 10 metres, less for small kinds kept pruned.',
    ready: 'Grafted trees from about the third or fourth year; fruit ripens 100 to 150 days after flowering.',
    water: 'Young trees regularly; mature trees flower best after a dry, cooler spell.',
    grow: 'Rain at flowering brings anthracnose, the black spotting on flowers and fruit, so dry-season flowering kinds suit humid coasts. Prune after harvest to keep the tree low.',
    sources: [edis('MG216', 'Mango growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'banana',
    name: 'Bananas and Plantains',
    aliases: ['banana', 'bananas', 'plantain', 'plantains', 'platano'],
    latin: 'Musa spp.',
    family: 'Banana family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun, sheltered from wind.',
    soil: 'Deep, rich, well-drained soil full of organic matter.',
    ph: [5.5, 7.0],
    feeding: 'heavy',
    sow: 'Plant suckers (pups) or tissue-cultured plants in the warm season.',
    spacing: '3 to 4 metres.',
    ready: 'About 9 to 15 months from planting to a bunch; cut it when the fruits fill out and lose their angles.',
    water: 'Large amounts; the leaves are mostly water.',
    grow: 'Each stem fruits once. After harvest cut it down, chop it as mulch around the base, and keep one or two suckers to follow. Heavy feeders of potassium above all.',
    sources: [edis('MG040', 'Banana growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'papaya',
    name: 'Papayas',
    aliases: ['papaya', 'papayas', 'pawpaw'],
    latin: 'Carica papaya',
    family: 'Papaya family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Very well-drained soil; a day of standing water can kill it.',
    ph: [5.5, 7.0],
    feeding: 'heavy',
    sow: 'Sow fresh seed in the warm season, several to a spot, and keep the strongest.',
    spacing: '2.5 to 3 metres.',
    ready: 'About 6 to 11 months from planting.',
    water: 'Regularly, never waterlogged.',
    grow: 'Plants are male, female or bisexual; bisexual plants fruit on their own, and a female needs a male nearby. Short-lived, so replant every few years.',
    sources: [edis('MG054', 'Papaya growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'avocado',
    name: 'Avocados',
    aliases: ['avocado', 'avocados', 'aguacate'],
    latin: 'Persea americana',
    family: 'Laurel family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Deep, very well-drained soil; root rot follows any waterlogging.',
    ph: [5.5, 7.0],
    feeding: 'moderate',
    sow: 'Plant grafted trees on a mound in the warm season.',
    spacing: '6 to 9 metres.',
    ready: 'Grafted trees from about the third or fourth year. Fruit ripens only after picking.',
    water: 'Deeply and regularly, letting the surface dry between.',
    grow: 'Leave fallen leaves as mulch under the tree; they suppress root rot. Flower types A and B shed pollen at different times, so one of each sets more fruit.',
    sources: [edis('MG213', 'Avocado growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'pineapple',
    name: 'Pineapples',
    aliases: ['pineapple', 'pineapples', 'pina'],
    latin: 'Ananas comosus',
    family: 'Bromeliad family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun or light shade.',
    soil: 'Sandy, well-drained, acid soil.',
    ph: [4.5, 6.5],
    feeding: 'moderate',
    sow: 'Plant the leafy top of a bought fruit, dried for a few days, or a sucker.',
    spacing: '30 to 60 cm.',
    ready: 'About 18 to 24 months to fruit.',
    water: 'Moderately; the leaf bases hold water.',
    grow: 'Grows well in pots. After fruiting, suckers give the next crop.',
    sources: [edis('MG055', 'Pineapple growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'guava',
    name: 'Guavas',
    aliases: ['guava', 'guavas', 'guayaba'],
    latin: 'Psidium guajava',
    family: 'Myrtle family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Most well-drained soils.',
    ph: [4.5, 7.0],
    feeding: 'moderate',
    sow: 'Plant in the warm season.',
    spacing: '4 to 6 metres.',
    ready: 'From the second or third year; ripe fruit softens and smells strongly.',
    water: 'Regularly while fruiting.',
    grow: 'Tough and quick. Can seed itself widely and become weedy in some tropical places.',
    sources: [edis('MG045', 'Guava growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'pomegranate',
    name: 'Pomegranates',
    aliases: ['pomegranate', 'pomegranates', 'granada'],
    latin: 'Punica granatum',
    family: 'Loosestrife family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun and heat.',
    soil: 'Well-drained soil; tolerates alkaline soil.',
    ph: [5.5, 7.5],
    feeding: 'light',
    sow: 'Plant in spring or at the start of the warm season.',
    spacing: '4 to 5 metres.',
    ready: 'About 5 to 7 months after flowering.',
    water: 'Drought-tolerant, but steady watering stops fruit splitting.',
    grow: 'A shrub or small tree; prune suckers from the base.',
    sources: [edis('MG056', 'Pomegranate growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'lychee',
    name: 'Lychees',
    aliases: ['lychee', 'lychees', 'litchi'],
    latin: 'Litchi chinensis',
    family: 'Soapberry family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun, sheltered from wind.',
    soil: 'Deep, well-drained, slightly acid soil.',
    ph: [5.0, 6.5],
    feeding: 'moderate',
    sow: 'Plant air-layered trees in the warm season.',
    spacing: '6 to 9 metres.',
    ready: 'From about the fourth or fifth year.',
    water: 'Regularly, but a dry, cool spell before flowering sets the crop.',
    grow: 'Irregular bearers without that cool, dry winter. Shows iron and zinc shortage on alkaline soils.',
    sources: [edis('MG051', 'Lychee growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'longan',
    name: 'Longans',
    aliases: ['longan', 'longans'],
    latin: 'Dimocarpus longan',
    family: 'Soapberry family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained, slightly acid soil.',
    ph: [5.5, 6.5],
    feeding: 'moderate',
    sow: 'Plant air-layered or grafted trees in the warm season.',
    spacing: '6 to 9 metres.',
    ready: 'From about the third to fifth year.',
    water: 'Regularly, less before flowering.',
    grow: 'Like lychee, flowers best after a cool, dry spell.',
    sources: [edis('MG049', 'Longan growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'loquat',
    name: 'Loquats',
    aliases: ['loquat', 'loquats', 'nispero'],
    latin: 'Eriobotrya japonica',
    family: 'Rose family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun or light shade.',
    soil: 'Most well-drained soils.',
    ph: [5.5, 7.5],
    feeding: 'moderate',
    sow: 'Plant grafted trees in the warm season.',
    spacing: '5 to 7 metres.',
    ready: 'Late winter to spring, from about the third year.',
    water: 'In dry spells while fruiting.',
    grow: 'Flowers in autumn and winter, feeding bees when little else does.',
    sources: [edis('MG050', 'Loquat growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'sapodilla',
    name: 'Sapodillas (Chicozapote)',
    aliases: ['sapodilla', 'sapodillas', 'chicozapote', 'chico'],
    latin: 'Manilkara zapota',
    family: 'Sapote family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Almost any well-drained soil; tolerates salt spray and limestone.',
    ph: [6.0, 8.0],
    feeding: 'light',
    sow: 'Plant grafted trees in the warm season.',
    spacing: '7 to 9 metres.',
    ready: 'From about the third to fifth year; pick mature and ripen off the tree.',
    water: 'Drought-tolerant once established.',
    grow: 'Slow-growing and long-lived. The sap is chicle, the original chewing gum.',
    sources: [edis('MG057', 'Sapodilla growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'sugarapple',
    name: 'Sugar Apples (Anona)',
    aliases: ['sugar apple', 'sugar apples', 'sweetsop', 'anona', 'custard apple'],
    latin: 'Annona squamosa',
    family: 'Custard apple family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained soil; tolerates poor, rocky ground.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Plant in the warm season.',
    spacing: '4 to 6 metres.',
    ready: 'From about the third year; ripe when the segments separate and yellow between.',
    water: 'Drought-tolerant; water as fruit sets.',
    grow: 'Small beetles pollinate it, so fruit set improves with a little hand pollination in dry climates.',
    sources: [edis('MG330', 'Sugar apple growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'jackfruit',
    name: 'Jackfruit',
    aliases: ['jackfruit', 'jack fruit', 'yaca'],
    latin: 'Artocarpus heterophyllus',
    family: 'Mulberry family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Deep, well-drained soil; will not tolerate waterlogging.',
    ph: [5.0, 7.5],
    feeding: 'moderate',
    sow: 'Plant grafted trees in the warm season.',
    spacing: '8 to 10 metres.',
    ready: 'From about the third or fourth year for grafted trees.',
    water: 'Regularly while young.',
    grow: 'Fruit can weigh over 20 kg and grows straight from the trunk. Prune to keep the tree low enough to reach.',
    sources: [edis('MG370', 'Jackfruit growing in the Florida home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'passionfruit',
    name: 'Passion Fruit (Maracuyá)',
    aliases: ['passion fruit', 'passionfruit', 'maracuya', 'granadilla'],
    latin: 'Passiflora edulis',
    family: 'Passionflower family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Well-drained soil rich in organic matter.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Plant in the warm season against a strong trellis or fence.',
    spacing: '3 to 5 metres along the support.',
    ready: 'From about 12 to 18 months; ripe fruit drops.',
    water: 'Regularly; drought drops fruit.',
    grow: 'Yellow kinds mostly need carpenter bees or hand pollination to set fruit, purple kinds set their own. Vines are short-lived, so replant every few years.',
    sources: [edis('HS1406', 'Passion fruit growing in the home landscape'), TROPICAL_FRUIT],
  },
  {
    key: 'sweetpotato',
    name: 'Sweet Potatoes (Camote)',
    aliases: ['sweet potato', 'sweet potatoes', 'sweetpotato', 'camote', 'boniato', 'kumara'],
    latin: 'Ipomoea batatas',
    family: 'Morning glory family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun and heat.',
    soil: 'Light, well-drained soil; rich soil gives leaves rather than roots.',
    ph: [5.5, 6.5],
    feeding: 'light',
    sow: 'Plant rooted shoots (slips) once the soil is warm.',
    spacing: '30 to 45 cm apart.',
    ready: 'About 90 to 120 days.',
    water: 'Regularly until established, then less.',
    grow: 'The young leaves are a leafy green in their own right. Cure dug roots somewhere warm for a week for sweetness and storage.',
    sources: [rhs('vegetables', 'sweet-potatoes', 'Sweet potatoes'), FLORIDA_VEG],
  },
  {
    key: 'okra',
    name: 'Okra',
    aliases: ['okra', 'bamia'],
    latin: 'Abelmoschus esculentus',
    family: 'Mallow family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun and heat.',
    soil: 'Well-drained, fertile soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow direct once the soil is above about 20°C; soak seed overnight first.',
    spacing: '30 to 45 cm apart.',
    ready: 'About 50 to 65 days; pick pods at 5 to 10 cm every day or two.',
    water: 'Deeply in dry spells.',
    grow: 'Pods left on turn woody and stop new ones. The flowers bring bees in.',
    sources: [rhs('vegetables', 'okra', 'Okra'), FLORIDA_VEG],
  },
  {
    key: 'cassava',
    name: 'Cassava (Yuca)',
    aliases: ['cassava', 'yuca', 'manioc'],
    latin: 'Manihot esculenta',
    family: 'Spurge family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun.',
    soil: 'Well-drained soil; grows in poor, acid soils where little else will.',
    ph: [5.5, 6.5],
    feeding: 'light',
    sow: 'Plant stem cuttings 20 to 30 cm long in the warm season.',
    spacing: '90 cm apart.',
    ready: 'About 8 to 12 months.',
    water: 'Drought-tolerant once established.',
    grow: 'The roots contain compounds that release cyanide, so they are always peeled and cooked, never eaten raw. Too much nitrogen gives leaves rather than roots.',
    sources: [FLORIDA_VEG],
  },
  {
    key: 'chayote',
    name: 'Chayote',
    aliases: ['chayote', 'chayotes', 'christophene', 'mirliton'],
    latin: 'Sechium edule',
    family: 'Squash family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun or light shade.',
    soil: 'Rich, well-drained soil.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant a whole mature fruit, sprouted end angled down, half-buried.',
    spacing: 'One vine covers a large trellis.',
    ready: 'From about 4 months; pick young and tender.',
    water: 'Regularly.',
    grow: 'A vigorous perennial vine in frost-free places; the shoots and root are edible too.',
    sources: [FLORIDA_VEG],
  },
  {
    key: 'malanga',
    name: 'Malanga and Taro',
    aliases: ['malanga', 'taro', 'yautia', 'dasheen', 'eddo'],
    latin: 'Xanthosoma sagittifolium, Colocasia esculenta',
    family: 'Arum family',
    group: 'warm',
    season: 'warm',
    sun: 'Sun or part shade.',
    soil: 'Moist, rich soil; taro tolerates wet ground, malanga needs drainage.',
    ph: [5.5, 6.5],
    feeding: 'moderate',
    sow: 'Plant small corms or top cuttings in the warm season.',
    spacing: '60 to 90 cm apart.',
    ready: 'About 9 to 12 months.',
    water: 'Plenty.',
    grow: 'The corms and leaves hold calcium oxalate crystals that irritate the mouth and throat raw, so they are always cooked.',
    sources: [FLORIDA_VEG],
  },
  {
    key: 'roselle',
    name: 'Roselle (Jamaica)',
    aliases: ['roselle', 'jamaica', 'flor de jamaica', 'hibiscus'],
    latin: 'Hibiscus sabdariffa',
    family: 'Mallow family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun.',
    soil: 'Most well-drained soils.',
    ph: [6.0, 7.5],
    feeding: 'moderate',
    sow: 'Sow at the start of the warm season. It flowers only as days shorten, so plants sown late flower small.',
    spacing: '90 cm apart.',
    ready: 'Pick the red calyces about 10 days after the flowers open.',
    water: 'Regularly while young.',
    grow: 'The calyces make agua de jamaica; the young leaves are eaten as a sour green.',
    sources: [FLORIDA_VEG],
  },
  {
    key: 'malabarspinach',
    name: 'Malabar Spinach',
    aliases: ['malabar spinach', 'basella'],
    latin: 'Basella alba',
    family: 'Basella family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun or light shade.',
    soil: 'Moist, fertile soil.',
    ph: [5.5, 7.5],
    feeding: 'moderate',
    sow: 'Sow or root cuttings in the warm season.',
    spacing: '30 cm apart along a trellis.',
    ready: 'Pick from about 70 days.',
    water: 'Keep moist.',
    grow: 'A heat-loving climbing green for when true spinach bolts.',
    sources: [FLORIDA_VEG],
  },
  {
    key: 'pigeonpea',
    name: 'Pigeon Peas (Gandul)',
    aliases: ['pigeon pea', 'pigeon peas', 'gandul', 'gandules', 'toor', 'arhar'],
    latin: 'Cajanus cajan',
    family: 'Pea family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun.',
    soil: 'Most well-drained soils, including poor ones.',
    ph: [5.0, 7.0],
    feeding: 'light',
    sow: 'Sow direct in the warm season.',
    spacing: '60 to 90 cm apart.',
    ready: 'Green pods from about 4 to 5 months.',
    water: 'Drought-tolerant.',
    grow: 'A short-lived shrub that fixes nitrogen, so it doubles as living fertiliser, a windbreak and chop-and-drop mulch.',
    sources: [FLORIDA_VEG],
  },
  {
    key: 'lemongrass',
    name: 'Lemongrass',
    aliases: ['lemongrass', 'lemon grass', 'zacate limon', 'te de limon'],
    latin: 'Cymbopogon citratus',
    family: 'Grass family',
    group: 'warm',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Fertile, moist, well-drained soil.',
    ph: [5.5, 7.5],
    feeding: 'moderate',
    sow: 'Root a stalk from the shop in water, then plant it out.',
    spacing: '60 to 90 cm apart.',
    ready: 'Cut stalks from about 4 months.',
    water: 'Regularly.',
    grow: 'Frost-tender; in cold climates, keep in a pot under cover for winter. Divide large clumps.',
    sources: [rhs('herbs', 'lemongrass', 'Lemongrass')],
  },
  // Cannabis is a crop guide and nothing else (lib/cropSigns.ts says why
  // it stays on the adult side).
  {
    key: 'cannabis',
    name: 'Cannabis',
    aliases: ['cannabis', 'hemp', 'marijuana'],
    latin: 'Cannabis sativa',
    family: 'Hemp family (Cannabaceae)',
    group: 'herbs',
    season: 'warm',
    sun: 'Full sun.',
    soil: 'Deep, loose, well-drained soil; it does poorly on wet, heavy clay and in soil that crusts or packs down.',
    ph: [6.0, 7.0],
    feeding: 'heavy',
    sow: 'Sow 1 to 2 cm deep once the soil is warm, from mid spring to early summer, or plant out young plants.',
    spacing: 'Plants grown for flower 1.2 to 1.5 m apart each way.',
    ready: 'Flowers ripen in autumn, as the days shorten.',
    water: 'Steadily, at the base, by drip where you can; never leave the roots standing wet.',
    grow: 'It flowers once the days fall below about 12 hours of light. Growing it is regulated or against the law in many places, so check the law where you live before you sow.',
    sources: [
      { label: 'Penn State Extension: Industrial hemp production', url: 'https://extension.psu.edu/industrial-hemp-production' },
      { label: 'Cornell: Hemp', url: 'https://hemp.cals.cornell.edu/' },
    ],
  },
  {
    key: 'hops',
    name: 'Hops',
    aliases: ['hops', 'hop'],
    latin: 'Humulus lupulus',
    family: 'Hemp family (Cannabaceae)',
    group: 'herbs',
    season: 'perennial',
    sun: 'Full sun.',
    soil: 'Deep, well-drained soil rich in organic matter.',
    ph: [5.7, 7.5],
    feeding: 'heavy',
    sow: 'Plant a rooted cutting or a piece of rhizome in spring.',
    spacing: '1 to 1.5 m apart, each with a tall string or pole to climb.',
    ready: 'Pick cones in late summer, once they feel papery and the yellow powder inside smells strongly.',
    water: 'Deeply in summer while the bines grow fast; go easy in spring while the soil is cool and wet.',
    grow: 'Bines climb 5 m or more each year and die back to the crown in winter. Train two or three bines up each string and cut the rest away.',
    sources: [
      { label: 'USA Hops field guide: Nutrient disorders of hop', url: 'https://www.usahops.org/cabinet/data/9.pdf' },
      { label: 'Oregon State University: Hops fertilizer guide (FG 79)', url: 'https://extension.oregonstate.edu/catalog/fg-79-hops-fertilizer-guide' },
    ],
  },
  {
    key: 'peach',
    name: 'Peaches and Nectarines',
    aliases: ['peach', 'peaches', 'nectarine', 'nectarines'],
    latin: 'Prunus persica',
    family: 'Rose family',
    group: 'fruit',
    season: 'perennial',
    sun: 'Full sun, at least 8 hours a day, against a warm wall or under cover in a cool climate.',
    soil: 'Well-drained soil; on heavy or wet ground plant on a raised bed 6 to 10 inches high.',
    ph: [6.5, 7.5],
    feeding: 'moderate',
    sow: 'Plant a young tree in winter. Most peaches set fruit with pollen from the same tree, but flowers that open before the bees are about need a soft brush passed from flower to flower.',
    spacing: 'Trees 12 to 16 feet apart, or a fan trained on a warm wall.',
    ready: 'Summer, once the fruit gives slightly near the stalk and comes away with a gentle lift.',
    water: 'About 30 inches of water over the season, given evenly; a dry spell followed by heavy watering splits fruit and drops it unripe.',
    grow: 'Frost on the open flowers is the usual reason for no crop, so cover the tree on frosty nights at blossom time. Keep the rain off a fan in late winter to keep leaf curl away.',
    sources: [
      rhs('fruit', 'peaches', 'Peaches and nectarines'),
      { label: 'Utah State University: Peaches in the garden', url: 'https://extension.usu.edu/yardandgarden/research/peaches-in-the-garden' },
    ],
  },
  {
    key: 'drybeans',
    name: 'Dry Beans',
    aliases: [
      'beans black', 'black beans', 'beans black turtle', 'beans kidney', 'bean red kidney', 'kidney bean', 'kidney beans',
      'beans pinto', 'pinto beans', 'beans navy', 'navy beans', 'beans great northern', 'beans white', 'beans small white',
      'beans pink', 'beans cranberry', 'beans french', 'beans yellow', 'dried beans', 'dry beans', 'borlotti',
    ],
    latin: 'Phaseolus vulgaris',
    family: 'Pea family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun.',
    soil: 'Well-drained soil that does not crust; a crust on clay can stop the seedlings coming up.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Sow outdoors 1 inch deep once the soil is above 60°F; seedlings come up in 7 to 10 days at 65 to 85°F.',
    spacing: '2 to 3 inches apart in rows 18 to 24 inches apart.',
    ready: 'Leave the pods on the plant until they are dry and rattle, then pull the plants and finish drying them under cover.',
    water: 'Most of all at flowering and while the pods fill; too much water rots the roots.',
    grow: 'The same kinds of bean as green beans, grown on until the seed inside is dry. Extra nitrogen gives leaves and delays the flowers, and above 95°F in dry weather the flowers drop.',
    sources: [
      { label: 'Utah State University: Beans in the garden', url: 'https://extension.usu.edu/yardandgarden/research/beans-in-the-garden' },
      { label: 'UMass New England Vegetable Management Guide: Bean, snap, lima and dry', url: 'https://nevegetable.org/crops/bean-snap-lima-and-dry' },
    ],
  },
  {
    key: 'chickpea',
    name: 'Chickpeas',
    aliases: ['chickpea', 'chickpeas', 'garbanzo', 'garbanzo beans'],
    latin: 'Cicer arietinum',
    family: 'Pea family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun and a warm site; best at 21 to 29°C by day and 18 to 21°C at night.',
    soil: 'Well-drained, lighter soil that warms quickly; chickpeas do not tolerate wet or waterlogged soil or heavy clay.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Sow in spring into warming soil. Chickpeas fix nitrogen with root bacteria, so they need none added.',
    spacing: 'Plants grow 30 to 70 cm tall; a taproot that often goes deeper than a metre makes them hard to move.',
    ready: 'Flowers come 50 to 55 days after sowing and the crop is ready 110 to 130 days after sowing, once the pods are dry.',
    water: 'Sparingly; the deep taproot finds water, and 15 to 25 cm of rain over the season is enough.',
    grow: 'Self-pollinating. At 30°C and above the early flowers and pods suffer. A plant cut back by frost can regrow from nodes below the soil.',
    sources: [
      { label: 'Saskatchewan Pulse Growers: Chickpea seeding', url: 'https://saskpulse.com/growing-pulses/chickpeas/chickpeas-seeding/' },
      { label: 'USDA ARS: Nutrient disorders of chickpea and lentil', url: 'https://www.ars.usda.gov/ARSUserFiles/20902000/Compendium/Part4-Noninfectious_Disorders.doc' },
    ],
  },
  {
    key: 'lentil',
    name: 'Lentils',
    aliases: ['lentil', 'lentils'],
    latin: 'Lens culinaris',
    family: 'Pea family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Well-drained soil; wet, poorly drained ground brings root disease.',
    ph: [6.0, 7.5],
    feeding: 'light',
    sow: 'Sow in early spring 1 to 1.5 inches deep. Lentils tolerate frost and regrow from below if the tops are nipped. They fix nitrogen from the air, so they need none added.',
    spacing: 'Sow thickly in rows, since each plant is small and the plants hold one another up.',
    ready: 'Late summer, once the lower pods are brown and rattle.',
    water: 'Only in a long dry spell; wet, poorly drained soil does lentils more harm than dry.',
    grow: 'Grow lentils in the same ground only once in four years, since the diseases that rot them stay in the soil.',
    sources: [
      { label: 'Manitoba Agriculture: Lentils', url: 'https://www.gov.mb.ca/agriculture/crops/crop-management/lentils.html' },
      { label: 'NDSU Extension: Lentil disease diagnostic series', url: 'https://www.ndsu.edu/agriculture/extension/publications/lentil-disease-diagnostic-series' },
    ],
  },
  {
    key: 'soybean',
    name: 'Soya Beans and Edamame',
    aliases: ['soya bean', 'soya beans', 'bean soya', 'soybean', 'soybeans', 'edamame'],
    latin: 'Glycine max',
    family: 'Pea family',
    group: 'vegetables',
    season: 'warm',
    sun: 'A warm, sunny site; best at 20 to 30°C, and in a cool summer the crop is smaller.',
    soil: 'Free-draining soil with at least two bucketfuls of compost worked into each square metre.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Sow indoors in April and May, 5 cm deep at 18 to 20°C, or outdoors in May and June once the soil is at least 15°C, under cloches or fleece.',
    spacing: '15 cm apart in rows 45 cm apart; plants grow about 60 cm tall.',
    ready: 'Pick edamame while the pods are plump and green, and boil them for at least 10 minutes before eating. Dry beans are ready from late September, as the leaves fall.',
    water: 'The plants are thirsty once they flower and the pods begin; mulch to hold the moisture in.',
    grow: 'Mice eat the seed and slugs eat the seedlings, so starting them indoors helps. Cut the plants at soil level at the end and leave the roots in the ground for their nitrogen.',
    sources: [
      rhs('vegetables', 'soya-beans', 'Soya beans'),
      { label: 'K-State Agronomy: Nutrient deficiencies in soybeans', url: 'https://www.agronomy.k-state.edu/eupdates/2026/issue-1110-july-2/nutrient-deficiencies-soybeans-2026.html' },
    ],
  },
  {
    key: 'peanut',
    name: 'Peanuts',
    aliases: ['peanut', 'peanuts', 'groundnut', 'groundnuts'],
    latin: 'Arachis hypogaea',
    family: 'Pea family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun and a long, warm season.',
    soil: 'Light, sandy soil rich in humus that does not crust, so the flower stalks (pegs) can push into it.',
    ph: [5.8, 6.2],
    feeding: 'light',
    sow: 'Sow 1½ to 2 inches deep on clay and 2 to 3 inches deep on sand once the soil is above 65°F.',
    spacing: 'Five seeds to a foot of row, rows at least 20 inches apart.',
    ready: '120 to 150 days after sowing, when the inside of the shells has darkened; lift the whole plant and dry it with the pods attached.',
    water: 'Most of all from 60 to 110 days after planting, while the pods form; stop 10 to 14 days before lifting.',
    grow: 'After the flowers fade, a stalk grows down into the soil and a pod forms at its tip, so keep the soil loose and weed-free around the plants and never let it crust.',
    sources: [
      { label: 'Clemson Home & Garden Information Center: Peanut', url: 'https://hgic.clemson.edu/factsheet/peanut/' },
      { label: 'Utah State University: Peanuts in the garden', url: 'https://extension.usu.edu/yardandgarden/research/peanuts-in-the-garden' },
    ],
  },
  {
    key: 'ginger',
    name: 'Ginger',
    aliases: ['ginger', 'ginger root'],
    latin: 'Zingiber officinale',
    family: 'Ginger family',
    group: 'warm',
    season: 'warm',
    sun: 'Partial shade; a couple of hours of sun a day is enough, and more browns the leaf tips.',
    soil: 'Loose, well-drained soil rich in organic matter, or a deep pot of it.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Plant pieces of fresh rhizome 1 to 1.5 inches long, each with an eye or two, once the soil is above 55°F, or start them indoors in a warm spot and plant out after the last frost.',
    spacing: '6 to 15 inches apart, since the rhizomes spread through the season.',
    ready: 'Young ginger after a short season; mature ginger 8 to 10 months after planting, once the tops die back.',
    water: 'Moist but never wet; too much water rots the rhizome. Water less as the weather cools.',
    grow: 'Grows best at 68°F or warmer and should never sit below 50°F, so in a cool climate grow it in a pot that comes indoors. Heap soil over the rhizomes when they show at the surface.',
    sources: [
      { label: 'UF/IFAS Gardening Solutions: Ginger', url: 'https://gardeningsolutions.ifas.ufl.edu/plants/edibles/vegetables/ginger/' },
      { label: 'Virginia Cooperative Extension: Growing ginger', url: 'https://ext.vt.edu/lawn-garden/Timely_Topics/Ginger.html' },
    ],
  },
  {
    key: 'turmeric',
    name: 'Turmeric',
    aliases: ['turmeric'],
    latin: 'Curcuma longa',
    family: 'Ginger family',
    group: 'warm',
    season: 'warm',
    sun: 'Partial to full shade, 2 to 5 hours of sun a day; more sun yellows the leaves, though the rhizomes grow larger in more light.',
    soil: 'Well-drained soil amended with organic matter.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Cut a firm rhizome into pieces 1 to 1.5 inches long, each with an eye, let the cuts dry for a few days, and sprout them in warm, moist potting mix; they take longer to sprout than ginger.',
    spacing: 'About 6 inches apart in a pot or bed.',
    ready: 'Dig the whole plant when the leaves yellow and die down in autumn, 8 to 10 months after planting.',
    water: 'Moist but never wet until the sprouts show, then keep the soil evenly moist.',
    grow: 'Grows best at 68°F or warmer and should never sit below 50°F. Wear gloves when cutting the rhizomes, which stain.',
    sources: [
      { label: 'UF/IFAS Gardening Solutions: Turmeric', url: 'https://gardeningsolutions.ifas.ufl.edu/plants/edibles/vegetables/turmeric/' },
      { label: 'NC State Extension, Caldwell County: Ginger and turmeric', url: 'https://caldwell.ces.ncsu.edu/news/ginger-and-turmeric-tropical-superfoods-for-the-garden/' },
    ],
  },
  {
    key: 'collards',
    name: 'Collard Greens',
    aliases: ['collards', 'collard', 'collard greens'],
    latin: 'Brassica oleracea (Acephala group)',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Fertile, well-drained soil; nitrogen is what makes good leaves.',
    ph: [6.0, 6.5],
    feeding: 'moderate',
    sow: 'Start transplants 6 to 8 weeks ahead, or sow seed ¼ to ½ inch deep; seed sown deeper than ½ inch may not come up.',
    spacing: '12 to 24 inches apart.',
    ready: '70 to 90 days from seed or 50 to 70 days from transplants. Pick the older, outer leaves and let the centre keep growing.',
    water: 'Wet the soil at least 6 inches deep, in the morning; moisture matters most as the plants establish and as they mature.',
    grow: 'Frost sweetens the leaves. A long cold spell makes spring plants flower, so choose a kind slow to bolt.',
    sources: [
      { label: 'Clemson Home & Garden Information Center: Collards', url: 'https://hgic.clemson.edu/factsheet/collards/' },
      { label: 'UF/IFAS Gardening Solutions: Collards', url: 'https://gardeningsolutions.ifas.ufl.edu/plants/edibles/vegetables/collards/' },
    ],
  },
  {
    key: 'mustardgreens',
    name: 'Mustard Greens',
    aliases: ['mustard greens', 'mustard green'],
    latin: 'Brassica juncea',
    family: 'Cabbage family',
    group: 'vegetables',
    season: 'cool',
    sun: 'Full sun.',
    soil: 'Well-drained, fertile soil; low fertility, heat or dry soil make the leaves strong and bitter.',
    ph: [6.0, 7.0],
    feeding: 'moderate',
    sow: 'Sow ½ inch deep into soil above 45°F, from 3 weeks before the last frost, again 3 weeks later, and again from mid to late summer for autumn; hot soil stops the seed coming up.',
    spacing: 'Thin to 2 to 4 inches apart in rows 16 to 24 inches apart.',
    ready: '35 to 50 days after sowing.',
    water: 'Evenly, so the leaves stay mild and tender.',
    grow: 'Spring sowings flower in the long, warm days of summer, so sow little and often. Mustard leaves carry less wax than cabbage and take more flea beetle damage.',
    sources: [
      { label: 'University of Arkansas Extension: Home gardening series, mustard (FSA-6072)', url: 'https://www.uaex.uada.edu/publications/pdf/FSA-6072.pdf' },
      { label: 'NC State Extension Gardener Plant Toolbox: Mustard greens', url: 'https://plants.ces.ncsu.edu/plants/brassica-juncea/common-name/mustard-greens/' },
    ],
  },
  {
    key: 'fennel',
    name: 'Florence Fennel',
    aliases: ['fennel', 'florence fennel'],
    latin: 'Foeniculum vulgare var. azoricum',
    family: 'Carrot family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun on a warm, sheltered site.',
    soil: 'Fertile, free-draining soil; fennel dislikes heavy clay and waterlogging.',
    ph: [6.5, 8.0],
    feeding: 'moderate',
    sow: 'Sow direct in June or July, 15 mm deep in rows 30 cm apart, or one seed to a module indoors from late spring; plant out from May after the last frost.',
    spacing: 'Thin to 30 cm apart; up to three plants fit a 40 cm container.',
    ready: '60 to 90 days after sowing. Cut the bulbs at 10 to 15 cm across, before they stretch upward.',
    water: '1 to 2 inches a week and never let the soil dry out; swings between wet and dry split the bulbs.',
    grow: 'Cold, early sowings, root disturbance and dry summers all make fennel flower before it bulbs, so sow after midsummer or in modules. Heap soil around the bulb as it swells.',
    sources: [
      rhs('vegetables', 'florence-fennel', 'Florence fennel'),
      { label: 'Utah State University: Fennel in the garden', url: 'https://extension.usu.edu/yardandgarden/research/fennel-in-the-garden' },
    ],
  },
  {
    key: 'tomatillo',
    name: 'Tomatillos',
    aliases: ['tomatillo', 'tomatillos'],
    latin: 'Physalis philadelphica',
    family: 'Nightshade family',
    group: 'vegetables',
    season: 'warm',
    sun: 'Full sun, six hours a day or more.',
    soil: 'Well-drained soil.',
    ph: [6.0, 7.0],
    feeding: 'light',
    sow: 'Start indoors like tomatoes and plant out after the last frost, setting each plant deep, up to its first true leaves.',
    spacing: '2 to 3 feet apart, and grow at least two plants, since one plant cannot pollinate itself.',
    ready: 'When the fruit fills its papery husk.',
    water: '1 to 2 inches a week, deeply and not often; tomatillos tolerate some drought and rot where the soil stays wet.',
    grow: 'Too much feeding gives leaves and delays the fruit. Grow them away from where tomatoes, peppers and potatoes grew, which share their diseases.',
    sources: [
      { label: 'Utah State University: Tomatillos in the garden', url: 'https://extension.usu.edu/yardandgarden/research/tomatillos-in-the-garden' },
      { label: 'NC State Extension, Wilkes County: Growing tomatillos in the home garden', url: 'https://wilkes.ces.ncsu.edu/news/growing-tomatillos-in-the-home-garden/' },
    ],
  },
  {
    key: 'cowpea',
    name: 'Cowpeas and Black-Eyed Peas',
    aliases: ['cowpea', 'cowpeas', 'cowpea black eyed pea', 'black eyed pea', 'black eyed peas', 'southern peas'],
    latin: 'Vigna unguiculata',
    family: 'Pea family',
    group: 'warm',
    season: 'warm',
    sun: 'Full sun and heat.',
    soil: 'Well-drained soil; avoid heavy, wet ground.',
    ph: [5.8, 6.3],
    feeding: 'light',
    sow: 'Sow ¾ to 1½ inches deep into soil at least 60°F; sown into cool soil the seedlings are hit by many pests and diseases.',
    spacing: '4 to 6 seeds a foot in rows 20 to 42 inches apart.',
    ready: '65 to 125 days after sowing, depending on the kind. Pick often to keep the flowers coming.',
    water: 'Usually none is needed once they are up; a mulch holds moisture in.',
    grow: 'Self-pollinating, and they fix nitrogen from the air, so rich soil, above all soil left high in nitrogen, gives long vines with few peas.',
    sources: [
      { label: 'Clemson Home & Garden Information Center: Southern peas', url: 'https://hgic.clemson.edu/factsheet/southern-peas/' },
      { label: 'UC IPM: Cut-out in blackeyes', url: 'https://ipm.ucanr.edu/agriculture/dry-beans/cut-out-blackeyes/' },
    ],
  },
];

function cropSpecies(guide: CropGuide): string {
  return guide.latin.split(',')[0].replace(/\(.*?\)/g, '').replace(/\bspp\.|\bsubsp\..*$|\bagg\./g, '').trim();
}

export function cropPubmedUrl(guide: CropGuide): string {
  return pubmedSearchUrl(`${cropSpecies(guide)} nutrient deficiency`);
}

// The living-soil page that suits each group best: no-dig beds for
// vegetables, compost for herbs, a deep mulch under fruit, and indigenous
// microorganisms for warm climates, where Korean Natural Farming is most
// practised.
const GROUP_LIVING_SOIL: Record<CropGroup, GuideSource> = {
  vegetables: GO_NO_DIG,
  herbs: GO_COMPOST,
  fruit: GO_MULCH,
  warm: KNF_IMO,
};

// Every source a guide shows: its advisory services, the organic growing
// guides for the crop, the living-soil page for its group, then two
// PubMed searches, one on shortages and one on compost and organic growing.
export function cropSources(guide: CropGuide): GuideSource[] {
  return [
    ...guide.sources,
    ...(CROP_ORGANIC_SOURCES[guide.key] ?? []),
    GROUP_LIVING_SOIL[guide.group],
    { label: 'PubMed: research on shortages in this crop', url: cropPubmedUrl(guide) },
    { label: 'PubMed: research on growing this crop with compost', url: pubmedSearchUrl(`${cropSpecies(guide)} compost organic`) },
  ];
}

function normalize(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9 ]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// Food names that begin with a crop's word but are not the crop.
const NOT_A_CROP = ['pepper black', 'black pepper', 'pepper white', 'white pepper', 'corn flakes', 'cornflakes', 'corn starch', 'cornstarch', 'orange juice drink', 'lime juice cordial', 'ginger ale', 'fennel seed'];

type AliasEntry = { alias: string; guide: CropGuide };
const ALIAS_INDEX: AliasEntry[] = CROP_GUIDES.flatMap((guide) => guide.aliases.map((alias) => ({ alias: normalize(alias), guide }))).sort(
  (a, b) => b.alias.length - a.alias.length,
);

// The guide for a saved food name, or null. The name has to begin with
// the alias as whole words, so "Mangosteen" is not a mango and
// "Peppermint" is mint only because mint lists it.
export function findCropGuide(foodName: string | null | undefined): CropGuide | null {
  if (!foodName) return null;
  const name = normalize(foodName);
  if (!name || NOT_A_CROP.some((phrase) => name.startsWith(phrase))) return null;
  for (const { alias, guide } of ALIAS_INDEX) {
    if (name === alias || name.startsWith(`${alias} `)) return guide;
  }
  return null;
}

export function findCropGuideByKey(key: string | null | undefined): CropGuide | null {
  if (!key) return null;
  return CROP_GUIDES.find((guide) => guide.key === key) ?? null;
}

export function searchCropGuides(query: string): CropGuide[] {
  const q = normalize(query);
  if (!q) return CROP_GUIDES;
  return CROP_GUIDES.filter((guide) => {
    const haystack = normalize([guide.name, guide.latin, guide.family, ...guide.aliases].join(' '));
    return q.split(' ').every((word) => haystack.includes(word));
  });
}

export function formatPh([low, high]: [number, number]): string {
  return `pH ${low.toFixed(1)} to ${high.toFixed(1)}`;
}

export const FEEDING_LABELS: Record<CropGuide['feeding'], string> = {
  light: 'Light feeder',
  moderate: 'Moderate feeder',
  heavy: 'Heavy feeder',
};

export const SEASON_LABELS: Record<CropGuide['season'], string> = {
  cool: 'Cool season',
  warm: 'Warm season',
  perennial: 'Perennial',
};
