// Auto-generated by scripts/build_food_reference_db.py (bumped manually here,
// 2026-08-08, after directly patching the compiled .db a sixteenth time
// the same day for Migraine, this app's sixteenth real condition and its
// sixth genuinely non-autoimmune one: a `conditions` row flipped to
// 'in_progress'; 2 new `common_medications` rows (erenumab, sumatriptan
// -- propranolol was already present from the Graves' pass and reused
// directly, since it's also a real, common, older migraine-prevention
// medication); 1 new `interaction_rules` row
// (sumatriptan_ssri_serotonin_syndrome, a real, well-established,
// reference-only caution -- triptans and SSRI/SNRI antidepressants both
// increase serotonin activity, a genuinely serious, well-documented
// interaction risk); and deliberately ZERO new
// `sub_criterion_condition_relevance` rows and zero new sub_criteria --
// checked directly and confirmed no `tyramine`/`histamine` nutrient_code
// exists in this database's own `food_nutrients` table, and, more
// fundamentally, this app's own Migraine research explicitly, honestly
// documents that tyramine's own reputation as the real mechanism behind
// classic trigger foods (aged cheese, red wine) does not hold up under
// refined modern measurement -- building a food-scoring dimension around
// a mechanism this app's own Digest content directly and honestly
// disputes would have misrepresented that same real nuance rather than
// reflected it, the same "don't force a dimension that misrepresents
// real nuance" discipline already applied to CKD's declined potassium/
// phosphorus sub-criteria and MASLD's declined sugar-based one -- since
// no Python interpreter was available in this session to run a real
// rebuild) -- do not edit by hand.
export const REFERENCE_DB_VERSION = "20260808240000";
