// Auto-generated by scripts/build_food_reference_db.py (bumped manually here,
// 2026-08-08, after directly patching the compiled .db to unhide 244 real
// chicken cuts -- see CLAUDE.md's own entry for the full reasoning -- since
// no Python interpreter was available in this session to run a real
// rebuild) -- do not edit by hand.
export const REFERENCE_DB_VERSION = "20260807104003";
