"""
Second batch for the same mechanism column add_interaction_rule_mechanisms.py
introduced -- covers the remaining 31 of 44 interaction_rules rows that
script named as a scoped, not-yet-done follow-up: the age-threshold and
concurrent-use cautions added across later condition build-outs.

Same discipline as the first batch: every mechanism traces to the same
citation already stored on that row, except where independently verified
via WebSearch first (Reye's syndrome mitochondrial injury, pediatric DKA
cerebral edema's own genuinely unsettled mechanism, methimazole
agranulocytosis' immune-mediated basis), each noted inline below where it
applies.

The mechanism text itself lives in a separate plain-text file
(interaction_rule_mechanisms_batch2.txt, next to this script) rather than
as Python string literals here, one paragraph per rule separated by a
blank line, in the same order as RULE_IDS below -- easier to review as
prose on its own, and avoids hand-escaping 31 long paragraphs into source.

allopurinol_azathioprine_toxicity and azathioprine_allopurinol_toxicity
describe the same underlying xanthine-oxidase interaction from each
drug's own side (two distinct rows already in the table, one checkable
concurrent_use_caution, one reference-only dose_consistency_caution, not
a duplicate this script introduced) -- their two mechanism paragraphs are
intentionally similar rather than identical, not copy-pasted.

Safe to re-run: every write is an UPDATE keyed on id, so running this
twice doesn't change anything the second time.

Usage:
  py scripts/add_interaction_rule_mechanisms_batch2.py
"""
import datetime
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent.parent / "assets" / "data" / "foods_reference.db"
VERSION_TS_PATH = Path(__file__).resolve().parent.parent / "lib" / "referenceDbVersion.ts"
MECHANISMS_TXT_PATH = Path(__file__).resolve().parent / "interaction_rule_mechanisms_batch2.txt"

# Same order as the plain-text paragraphs in MECHANISMS_TXT_PATH.
RULE_IDS = [
    "ace_arb_potassium_monitoring",
    "acitretin_alcohol_avoidance",
    "allopurinol_azathioprine_toxicity",
    "antithyroid_drug_iodine_efficacy",
    "aspirin_pediatric_reyes_syndrome",
    "atorvastatin_grapefruit_caution",
    "azathioprine_adalimumab_infection_risk",
    "azathioprine_allopurinol_toxicity",
    "colchicine_atorvastatin_myopathy",
    "cyclosporine_grapefruit_avoidance",
    "dimethyl_fumarate_dietary_fat",
    "diphenhydramine_elderly_anticholinergic_risk",
    "glyburide_elderly_hypoglycemia_beers",
    "graves_apathetic_presentation_60plus",
    "hydroxychloroquine_grapefruit_caution",
    "insulin_alcohol_delayed_hypoglycemia",
    "levothyroxine_elderly_lower_starting_dose",
    "lithium_elderly_renal_clearance",
    "methimazole_agranulocytosis_warning_signs",
    "methotrexate_adalimumab_infection_risk",
    "methotrexate_age70_toxicity_risk",
    "methotrexate_folate_interaction",
    "natalizumab_immunosuppressant_pml_caution",
    "nsaid_elderly_bleeding_risk",
    "ppi_longterm_elderly_fracture_risk",
    "ptu_liver_injury_warning_signs",
    "radioactive_iodine_low_iodine_diet_prep",
    "spironolactone_potassium_caution",
    "sulfonylurea_reduced_kidney_function_caution",
    "sumatriptan_ssri_serotonin_syndrome",
    "type1_pediatric_dka_cerebral_edema",
]


def main():
    paragraphs = [p.strip() for p in MECHANISMS_TXT_PATH.read_text(encoding="utf-8").split("\n\n") if p.strip()]
    if len(paragraphs) != len(RULE_IDS):
        raise SystemExit(f"Mismatch: {len(paragraphs)} paragraphs in the text file but {len(RULE_IDS)} rule ids.")

    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    updated = 0
    unmatched = []
    for rule_id, mechanism in zip(RULE_IDS, paragraphs):
        cur.execute("UPDATE interaction_rules SET mechanism = ? WHERE id = ?", (mechanism, rule_id))
        if cur.rowcount == 1:
            updated += 1
        else:
            unmatched.append(rule_id)
    print(f"Updated mechanism on {updated} of {len(RULE_IDS)} interaction_rules rows.")
    if unmatched:
        print(f"WARNING: no matching row found for: {unmatched}")

    conn.commit()

    cur.execute("SELECT COUNT(*) FROM interaction_rules WHERE mechanism IS NULL")
    remaining = cur.fetchone()[0]
    print(f"{remaining} interaction_rules rows still have no mechanism (expected 0 after this batch).")

    conn.close()

    version = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    VERSION_TS_PATH.write_text(
        '// Auto-generated by scripts/build_food_reference_db.py (bumped manually here by\n'
        '// scripts/add_interaction_rule_mechanisms_batch2.py, which patches the compiled .db\n'
        '// directly) -- do not edit by hand.\n'
        f'export const REFERENCE_DB_VERSION = "{version}";\n',
        encoding="utf-8",
    )
    print(f"Bumped REFERENCE_DB_VERSION to {version}.")


if __name__ == "__main__":
    main()
