"""
Vegan Meal Plan track, lunch/dinner mains -- 2026-08-24, continuation of
add_vegan_meal_plan_breakfasts.py. 64 new curated recipes, each a direct,
vegetable-preserving substitute for one of the omnivore 6-Week Meal Plan's
own meat/fish/feta/egg lunch or dinner dishes: every real vegetable,
aromatic, and seasoning from the original dish is carried over unchanged,
only the animal protein itself is replaced with tofu, tempeh, seitan
(vital wheat gluten), a legume, or a "meaty" mushroom appropriate to that
dish's own cooking method and cuisine. This keeps the real vegetable
variety the omnivore plan's own header comment already documents while
making every one of these dishes genuinely vegan.

Two small in-place edits (not new recipes) also happen here: the existing
curated_side_teriyaki_baked_tofu and curated_salad_sesame_ginger_slaw
rows both use honey as their only non-vegan ingredient; both get it
swapped to maple syrup directly, a flavor-neutral change that benefits
every track, not just this one.

Every ingredient verified against the live reference database before
being written in, same discipline as every other batch.

Usage:
  py scripts/add_vegan_meal_plan_mains.py
"""
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent.parent / "assets" / "data" / "foods_reference.db"

TOFU = ("Legume", "Tofu")
TEMPEH = ("Legume", "Tempeh")
SEITAN = ("Grain", "Meat substitute containing gluten (seitan)")
CHICKPEA = ("Legume", "Chickpeas (garbanzo beans, bengal gram)")
WHITE_BEANS = ("Legume", "White Beans")
GREEN_LENTIL = ("Legume", "Lentil, green, hulled, dry")
HEARTS_OF_PALM = ("Veg", "Hearts of palm")
KING_OYSTER = ("Mushroom", "Mushrooms, king oyster mushrooms")
PORTOBELLO = ("Veg", "Mushroom, portabella (portobello)")
COMMON_MUSHROOM = ("Veg", "Mushroom, common, fresh")
WALNUT = ("NutSeed", "Walnut")
FLAXSEED = ("NutSeed", "Flaxseed Seeds")
NUTRITIONAL_YEAST = ("Mushroom", "Yeast flakes/nutritional yeast")
TURMERIC = ("Herbs", "Turmeric, dried, ground")
PAPRIKA = ("Herbs", "Paprika")
VEGETABLE_STOCK = ("PantryStaples", "Vegetable stock")
MAPLE_SYRUP = ("Sweets", "Maple Syrup (100% Pure)")

RECIPES = [
    # ---- Handhelds ----
    ("curated_vegan_handheld_seitan_roasted_vegetable_wrap", "handheld",
     "Seitan & Roasted Vegetable Wrap",
     "A hearty wrap built on seitan instead of bison.",
     "Vital wheat gluten (seitan) has a genuinely chewy, meat-like bite once cooked, standing in well for a sliced, sauteed protein.",
     1.0, 1.0, "wrap", 0,
     [(*SEITAN, 120, "g", "sliced", "Sauteed", None),
      ("PantryStaples", "Wheat flour, white, tortilla mix, enriched", 60, "g", None, "Baked", None),
      ("Veg", "Red Bell Pepper", 50, "g", "sliced", "Roasted", None),
      ("Veg", "Onion", 30, "g", "sliced", "Roasted", None),
      ("Veg", "Lettuce, green leaf", 20, "g", "whole", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_handheld_grilled_tempeh_sandwich", "handheld",
     "Grilled Tempeh Sandwich",
     "A grilled sandwich built on tempeh instead of chicken breast.",
     "Tempeh's own firm, nutty texture holds up well to a hot grill, the same real reason it works across so many savory sandwiches.",
     1.0, 1.0, "sandwich", 1,
     [("Baked", "Bröd fullkorn vete råg fibrer ca 6%", 2, "slice", None, None, None),
      (*TEMPEH, 120, "g", None, "Grilled", None),
      ("Veg", "Lettuce, green leaf", 20, "g", None, None, None),
      ("Veg", "Tomato", 40, "g", "sliced", None, None),
      ("Fruit", "Avocado", 40, "g", "sliced", None, None)]),
    ("curated_vegan_handheld_chickpea_avocado_wrap", "handheld",
     "Chickpea Smash & Avocado Wrap",
     "A creamy mashed-chickpea wrap standing in for sliced turkey.",
     "Mashed chickpeas bring a genuine, satisfying protein and fiber base without needing a meat slice at all.",
     1.0, 1.0, "wrap", 2,
     [("Baked", "Tortilla, wraps/burrito, hvetemel", 1, "each", None, None, None),
      (*CHICKPEA, 100, "g", "mashed", None, None),
      ("Fruit", "Avocado", 80, "g", "sliced", None, None),
      ("Veg", "Lettuce, green leaf", 30, "g", None, None, None),
      ("Veg", "Tomato", 60, "g", "sliced", None, None)]),
    ("curated_vegan_handheld_tempeh_hummus_collard_wrap", "handheld",
     "Tempeh Hummus Collard Wrap",
     "A collard-leaf wrap pairing sauteed tempeh with real homemade hummus.",
     "Tempeh and hummus together bring two distinct whole-soy and whole-legume proteins into the same wrap.",
     1.0, 1.0, "wrap", 3,
     [(*TEMPEH, 100, "g", "sliced", "Sauteed", None),
      ("Veg", "Collards", 2, "each", "large leaf, stem trimmed", None, None),
      (*CHICKPEA, 40, "g", None, None, "blended into hummus"),
      ("SaucesCondiments", "Tahini", 10, "g", None, None, "blended into hummus"),
      ("Fruit", "Lemon", 5, "g", "juiced", None, "blended into hummus"),
      ("Veg", "Garlic", 1.5, "g", "minced", None, "blended into hummus"),
      ("Veg", "Tomato", 40, "g", "sliced", None, None),
      ("Herbs", "Common salt/table salt", 0.5, "g", None, None, None)]),
    ("curated_vegan_handheld_chickpea_egg_salad_lettuce_wraps", "handheld",
     "Chickpea \"Egg\" Salad Lettuce Wraps",
     "Mashed chickpeas, turmeric, and tahini stand in for the usual boiled egg and mayonnaise.",
     "Turmeric gives mashed chickpeas the same real yellow color a boiled egg has, and tahini brings the same creamy body mayonnaise would.",
     1.0, 1.0, "wrap", 4,
     [(*CHICKPEA, 150, "g", "mashed", None, None),
      ("SaucesCondiments", "Tahini", 15, "g", None, None, "as a creamy binder"),
      (*TURMERIC, 0.5, "g", None, None, "for color"),
      ("Veg", "Celery", 20, "g", "diced", None, None),
      ("Veg", "Lettuce, green leaf", 30, "g", None, None, None),
      ("Herbs", "Mustard, prepared, yellow", 2.5, "g", None, None, None)]),
    # ---- Salads ----
    ("curated_vegan_salad_hearts_of_palm_avocado_salad", "salad",
     "Hearts of Palm & Avocado Salad",
     "Hearts of palm's own mild, flaky texture stands in for crab.",
     "Hearts of palm are a real vegetable with a texture close enough to crab that it's a common vegan substitute for exactly this reason.",
     1.0, 1.0, "bowl", 5,
     [(*HEARTS_OF_PALM, 120, "g", "sliced", None, None),
      ("Fruit", "Avocado", 80, "g", "diced", None, None),
      ("Veg", "Lettuce, green leaf", 50, "g", "whole", None, None),
      ("Fruit", "Lime", 10, "g", "juiced", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 5, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_salad_hearts_of_palm_mango_salad", "salad",
     "Hearts of Palm & Mango Salad",
     "Hearts of palm against sweet mango and peppery arugula.",
     "The same real crab stand-in used elsewhere in this plan, paired here with mango instead of avocado for a genuinely different bowl.",
     1.0, 1.0, "bowl", 6,
     [(*HEARTS_OF_PALM, 120, "g", "sliced", None, None),
      ("Fruit", "Mango", 80, "g", "diced", None, None),
      ("Veg", "Arugula", 50, "g", "whole", None, None),
      ("Fruit", "Lime", 10, "g", "juiced", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 5, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_salad_grilled_tofu_greens_salad", "salad",
     "Grilled Marinated Tofu & Greens Salad",
     "Grilled tofu over a real mixed-greens salad, standing in for grilled halibut.",
     "Firm tofu takes on real grill marks and a genuine char flavor the same way a flaky white fish would.",
     1.0, 1.0, "bowl", 7,
     [(*TOFU, 150, "g", "cubed", "Grilled", None),
      ("Veg", "Lettuce, green leaf", 60, "g", "whole", None, None),
      ("Veg", "Arugula", 30, "g", "whole", None, None),
      ("Veg", "Cucumber", 50, "g", "sliced", None, None),
      ("Veg", "Tomato", 50, "g", "sliced", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_salad_smoky_tempeh_radish_salad", "salad",
     "Smoky Tempeh & Radish Salad",
     "Paprika-seared tempeh against crisp radish, standing in for grilled mackerel.",
     "A little paprika gives grilled tempeh a real smoky depth close to a rich, oily fish.",
     1.0, 1.0, "bowl", 8,
     [(*TEMPEH, 130, "g", "sliced", "Grilled", None),
      (*PAPRIKA, 1, "g", None, None, None),
      ("Veg", "Radish", 60, "g", "sliced", None, None),
      ("Veg", "Lettuce, green leaf", 50, "g", "whole", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_salad_white_bean_roasted_pepper_salad", "salad",
     "White Bean & Roasted Pepper Salad",
     "Creamy white beans against sweet roasted pepper, standing in for sardine.",
     "White beans bring a genuine plant protein without the small bones or briny intensity a whole sardine carries.",
     1.0, 1.0, "bowl", 9,
     [(*WHITE_BEANS, 120, "g", None, None, None),
      ("Veg", "Yellow Bell Pepper", 60, "g", "sliced", "Roasted", None),
      ("Veg", "Arugula", 40, "g", "whole", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_salad_king_oyster_watermelon_salad", "salad",
     "King Oyster Mushroom & Watermelon Salad",
     "Grilled king oyster mushroom and cool watermelon, with marinated tofu standing in for feta.",
     "King oyster mushroom's own dense, meaty stem takes on a real char from the grill the way shrimp would.",
     1.0, 1.0, "bowl", 10,
     [(*KING_OYSTER, 130, "g", "sliced", "Grilled", None),
      ("Fruit", "Watermelon", 100, "g", "cubed", None, None),
      (*TOFU, 20, "g", "crumbled", None, "marinated as a feta stand-in"),
      ("Fruit", "Lime", 10, "g", "juiced", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 5, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 0.5, "g", None, None, None)]),
    ("curated_vegan_salad_tofu_cucumber_dill_salad", "salad",
     "Marinated Tofu & Cucumber Dill Salad",
     "Baked tofu with fresh dill, standing in for trout.",
     "Fresh dill is the same real herb that pairs with fish across this whole plan, and it works just as well against baked tofu.",
     1.0, 1.0, "bowl", 11,
     [(*TOFU, 130, "g", "cubed", "Baked", None),
      ("Veg", "Cucumber", 80, "g", "sliced", None, None),
      ("Veg", "Lettuce, green leaf", 40, "g", "whole", None, None),
      ("Herbs", "Fresh Dill Weed", 3, "g", "chopped", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_salad_white_bean_artichoke_salad", "salad",
     "White Bean & Artichoke Salad",
     "Roasted artichoke and creamy white beans, standing in for tuna.",
     "White beans bring a genuine plant protein alongside the same roasted artichoke this plan's own tuna version already uses.",
     1.0, 1.0, "bowl", 12,
     [(*WHITE_BEANS, 120, "g", None, None, None),
      ("Veg", "Artichoke", 80, "g", "quartered", "Roasted", None),
      ("Veg", "Arugula", 50, "g", "whole", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_salad_chickpea_white_bean_salad", "salad",
     "Chickpea & White Bean Salad",
     "Two legumes together, standing in for tuna.",
     "Combining chickpea and white bean brings a genuinely complete plant protein into one bowl.",
     1.0, 1.0, "bowl", 13,
     [(*CHICKPEA, 120, "g", None, None, None),
      (*WHITE_BEANS, 80, "g", None, None, None),
      ("Veg", "Arugula", 50, "g", "whole", None, None),
      ("Veg", "Onion", 20, "g", "thinly sliced", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_salad_beet_walnut_arugula_tofu", "salad",
     "Beet, Walnut & Arugula Salad with Herbed Tofu",
     "Roasted beet and toasted walnut, with lemon-marinated tofu standing in for feta.",
     "A little lemon and salt gives firm tofu a real tangy, briny edge close to feta.",
     1.0, 1.0, "bowl", 14,
     [("Veg", "Beets", 0.75, "cup", "Diced", "Roasted", None),
      (*WALNUT, 0.125, "cup", "Chopped", "Raw", None),
      ("Veg", "Arugula", 1, "cup", "Whole", "Raw", None),
      (*TOFU, 30, "g", "cubed", None, "marinated as a feta stand-in"),
      ("Herbs", "Vinegar, balsamic", 0.5, "tbsp", None, None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 0.5, "tbsp", None, None, None)]),
    ("curated_vegan_salad_mediterranean_chickpea_tofu", "salad",
     "Mediterranean Chickpea Salad with Herbed Tofu",
     "Cucumber, tomato, and chickpea, with lemon-marinated tofu standing in for feta.",
     "The same real Mediterranean vegetables this plan's own chickpea-feta salad already uses, just without the dairy.",
     1.0, 1.0, "bowl", 15,
     [(*CHICKPEA, 0.5, "cup", "Whole", None, None),
      (*TOFU, 60, "g", "cubed", None, "marinated as a feta stand-in"),
      ("Veg", "Cucumber", 0.5, "cup", "Diced", "Raw", None),
      ("Veg", "Tomato", 0.5, "cup", "Diced", "Raw", None),
      ("Veg", "Onion", 0.125, "cup", "Diced", "Raw", None),
      ("Fats", "Olive Oil (Extra Virgin)", 1, "tbsp", None, None, None),
      ("Bev", "Lemon Juice", 0.5, "tbsp", None, None, None),
      ("Herbs", "Oregano", 0.5, "tsp", None, None, None)]),
    ("curated_vegan_salad_roasted_artichoke_white_bean_tofu", "salad",
     "Roasted Artichoke & White Bean Salad with Herbed Tofu",
     "Roasted artichoke and white bean, with lemon-marinated tofu standing in for feta.",
     "White bean already carries real protein on its own; the marinated tofu here adds the same tangy note feta would.",
     1.0, 1.0, "bowl", 16,
     [("Veg", "Artichoke", 100, "g", "quartered", "Roasted", None),
      (*WHITE_BEANS, 80, "g", None, None, None),
      (*TOFU, 20, "g", "crumbled", None, "marinated as a feta stand-in"),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_salad_spelt_roasted_vegetable_tofu", "salad",
     "Spelt & Roasted Vegetable Salad with Herbed Tofu",
     "Whole-grain spelt with roasted parsnip and carrot, with lemon-marinated tofu standing in for feta.",
     "Spelt is an ancient whole grain that carries real fiber and B vitamins the more common wheat berry sometimes doesn't match.",
     1.0, 1.0, "bowl", 17,
     [("Grain", "Spelt Grains", 75, "g", "cooked", None, None),
      ("Veg", "Parsnip", 80, "g", "diced", "Roasted", None),
      ("Veg", "Carrot", 60, "g", "diced", "Roasted", None),
      (*TOFU, 20, "g", "crumbled", None, "marinated as a feta stand-in"),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None)]),
    # ---- Sides (dinner mains) ----
    ("curated_vegan_side_baked_tempeh_brussels_sweet_potato", "side",
     "Baked Tempeh with Brussels Sprouts & Sweet Potato",
     "Rosemary-roasted tempeh alongside brussels sprouts and sweet potato.",
     "Tempeh's own firm bite holds together well through a full roast, the same real reason it works here in place of chicken thigh.",
     1.0, 1.0, "plate", 18,
     [(*TEMPEH, 150, "g", None, "Baked", None),
      ("Veg", "Brussels sprout", 100, "g", "halved", "Roasted", None),
      ("Veg", "Sweet potato", 100, "g", "diced", "Roasted", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Herbs", "Rosemary", 2, "g", "chopped", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None),
      ("Herbs", "Pepper, black, ground", 0.5, "g", None, None, None)]),
    ("curated_vegan_side_baked_tofu_fennel_orange", "side",
     "Baked Tofu with Fennel & Orange",
     "Baked tofu with roasted fennel and fresh orange, standing in for cod.",
     "Fennel and orange are a genuinely classic pairing with a mild white fish, and they work just as well against plain baked tofu.",
     1.0, 1.0, "plate", 19,
     [(*TOFU, 150, "g", None, "Baked", None),
      ("Veg", "Fennel Bulb", 90, "g", "sliced", "Roasted", None),
      ("Fruit", "Orange", 50, "g", "segmented", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_baked_tofu_paprika_lemon", "side",
     "Baked Paprika-Lemon Tofu",
     "Simple baked tofu with paprika and lemon, standing in for cod.",
     "A short paprika-and-lemon marinade gives plain tofu real color and flavor before it ever reaches the oven.",
     1.0, 1.0, "plate", 20,
     [(*TOFU, 150, "g", None, "Baked", None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      (*PAPRIKA, 2, "g", None, None, None),
      ("Fruit", "Lemon", 15, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None),
      ("Herbs", "Pepper, black, ground", 0.5, "g", None, None, None)]),
    ("curated_vegan_side_baked_tofu_lemon_dill", "side",
     "Baked Tofu with Lemon & Dill",
     "Baked tofu with fresh dill and lemon, standing in for salmon.",
     "Dill and lemon are the same real pairing behind this plan's own baked salmon, working just as well here.",
     1.0, 1.0, "plate", 21,
     [(*TOFU, 150, "g", None, "Baked", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 15, "g", "juiced, plus a few slices", None, None),
      ("Herbs", "Fresh Dill Weed", 3, "g", "chopped", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None),
      ("Herbs", "Pepper, black, ground", 0.5, "g", None, None, None)]),
    ("curated_vegan_side_baked_tempeh_parsnip_mash", "side",
     "Baked Tempeh with Parsnip Mash",
     "Baked tempeh over a garlicky parsnip mash, standing in for trout.",
     "A creamy parsnip mash brings real body to the plate, matching the mash this plan's own trout version already builds.",
     1.0, 1.0, "plate", 22,
     [(*TEMPEH, 150, "g", None, "Baked", None),
      ("Veg", "Parsnip", 150, "g", "chopped", "Boiled", None),
      ("Veg", "Garlic", 3, "g", "minced", "Boiled", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None),
      ("Herbs", "Pepper, black, ground", 0.5, "g", None, None, None)]),
    ("curated_vegan_side_baked_seitan_zucchini_tomatoes", "side",
     "Baked Seitan with Zucchini & Tomatoes",
     "Herb-baked seitan with zucchini and tomato, standing in for turkey breast.",
     "Seitan's own chewy bite carries a full bake the same way a lean turkey breast would.",
     1.0, 1.0, "plate", 23,
     [(*SEITAN, 150, "g", None, "Baked", None),
      ("Veg", "Zucchini, green skin, fresh, unpeeled", 100, "g", "sliced", "Baked", None),
      ("Veg", "Tomato", 100, "g", "sliced", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Herbs", "Oregano", 2, "g", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None),
      ("Herbs", "Pepper, black, ground", 0.5, "g", None, None, None)]),
    ("curated_vegan_side_mushroom_walnut_stir_fry_rice", "side",
     "Mushroom & Walnut Stir-Fry Rice",
     "Two mushrooms and toasted walnut standing in for beef in a real stir-fry.",
     "Doubling up on mushroom and adding walnut brings real umami depth and texture close to what sliced beef would.",
     1.0, 1.0, "bowl", 24,
     [("Veg", "Mushroom, common, fresh", 100, "g", "sliced", "Sauteed", None),
      ("Veg", "Mushroom, portabella (portobello)", 80, "g", "sliced", "Sauteed", None),
      (*WALNUT, 30, "g", "chopped", None, None),
      ("Veg", "Onion", 50, "g", "sliced", None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Herbs", "Ginger root", 5, "g", "grated", None, None),
      ("Legume", "Soy sauce made from soy and wheat (shoyu)", 15, "ml", None, None, None),
      ("Grain", "Grains, rice, brown, long-grain, dry", 75, "g", "cooked", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 5, "ml", None, None, None)]),
    ("curated_vegan_side_lentil_walnut_meatballs_tomato_sauce", "side",
     "Lentil-Walnut Meatballs in Herb Tomato Sauce",
     "Lentil-and-walnut meatballs simmered in a real herb tomato sauce, standing in for bison.",
     "Mashed green lentil and chopped walnut bind into a genuinely hearty meatball base, with ground flaxseed doing the same binding job an egg would.",
     1.0, 1.0, "plate", 25,
     [(*GREEN_LENTIL, 90, "g", "cooked, mashed", None, "as the meatball base"),
      (*WALNUT, 40, "g", "chopped", None, "as the meatball base"),
      (*FLAXSEED, 8, "g", "ground, mixed with 24g water", None, "as a binder"),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Veg", "Tomato", 180, "g", "crushed", "Simmered", None),
      ("Veg", "Onion", 30, "g", "diced", None, None),
      ("Herbs", "Basil", 2, "g", "chopped", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 5, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_tempeh_root_vegetable_bowl", "side",
     "Tempeh & Root Vegetable Bowl",
     "Sauteed tempeh over roasted parsnip, carrot, and turnip, standing in for bison.",
     "Three roasted root vegetables together bring a genuinely wide nutrient spread alongside tempeh's own real protein.",
     1.0, 1.0, "bowl", 26,
     [(*TEMPEH, 150, "g", "sliced", "Sauteed", None),
      ("Veg", "Parsnip", 60, "g", "diced", "Roasted", None),
      ("Veg", "Carrot", 60, "g", "diced", "Roasted", None),
      ("Veg", "Turnip", 60, "g", "diced", "Roasted", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Herbs", "Fresh Thyme", 1, "g", "chopped", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_braised_seitan_kohlrabi_carrot", "side",
     "Braised Seitan with Kohlrabi & Carrot",
     "Slow-braised seitan with kohlrabi and carrot, standing in for beef.",
     "A long braise gives seitan real time to soak up the same aromatics a braised beef cube would.",
     1.0, 1.0, "bowl", 27,
     [(*SEITAN, 150, "g", "cubed", "Braised", None),
      ("Veg", "Kohlrabi", 100, "g", "diced", None, None),
      ("Veg", "Carrot", 60, "g", "diced", None, None),
      ("Veg", "Onion", 40, "g", "diced", None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      (*VEGETABLE_STOCK, 7.5, "g", None, None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1.5, "g", None, None, None)]),
    ("curated_vegan_side_lemon_tofu_artichoke", "side",
     "Lemon Tofu with Artichoke",
     "Roasted lemon tofu with artichoke, standing in for chicken breast.",
     "A quick lemon marinade before roasting gives firm tofu real depth close to a roasted chicken breast.",
     1.0, 1.0, "plate", 28,
     [(*TOFU, 150, "g", None, "Roasted", None),
      ("Veg", "Artichoke", 90, "g", "quartered", "Roasted", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 15, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_tempeh_snow_peas_carrots", "side",
     "Tempeh with Snow Peas & Carrots",
     "Baked tempeh with sauteed snow peas and carrot, standing in for chicken breast.",
     "Snow peas and carrot bring a genuine crunch and bright color against tempeh's own firmer texture.",
     1.0, 1.0, "plate", 29,
     [(*TEMPEH, 150, "g", None, "Baked", None),
      ("Veg", "Fresh Snow Pea", 80, "g", "trimmed", "Sauteed", None),
      ("Veg", "Carrot", 60, "g", "sliced", "Sauteed", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Herbs", "Ginger root", 3, "g", "grated", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_chickpea_okra_tomato_skillet", "side",
     "Chickpea, Okra & Tomato Skillet",
     "A one-skillet chickpea, okra, and tomato dish, standing in for chicken thigh.",
     "Okra and tomato together are a real, traditional Southern pairing, chickpea bringing the plant protein here instead of chicken.",
     1.0, 1.0, "plate", 30,
     [(*CHICKPEA, 150, "g", None, "Sauteed", None),
      ("Veg", "Okra", 80, "g", "sliced", "Sauteed", None),
      ("Veg", "Tomato", 100, "g", "diced", None, None),
      ("Veg", "Onion", 30, "g", "diced", None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      (*PAPRIKA, 1, "g", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_tempeh_kohlrabi_apple", "side",
     "Tempeh with Kohlrabi & Apple",
     "Roasted tempeh with kohlrabi and apple, standing in for chicken thigh.",
     "Apple's own sweetness against roasted kohlrabi is a real, unusual pairing worth trying regardless of the protein underneath it.",
     1.0, 1.0, "plate", 31,
     [(*TEMPEH, 150, "g", None, "Roasted", None),
      ("Veg", "Kohlrabi", 90, "g", "diced", "Roasted", None),
      ("Fruit", "Apple", 60, "g", "sliced", "Roasted", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_portobello_beets_orange", "side",
     "Portobello Mushroom with Beets & Orange",
     "Baked portobello with roasted beet and fresh orange, standing in for duck.",
     "Portobello's own dense, savory cap carries the same rich role duck breast plays against sweet beet and citrus.",
     1.0, 1.0, "plate", 32,
     [(*PORTOBELLO, 150, "g", None, "Baked", None),
      ("Veg", "Beets", 100, "g", "diced", "Roasted", None),
      ("Fruit", "Orange", 60, "g", "segmented", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None),
      ("Herbs", "Pepper, black, ground", 0.5, "g", None, None, None)]),
    ("curated_vegan_side_tempeh_cherry_wild_rice", "side",
     "Tempeh with Cherries & Wild Rice",
     "Sauteed tempeh with sour cherry and wild rice, standing in for duck.",
     "Tart cherry against a savory protein is a real, traditional pairing that works just as well with tempeh.",
     1.0, 1.0, "bowl", 33,
     [(*TEMPEH, 150, "g", None, "Sauteed", None),
      ("Fruit", "Sour Cherry", 60, "g", "pitted", None, None),
      ("Grain", "Grains, rice, wild, dry", 70, "g", "cooked", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_ginger_soy_tempeh", "side",
     "Ginger Soy Tempeh",
     "Roasted tempeh in a real ginger-soy glaze, standing in for chicken thigh.",
     "Tempeh soaks up a ginger-soy glaze well, the fermented soy in tempeh itself pairing naturally with the soy sauce in the glaze.",
     1.0, 1.0, "plate", 34,
     [(*TEMPEH, 150, "g", None, "Roasted", None),
      ("Legume", "Soy sauce made from soy and wheat (shoyu)", 15, "ml", None, None, None),
      (*MAPLE_SYRUP, 10, "g", None, None, None),
      ("Herbs", "Ginger root", 5, "g", "grated", None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 5, "ml", None, None, None)]),
    ("curated_vegan_side_tofu_leeks_peas", "side",
     "Tofu with Leeks & Peas",
     "Baked tofu with sauteed leek and fresh pea, standing in for halibut.",
     "Leek and pea together bring a genuinely mild, sweet vegetable pairing that lets the tofu carry a mild flavor of its own.",
     1.0, 1.0, "plate", 35,
     [(*TOFU, 150, "g", None, "Baked", None),
      ("Veg", "Leek", 80, "g", "sliced", "Sauteed", None),
      ("Veg", "Pea, green, fresh", 50, "g", None, None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_herb_crusted_seitan_roast", "side",
     "Herb-Crusted Seitan Roast",
     "A rosemary-and-thyme-crusted seitan roast, standing in for pork tenderloin.",
     "Seitan's own dense, chewy texture holds a real herb crust the same way a roasted pork tenderloin would.",
     1.0, 1.0, "plate", 36,
     [(*SEITAN, 150, "g", None, "Roasted", None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Herbs", "Rosemary", 2, "g", "chopped", None, None),
      ("Herbs", "Fresh Thyme", 1, "g", "chopped", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None),
      ("Herbs", "Pepper, black, ground", 0.5, "g", None, None, None)]),
    ("curated_vegan_side_seitan_chops_roasted_eggplant", "side",
     "Seitan \"Chops\" with Roasted Eggplant",
     "Grilled seitan alongside real roasted eggplant, standing in for lamb chops.",
     "Seitan's own chewy, fibrous texture is close enough to a grilled chop that it's a common substitute for exactly this reason.",
     1.0, 1.0, "plate", 37,
     [(*SEITAN, 150, "g", None, "Grilled", None),
      ("Veg", "Eggplant", 100, "g", "sliced", "Roasted", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Herbs", "Rosemary", 2, "g", "chopped", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_braised_chickpea_fennel_orange", "side",
     "Braised Chickpeas with Fennel & Orange",
     "Chickpeas braised with roasted fennel and fresh orange, standing in for lamb.",
     "The same real fennel-and-orange pairing this plan's own lamb version uses, carried by chickpea instead.",
     1.0, 1.0, "bowl", 38,
     [(*CHICKPEA, 150, "g", None, "Simmered", None),
      ("Veg", "Fennel Bulb", 90, "g", "sliced", "Roasted", None),
      ("Fruit", "Orange", 50, "g", "segmented", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_tofu_skewers_couscous", "side",
     "Marinated Tofu Skewers with Couscous",
     "Cumin-marinated tofu skewers over real couscous, standing in for lamb.",
     "Cubed tofu takes on a grill and a cumin marinade the same way skewered lamb would.",
     1.0, 1.0, "plate", 39,
     [(*TOFU, 130, "g", "cubed", "Grilled", None),
      ("Veg", "Zucchini, green skin, fresh, unpeeled", 60, "g", "cubed", "Grilled", None),
      ("Veg", "Red Bell Pepper", 50, "g", "cubed", "Grilled", None),
      ("Grain", "Couscous (durum wheat)", 60, "g", "cooked", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None),
      ("Herbs", "Cumin (cummin) seed, dried, ground", 1, "g", None, None, None)]),
    ("curated_vegan_side_one_pan_king_oyster_asparagus_rice", "side",
     "One-Pan King Oyster Mushroom & Asparagus Rice",
     "King oyster mushroom and asparagus over rice, all in one pan, standing in for shrimp.",
     "King oyster mushroom's own dense, chewy texture is a common, genuine shrimp stand-in once sliced and sauteed.",
     1.0, 1.0, "bowl", 40,
     [(*KING_OYSTER, 150, "g", "sliced", "Sauteed", None),
      ("Veg", "Asparagus", 100, "g", "trimmed", "Sauteed", None),
      ("Grain", "Grains, rice, brown, long-grain, dry", 75, "g", "cooked", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_seitan_chop_brussels_apple", "side",
     "Seitan \"Chop\" with Brussels Sprouts & Apple",
     "Baked seitan with roasted brussels sprouts and apple, standing in for pork chop.",
     "Apple and brussels sprouts together are a real, classic pork pairing that carries over cleanly onto seitan.",
     1.0, 1.0, "plate", 41,
     [(*SEITAN, 150, "g", None, "Baked", None),
      ("Veg", "Brussels sprout", 100, "g", "halved", "Roasted", None),
      ("Fruit", "Apple", 80, "g", "sliced", "Roasted", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None),
      ("Herbs", "Pepper, black, ground", 0.5, "g", None, None, None)]),
    ("curated_vegan_side_tempeh_radish_carrot", "side",
     "Tempeh with Radish & Carrot",
     "Grilled tempeh with roasted radish and carrot, standing in for pork loin.",
     "Roasted radish loses most of its raw bite and turns genuinely mild and sweet, an easy pairing against grilled tempeh.",
     1.0, 1.0, "plate", 42,
     [(*TEMPEH, 150, "g", None, "Grilled", None),
      ("Veg", "Radish", 80, "g", "halved", "Roasted", None),
      ("Veg", "Carrot", 60, "g", "sliced", "Roasted", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_seitan_turnip_kale", "side",
     "Seitan with Turnip & Kale",
     "Roasted seitan with turnip and sauteed kale, standing in for pork loin.",
     "Turnip and kale together bring a genuinely earthy, hearty vegetable pairing against seitan's own dense bite.",
     1.0, 1.0, "plate", 43,
     [(*SEITAN, 150, "g", None, "Roasted", None),
      ("Veg", "Turnip", 80, "g", "diced", "Roasted", None),
      ("Veg", "Kale", 40, "g", "whole", "Sauteed", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None),
      ("Herbs", "Pepper, black, ground", 0.5, "g", None, None, None)]),
    ("curated_vegan_side_roast_tempeh_fennel_leeks", "side",
     "Roast Tempeh with Fennel & Leeks",
     "Roasted tempeh with fennel and leek, standing in for chicken breast.",
     "Fennel and leek together bring a genuinely mild, aniseed-and-onion depth against roasted tempeh.",
     1.0, 1.0, "plate", 44,
     [(*TEMPEH, 150, "g", None, "Roasted", None),
      ("Veg", "Fennel Bulb", 100, "g", "sliced", "Roasted", None),
      ("Veg", "Leek", 60, "g", "sliced", "Roasted", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None),
      ("Herbs", "Pepper, black, ground", 0.5, "g", None, None, None)]),
    ("curated_vegan_side_tofu_leeks_lemon", "side",
     "Tofu with Leeks & Lemon",
     "Baked tofu with sauteed leek and lemon, standing in for salmon.",
     "Leek's own mild sweetness against a bright squeeze of lemon works just as well over baked tofu as it does over salmon.",
     1.0, 1.0, "plate", 45,
     [(*TOFU, 150, "g", None, "Baked", None),
      ("Veg", "Leek", 100, "g", "sliced", "Sauteed", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 15, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_tofu_wild_rice_asparagus", "side",
     "Tofu with Wild Rice & Asparagus",
     "Roasted tofu with wild rice and asparagus, standing in for salmon.",
     "Wild rice's own nutty bite pairs well against roasted tofu, the same real combination this plan's own salmon version uses.",
     1.0, 1.0, "bowl", 46,
     [(*TOFU, 150, "g", None, "Roasted", None),
      ("Grain", "Grains, rice, wild, dry", 70, "g", "cooked", None, None),
      ("Veg", "Asparagus", 90, "g", "trimmed", "Roasted", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Herbs", "Fresh Dill Weed", 2, "g", "chopped", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_white_bean_tomato_bowl", "side",
     "White Bean & Tomato Bowl",
     "White beans simmered with tomato and parsley, standing in for sardine.",
     "White beans already share the bowl with sardine in this plan's own original version; leaving sardine out and doubling the beans keeps the same real protein base.",
     1.0, 1.0, "bowl", 47,
     [(*WHITE_BEANS, 180, "g", None, None, None),
      ("Veg", "Tomato", 60, "g", "diced", None, None),
      ("Herbs", "Parsley Spices", 10, "g", "chopped", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_king_oyster_scallops_asparagus_lemon", "side",
     "King Oyster \"Scallops\" with Asparagus & Lemon",
     "Pan-seared king oyster mushroom rounds with asparagus and lemon, standing in for scallops.",
     "King oyster mushroom, sliced into rounds and seared, is a genuine, common scallop stand-in for exactly this reason.",
     1.0, 1.0, "plate", 48,
     [(*KING_OYSTER, 150, "g", "sliced into rounds", "Sauteed", None),
      ("Veg", "Asparagus", 100, "g", "trimmed", "Sauteed", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_king_oyster_snow_pea_stir_fry_rice", "side",
     "King Oyster Mushroom & Snow Pea Stir-Fry Rice",
     "A gingery king oyster mushroom and snow pea stir-fry over rice, standing in for shrimp.",
     "The same real king oyster mushroom stand-in used elsewhere in this plan, here in a gingery stir-fry instead of a simple pan-sear.",
     1.0, 1.0, "bowl", 49,
     [(*KING_OYSTER, 150, "g", "sliced", "Sauteed", None),
      ("Veg", "Fresh Snow Pea", 80, "g", "trimmed", "Sauteed", None),
      ("Grain", "Grains, rice, brown, long-grain, dry", 75, "g", "cooked", None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Herbs", "Ginger root", 4, "g", "grated", None, None),
      ("Legume", "Soy sauce made from soy and wheat (shoyu)", 10, "ml", None, None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 5, "ml", None, None, None)]),
    ("curated_vegan_side_tofu_bok_choy_ginger", "side",
     "Tofu with Bok Choy & Ginger",
     "Sauteed tofu with bok choy and ginger, standing in for sole.",
     "Bok choy and ginger together are a real, common pairing with a delicate white fish, and they work just as well against tofu.",
     1.0, 1.0, "plate", 50,
     [(*TOFU, 150, "g", None, "Sauteed", None),
      ("Veg", "Bok choy", 100, "g", "chopped", "Sauteed", None),
      ("Herbs", "Ginger root", 5, "g", "grated", None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Legume", "Soy sauce made from soy and wheat (shoyu)", 10, "ml", None, None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None)]),
    ("curated_vegan_side_tempeh_radish_dill", "side",
     "Tempeh with Radish & Dill",
     "Baked tempeh with roasted radish and fresh dill, standing in for trout.",
     "The same real dill this plan's own trout version uses, carried by baked tempeh instead.",
     1.0, 1.0, "plate", 51,
     [(*TEMPEH, 150, "g", None, "Baked", None),
      ("Veg", "Radish", 90, "g", "halved", "Roasted", None),
      ("Herbs", "Fresh Dill Weed", 3, "g", "chopped", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_chickpea_walnut_meatballs_tomato_sauce", "side",
     "Chickpea-Walnut Meatballs in Tomato Sauce",
     "Chickpea-and-walnut meatballs simmered in real tomato sauce, standing in for turkey.",
     "Mashed chickpea and chopped walnut bind into a genuinely hearty meatball, nutritional yeast standing in for the parmesan the original recipe used.",
     1.0, 1.0, "plate", 52,
     [(*CHICKPEA, 100, "g", "mashed", None, "as the meatball base"),
      (*WALNUT, 40, "g", "chopped", None, "as the meatball base"),
      (*FLAXSEED, 8, "g", "ground, mixed with 24g water", None, "as a binder"),
      (*NUTRITIONAL_YEAST, 5, "g", None, None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Veg", "Tomato", 200, "g", "crushed", "Simmered", None),
      ("Veg", "Onion", 30, "g", "diced", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 5, "ml", None, None, None),
      ("Herbs", "Basil", 2, "g", "chopped", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_lentil_meatloaf_parsnip_carrot", "side",
     "Lentil Meatloaf with Parsnip & Carrot",
     "A real lentil meatloaf alongside roasted parsnip and carrot, standing in for turkey.",
     "Mashed lentil holds together into a genuine sliceable loaf, with ground flaxseed doing the same binding job an egg would.",
     1.0, 1.0, "plate", 53,
     [(*GREEN_LENTIL, 100, "g", "cooked, mashed", None, "as the loaf base"),
      (*FLAXSEED, 8, "g", "ground, mixed with 24g water", None, "as a binder"),
      ("Veg", "Onion", 30, "g", "diced", None, None),
      ("Veg", "Parsnip", 70, "g", "diced", "Roasted", None),
      ("Veg", "Carrot", 60, "g", "diced", "Roasted", None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_tempeh_turnip_carrot", "side",
     "Tempeh with Turnip & Carrot",
     "Roasted tempeh with turnip and carrot, standing in for turkey thigh.",
     "The same real turnip-and-carrot roast this plan's own turkey version uses, carried by tempeh instead.",
     1.0, 1.0, "plate", 54,
     [(*TEMPEH, 150, "g", None, "Roasted", None),
      ("Veg", "Turnip", 100, "g", "diced", "Roasted", None),
      ("Veg", "Carrot", 60, "g", "diced", "Roasted", None),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Herbs", "Rosemary", 2, "g", "chopped", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None),
      ("Herbs", "Pepper, black, ground", 0.5, "g", None, None, None)]),
    ("curated_vegan_side_tempeh_wild_rice_cranberries", "side",
     "Tempeh with Wild Rice & Cranberries",
     "Roasted tempeh with wild rice and whole cranberry, standing in for turkey breast.",
     "Tart cranberry against a savory roasted protein is a real, traditional pairing that carries over cleanly onto tempeh.",
     1.0, 1.0, "bowl", 55,
     [(*TEMPEH, 150, "g", None, "Roasted", None),
      ("Grain", "Grains, rice, wild, dry", 70, "g", "cooked", None, None),
      ("Fruit", "Cranberry", 40, "g", "whole", None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_side_tofu_vegetable_fried_rice", "side",
     "Tofu Vegetable Fried Rice",
     "A real vegetable fried rice, turmeric-tofu scramble bits standing in for scrambled egg.",
     "Crumbled tofu, browned with a little turmeric, breaks up into real egg-like bits through the rest of the fried rice.",
     1.0, 1.0, "bowl", 56,
     [("Grain", "Grains, rice, brown, long-grain, dry", 100, "g", "cooked", None, None),
      (*TOFU, 100, "g", "crumbled", "Sauteed", None),
      (*TURMERIC, 0.5, "g", None, None, "for color"),
      ("Veg", "Pea, green, fresh", 40, "g", None, None, None),
      ("Veg", "Carrot", 40, "g", "diced", None, None),
      ("Veg", "Onion", 20, "g", "diced", None, None),
      ("Legume", "Soy sauce made from soy and wheat (shoyu)", 10, "ml", None, None, None),
      ("NutSeed", "Sesame seed", 5, "g", None, None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 5, "ml", None, None, None)]),
    ("curated_vegan_side_white_bean_roasted_vegetable_tofu_bowl", "side",
     "White Bean & Roasted Vegetable Bowl with Herbed Tofu",
     "Roasted zucchini, eggplant, and tomato over white bean, with lemon-marinated tofu standing in for feta.",
     "White bean already carries the real protein here; the marinated tofu adds the same tangy finish feta would.",
     1.0, 1.0, "bowl", 57,
     [(*WHITE_BEANS, 100, "g", None, None, None),
      ("Veg", "Zucchini, green skin, fresh, unpeeled", 100, "g", "diced", "Roasted", None),
      ("Veg", "Eggplant", 80, "g", "diced", "Roasted", None),
      ("Veg", "Tomato", 50, "g", "diced", None, None),
      (*TOFU, 15, "g", "crumbled", None, "marinated as a feta stand-in"),
      ("Fats", "Olive Oil (Extra Virgin)", 10, "ml", None, None, None),
      ("Fruit", "Lemon", 10, "g", "juiced", None, None),
      ("Herbs", "Oregano", 1, "g", None, None, None)]),
    # ---- Soups ----
    ("curated_vegan_soup_white_bean_vegetable_soup", "soup",
     "White Bean Vegetable Soup",
     "A real vegetable soup built on white bean instead of chicken.",
     "White bean brings a genuine plant protein into the same carrot-celery-onion base this plan's own chicken soup uses.",
     1.0, 1.0, "bowl", 58,
     [(*WHITE_BEANS, 60, "g", None, None, None),
      ("Veg", "Carrot", 25, "g", "diced", None, None),
      ("Veg", "Celery", 20, "g", "diced", None, None),
      ("Veg", "Onion", 25, "g", "diced", None, None),
      ("Veg", "Garlic", 1.5, "g", "minced", None, None),
      (*VEGETABLE_STOCK, 5, "g", None, None, None),
      ("Bev", "Water, tap", 250, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 0.75, "g", None, None, None)]),
    ("curated_vegan_soup_hearts_of_palm_corn_chowder", "soup",
     "Hearts of Palm & Corn Chowder",
     "A creamy coconut-milk corn chowder with hearts of palm, standing in for crab.",
     "Hearts of palm bring a genuine flaky texture into the same rich chowder base this plan's own crab version uses.",
     1.0, 1.0, "bowl", 59,
     [(*HEARTS_OF_PALM, 120, "g", "sliced", None, None),
      ("Veg", "Corn, sweet, yellow", 100, "g", None, None, None),
      ("Veg", "Onion", 40, "g", "diced", None, None),
      ("Veg", "Celery", 30, "g", "diced", None, None),
      ("NutSeed", "Coconut milk", 150, "ml", None, None, None),
      (*VEGETABLE_STOCK, 5, "g", None, None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_soup_white_bean_tomato_fennel_broth", "soup",
     "White Bean Tomato Fennel Broth",
     "A light tomato-fennel broth with white bean, standing in for mussels.",
     "White bean brings genuine substance to a broth this light, the same role mussels play in this plan's own original version.",
     1.0, 1.0, "bowl", 60,
     [(*WHITE_BEANS, 150, "g", None, None, None),
      ("Veg", "Tomato", 90, "g", "diced", None, None),
      ("Veg", "Fennel Bulb", 60, "g", "sliced", None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      (*VEGETABLE_STOCK, 5, "g", None, None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_soup_white_bean_tomato_garlic_broth", "soup",
     "White Bean Tomato Garlic Broth",
     "A garlicky tomato broth with white bean, standing in for mussels.",
     "The same real garlic-forward broth this plan's own mussels version uses, carried by white bean instead.",
     1.0, 1.0, "bowl", 61,
     [(*WHITE_BEANS, 150, "g", None, None, None),
      ("Veg", "Tomato", 100, "g", "diced", None, None),
      ("Veg", "Onion", 30, "g", "diced", None, None),
      ("Veg", "Garlic", 4, "g", "minced", None, None),
      (*VEGETABLE_STOCK, 5, "g", None, None, None),
      ("Fats", "Olive Oil (Extra Virgin)", 8, "ml", None, None, None),
      ("Herbs", "Parsley Spices", 5, "g", "chopped", None, None),
      ("Herbs", "Common salt/table salt", 1, "g", None, None, None)]),
    ("curated_vegan_soup_lentil_black_bean_chili", "soup",
     "Lentil Black Bean Chili",
     "A hearty two-legume chili, standing in for turkey black bean chili.",
     "Green lentil adds a real, second plant protein and a genuine meaty texture alongside the black bean.",
     1.0, 1.0, "bowl", 62,
     [(*GREEN_LENTIL, 100, "g", "cooked", "Simmered", None),
      ("Legume", "Black Beans", 100, "g", None, None, None),
      ("Veg", "Tomato", 100, "g", "diced", None, None),
      ("Veg", "Onion", 40, "g", "diced", None, None),
      ("Veg", "Red Bell Pepper", 40, "g", "diced", None, None),
      ("Veg", "Corn, sweet, yellow", 30, "g", None, None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      ("Herbs", "Cumin (cummin) seed, dried, ground", 2, "g", None, None, None),
      (*PAPRIKA, 2, "g", None, None, None),
      (*VEGETABLE_STOCK, 5, "g", None, None, None),
      ("Herbs", "Common salt/table salt", 1.5, "g", None, None, None)]),
    ("curated_vegan_soup_mushroom_white_bean_soup", "soup",
     "Mushroom White Bean Soup",
     "A savory mushroom-and-white-bean soup, standing in for turkey white bean soup.",
     "Sauteed mushroom brings a genuine, deep umami base into the same carrot-celery-onion soup this plan's own turkey version uses.",
     1.0, 1.0, "bowl", 63,
     [("Veg", "Mushroom, common, fresh", 100, "g", "sliced", "Sauteed", None),
      (*WHITE_BEANS, 80, "g", None, None, None),
      ("Veg", "Carrot", 50, "g", "diced", None, None),
      ("Veg", "Celery", 40, "g", "diced", None, None),
      ("Veg", "Onion", 40, "g", "diced", None, None),
      ("Veg", "Garlic", 3, "g", "minced", None, None),
      (*VEGETABLE_STOCK, 7.5, "g", None, None, None),
      ("Herbs", "Common salt/table salt", 1.5, "g", None, None, None)]),
]


def main():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    for recipe_id, builder_type, name, flavor_profile, health_benefit, servings, serving_size_amount, \
            serving_size_unit, sort_order, ingredients in RECIPES:
        cur.execute(
            """
            INSERT INTO curated_recipes
                (id, builder_type, name, flavor_profile, health_benefit, servings,
                 serving_size_amount, serving_size_unit, sort_order)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(id) DO UPDATE SET
                builder_type = excluded.builder_type, name = excluded.name,
                flavor_profile = excluded.flavor_profile, health_benefit = excluded.health_benefit,
                servings = excluded.servings, serving_size_amount = excluded.serving_size_amount,
                serving_size_unit = excluded.serving_size_unit, sort_order = excluded.sort_order
            """,
            (recipe_id, builder_type, name, flavor_profile, health_benefit, servings,
             serving_size_amount, serving_size_unit, sort_order),
        )
        cur.execute("DELETE FROM curated_recipe_ingredients WHERE recipe_id = ?", (recipe_id,))
        for i, (category, base_name, quantity, unit, cut_prep, cooking_method, prep_note) in enumerate(ingredients):
            cur.execute(
                """
                INSERT INTO curated_recipe_ingredients
                    (recipe_id, category, base_name, quantity, unit, cut_prep, cooking_method, prep_note, sort_order)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (recipe_id, category, base_name, quantity, unit, cut_prep, cooking_method, prep_note, i),
            )

    # Two in-place honey -> maple syrup edits, benefiting every track.
    cur.execute(
        "UPDATE curated_recipe_ingredients SET category = ?, base_name = ? "
        "WHERE recipe_id = 'curated_side_teriyaki_baked_tofu' AND base_name LIKE '%honey%'",
        MAPLE_SYRUP,
    )
    cur.execute(
        "UPDATE curated_recipe_ingredients SET category = ?, base_name = ? "
        "WHERE recipe_id = 'curated_salad_sesame_ginger_slaw' AND base_name LIKE '%honey%'",
        MAPLE_SYRUP,
    )

    conn.commit()
    total_ingredients = sum(len(r[9]) for r in RECIPES)
    print(f"Upserted {len(RECIPES)} curated_recipes rows, {total_ingredients} curated_recipe_ingredients rows.")
    print("Honey -> maple syrup swapped on curated_side_teriyaki_baked_tofu and curated_salad_sesame_ginger_slaw.")
    conn.close()


if __name__ == "__main__":
    main()
