"""
Adds a new 'food_aliases' table to the already-built
assets/data/foods_reference.db, as a supplemental patch rather than
through scripts/build_food_reference_db.py -- same pattern as
scripts/add_water_tracking_data.py, scripts/add_supplement_powder_category.py,
and scripts/add_interaction_rules.py (see those for why patching the
compiled .db directly, rather than the spreadsheet-driven rebuild, is the
right approach in this environment).

IMPORTANT / FOLLOW-UP NEEDED: if the main spreadsheet-driven build is ever
re-run to regenerate foods_reference.db from scratch, this table will be
silently wiped. At that point, re-run this script again afterward.

What this is for: lib/db.ts's searchReferenceFoodNames() matches a typed
query against a food's own base_name/name (plus a whitespace-collapsed
variant of both). That's the right default, but it can't bridge a genuine
vocabulary gap -- someone typing the everyday name they actually know a
food by ("bell pepper", "heavy cream") when the database only has a more
formal/regional/differently-ordered name for the identical food ("Sweet
Pepper", "Heavy Whipping Cream"). food_aliases is a small, deliberately
narrow lookup table for exactly that gap: alias -> the real base_name(s) it
should also match, scoped by category since an alias is only meaningful
within the category the app is already browsing.

Every alias in scripts/food_alias_data.py was found by first confirming the
gap is real (the alias term returns zero matches against the live database
today) and each target base_name was checked to actually exist for that
category -- see that file's own module docstring. This script re-verifies
that at load time and fails loudly (not silently) if a target base_name
has drifted or was mistyped, rather than inserting a dangling alias that
would never actually match anything.

Safe to re-run: DROP + recreate, so stale aliases from a previous version
of food_alias_data.py never linger.

Usage:
  py scripts/add_food_aliases.py
"""
import datetime
import sqlite3
from pathlib import Path

from food_alias_data import FOOD_ALIASES

DB_PATH = Path(__file__).resolve().parent.parent / "assets" / "data" / "foods_reference.db"
VERSION_TS_PATH = Path(__file__).resolve().parent.parent / "lib" / "referenceDbVersion.ts"


def main():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()

    cur.execute("DROP TABLE IF EXISTS food_aliases")
    cur.execute(
        """
        CREATE TABLE food_aliases (
            alias TEXT NOT NULL COLLATE NOCASE,
            base_name TEXT NOT NULL COLLATE NOCASE,
            food_category TEXT NOT NULL,
            reason TEXT NOT NULL,
            UNIQUE (alias, base_name, food_category)
        )
        """
    )
    cur.execute("CREATE INDEX idx_food_aliases_alias ON food_aliases(alias)")

    rows = []
    missing = []
    for category, alias, base_names, reason in FOOD_ALIASES:
        for base_name in base_names:
            exists = cur.execute(
                "SELECT 1 FROM foods WHERE category = ? AND base_name = ? COLLATE NOCASE LIMIT 1",
                (category, base_name),
            ).fetchone()
            if not exists:
                missing.append((category, alias, base_name))
                continue
            rows.append((alias, base_name, category, reason))

    if missing:
        details = "\n".join(f"  ({cat!r}, alias={alias!r}) -> base_name {bn!r} not found" for cat, alias, bn in missing)
        raise RuntimeError(
            f"food_alias_data.py references {len(missing)} base_name(s) that don't exist in "
            f"the current foods table -- fix food_alias_data.py rather than insert a dangling "
            f"alias:\n{details}"
        )

    cur.executemany(
        "INSERT INTO food_aliases (alias, base_name, food_category, reason) VALUES (?, ?, ?, ?)",
        rows,
    )
    print(f"Inserted {len(rows)} food_aliases rows (from {len(FOOD_ALIASES)} alias entries).")

    conn.commit()
    conn.close()

    version = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    VERSION_TS_PATH.write_text(
        '// Auto-generated by scripts/build_food_reference_db.py (bumped manually here by\n'
        '// scripts/add_food_aliases.py, which patches the compiled .db directly) --\n'
        '// do not edit by hand.\n'
        f'export const REFERENCE_DB_VERSION = "{version}";\n',
        encoding="utf-8",
    )
    print(f"Bumped REFERENCE_DB_VERSION to {version}.")


if __name__ == "__main__":
    main()
