/* global __dirname */
// Measures how far each TabHub icon's painted pixels reach from the centre
// of its image, and writes constants/tabHubIconReach.ts.
//
// 2026-10-07, direct request: "Can we make each one the largest size they
// can be inside of the pressed-in circle? We don't want them touching the
// edges at all, just as large as they can reasonably be inside of the
// circle." The icon is drawn centred on the well, so the one number that
// decides how big it can go is the distance from the image centre to its
// farthest painted pixel. Sizing by the image's rectangle instead (its
// corners on the circle) left most icons well short of the edge, since
// artwork rarely reaches the corners of its own box.
//
// Run it again whenever an icon file is added or replaced:
//   node scripts/measure_tab_hub_icons.js
// It also fails if a file's size no longer matches the pixel pair recorded
// for it in TAB_HUB_ICON_PIXEL_DIMENSIONS.

const fs = require('fs');
const path = require('path');
const { PNG } = require('pngjs');

const ROOT = path.join(__dirname, '..');
const SOURCE = path.join(ROOT, 'constants', 'tabHubIcons.ts');
const OUT = path.join(ROOT, 'constants', 'tabHubIconReach.ts');
// Antialiased edge pixels fainter than this do not read as part of the shape.
const ALPHA_THRESHOLD = 24;

const src = fs.readFileSync(SOURCE, 'utf8');

function section(startMarker) {
  const start = src.indexOf(startMarker);
  if (start < 0) throw new Error('missing ' + startMarker);
  return src.slice(start, src.indexOf('\n};', start));
}

const sources = {};
for (const m of section('export const TAB_HUB_ICON_SOURCES').matchAll(/^\s*(\w+): require\('([^']+)'\)/gm)) {
  sources[m[1]] = path.join(ROOT, 'constants', m[2]);
}
const dims = {};
for (const m of section('const TAB_HUB_ICON_PIXEL_DIMENSIONS').matchAll(/^\s*(\w+): \[(\d+), (\d+)\]/gm)) {
  dims[m[1]] = [Number(m[2]), Number(m[3])];
}

const reach = {};
const problems = [];
for (const [key, file] of Object.entries(sources)) {
  const png = PNG.sync.read(fs.readFileSync(file));
  const { width, height, data } = png;
  const recorded = dims[key];
  if (!recorded) problems.push(`${key}: no pixel pair in TAB_HUB_ICON_PIXEL_DIMENSIONS`);
  else if (recorded[0] !== width || recorded[1] !== height) {
    problems.push(`${key}: file is ${width}x${height}, recorded as ${recorded[0]}x${recorded[1]}`);
  }
  const cx = width / 2;
  const cy = height / 2;
  let farthest = 0;
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      if (data[(y * width + x) * 4 + 3] < ALPHA_THRESHOLD) continue;
      // The pixel's far corner, so a pixel touching the edge counts in full.
      const dx = Math.max(Math.abs(x - cx), Math.abs(x + 1 - cx));
      const dy = Math.max(Math.abs(y - cy), Math.abs(y + 1 - cy));
      const d = Math.hypot(dx, dy);
      if (d > farthest) farthest = d;
    }
  }
  // As a fraction of the image's height, so the number holds at any size.
  reach[key] = Math.round((farthest / height) * 10000) / 10000;
}

if (problems.length) {
  console.error(problems.join('\n'));
  process.exit(1);
}

const lines = Object.entries(reach).map(([k, v]) => `  ${k}: ${v},`);
const out =
  '// Generated by scripts/measure_tab_hub_icons.js. Do not edit by hand.\n' +
  '//\n' +
  "// For each TabHub icon, the distance from its image's centre to its\n" +
  "// farthest painted pixel, as a fraction of the image's height.\n" +
  '// getTabHubIconRenderSize in constants/tabHubIcons.ts sizes each icon so\n' +
  '// that point lands just inside the pressed-in well.\n\n' +
  'export const TAB_HUB_ICON_REACH: Record<string, number> = {\n' +
  lines.join('\n') +
  '\n};\n';
fs.writeFileSync(OUT, out);
console.log(`Measured ${lines.length} icons into constants/tabHubIconReach.ts`);
